"""Template-based practice question variants — NEVER presented as official PYQ.

Only approved deterministic types are generated. Every item is labeled
`generated_by = "deterministic_python"` and `source = "DETERMINISTIC_PRACTICE"`.
"""
from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Literal, Sequence

ApprovedType = Literal[
    "percentage",
    "simple_arithmetic",
    "number_series",
    "coding_decoding",
    "directions",
    "synonym",
    "antonym",
    "static_gk",
]

APPROVED_TYPES: tuple[ApprovedType, ...] = (
    "percentage",
    "simple_arithmetic",
    "number_series",
    "coding_decoding",
    "directions",
    "synonym",
    "antonym",
    "static_gk",
)

GENERATED_BY = "deterministic_python"
GENERATOR_VERSION = "1.2.0"
# Must satisfy questions_source_check: OFFICIAL_PYP|AI_GENERATED|USER_UPLOAD|ORIGINAL|INTERNAL|PUBLIC_DOMAIN
PRACTICE_SOURCE = "INTERNAL"
PRACTICE_SOURCE_TYPE = "generated_practice"
PRACTICE_DISCLAIMER = (
    "Deterministic practice variant generated by Python templates. "
    "Not an official previous-year question."
)

# Map blueprint section codes → approved generator families
SECTION_TYPE_MAP: dict[str, tuple[ApprovedType, ...]] = {
    "quant": ("percentage", "simple_arithmetic"),
    "quantitative": ("percentage", "simple_arithmetic"),
    "qa": ("percentage", "simple_arithmetic"),
    "math": ("percentage", "simple_arithmetic"),
    "reasoning": ("number_series", "coding_decoding", "directions"),
    "logical": ("number_series", "coding_decoding", "directions"),
    "english": ("synonym", "antonym"),
    "eng": ("synonym", "antonym"),
    "ga": ("static_gk",),
    "gk": ("static_gk",),
    "general": ("static_gk",),
    "awareness": ("static_gk",),
    "gs": ("static_gk",),
}


@dataclass(frozen=True)
class DeterministicQuestion:
    question_text: str
    options: list[str]
    correct_index: int
    subject: str
    topic: str
    difficulty: str
    explanation: str
    question_type: ApprovedType
    generated_by: str = GENERATED_BY
    source: str = PRACTICE_SOURCE
    source_reference: str | None = None
    is_current_affairs: bool = False

    def to_insert_row(
        self,
        *,
        exam_type: str,
        owner: str | None,
        language: str,
    ) -> dict[str, Any]:
        return {
            "question_text": self.question_text,
            "question_type": "MCQ",
            "options": [
                {"label": chr(65 + idx), "text": text}
                for idx, text in enumerate(self.options)
            ],
            "correct_answer": chr(65 + self.correct_index),
            "explanation": self.explanation,
            "subject": self.subject,
            "topic": self.topic,
            "difficulty": self.difficulty,
            "exam_type": exam_type,
            "source": PRACTICE_SOURCE,
            "source_type": PRACTICE_SOURCE_TYPE,
            "marks_positive": 1.0,
            "marks_negative": 0.25,
            "is_public": False,
            "is_verified": False,
            "publish_status": "draft",
            "review_status": "unreviewed",
            "uploaded_by": owner,
            "created_by": owner,
            "latex_present": False,
            "has_image": False,
            "metadata": {
                "generated_by": GENERATED_BY,
                "generation_method": "template_variant",
                "generator_version": GENERATOR_VERSION,
                "quality_algorithm_version": "gov_question_quality_v2",
                "dedup_algorithm_version": "gov_question_dedup_v2",
                "template_id": self.question_type,
                "question_type": self.question_type,
                "language": language,
                "disclaimer": PRACTICE_DISCLAIMER,
                "official_pyq": False,
                "ai_generated": False,
                "source_type": PRACTICE_SOURCE_TYPE,
                "source_class": "deterministic_practice",
                "source_reference": self.source_reference,
                "is_current_affairs": self.is_current_affairs,
                "created_at": datetime.now(timezone.utc).isoformat(),
            },
        }


def _seed_int(seed: str, salt: int) -> int:
    digest = hashlib.sha256(f"{seed}:{salt}".encode()).hexdigest()
    return int(digest[:8], 16)


def _unique_distractors(correct: int, values: list[int]) -> list[int]:
    """Build four distinct option values with `correct` among them."""
    pool = [correct]
    for value in values:
        if value != correct and value not in pool:
            pool.append(value)
        if len(pool) >= 4:
            break
    offset = 1
    while len(pool) < 4:
        candidate = correct + offset
        if candidate not in pool:
            pool.append(candidate)
        offset += 1
    return pool[:4]


def _place_correct(options_nums: list[int], correct: int, slot: int) -> list[int]:
    nums = list(options_nums)
    if correct not in nums:
        nums[0] = correct
    current = nums.index(correct)
    nums[current], nums[slot] = nums[slot], correct
    return nums


def generate_percentage(seed: str, index: int) -> DeterministicQuestion:
    base = 40 + (_seed_int(seed, index) % 61)
    pct = 5 + (_seed_int(seed, index + 17) % 46)
    correct = round(base * pct / 100)
    distractors = _unique_distractors(
        correct,
        [correct + 5, correct - 5, round(base * (pct + 10) / 100), base - correct],
    )
    slot = _seed_int(seed, index + 3) % 4
    options_nums = _place_correct(distractors, correct, slot)
    return DeterministicQuestion(
        question_text=f"What is {pct}% of {base}?",
        options=[str(v) for v in options_nums],
        correct_index=slot,
        subject="Quantitative Aptitude",
        topic="Percentage",
        difficulty="EASY",
        explanation=f"{pct}% of {base} = ({pct}/100)×{base} = {correct}. {PRACTICE_DISCLAIMER}",
        question_type="percentage",
    )


def generate_simple_arithmetic(seed: str, index: int) -> DeterministicQuestion:
    a = 12 + (_seed_int(seed, index) % 40)
    b = 3 + (_seed_int(seed, index + 9) % 20)
    op_idx = _seed_int(seed, index + 2) % 3
    if op_idx == 0:
        correct = a + b
        stem = f"What is {a} + {b}?"
        explanation = f"{a} + {b} = {correct}."
    elif op_idx == 1:
        correct = a - b
        stem = f"What is {a} − {b}?"
        explanation = f"{a} − {b} = {correct}."
    else:
        correct = a * b
        stem = f"What is {a} × {b}?"
        explanation = f"{a} × {b} = {correct}."
    distractors = _unique_distractors(correct, [correct + 2, correct - 2, correct + b, a])
    slot = _seed_int(seed, index + 5) % 4
    options_nums = _place_correct(distractors, correct, slot)
    return DeterministicQuestion(
        question_text=stem,
        options=[str(v) for v in options_nums],
        correct_index=slot,
        subject="Quantitative Aptitude",
        topic="Arithmetic",
        difficulty="EASY",
        explanation=f"{explanation} {PRACTICE_DISCLAIMER}",
        question_type="simple_arithmetic",
    )


def generate_number_series(seed: str, index: int) -> DeterministicQuestion:
    start = 2 + (_seed_int(seed, index) % 10)
    step = 2 + (_seed_int(seed, index + 4) % 5)
    seq = [start + i * step for i in range(4)]
    correct = start + 4 * step
    distractors = _unique_distractors(
        correct, [correct + step, correct - step, correct + 1, seq[-1] + 2]
    )
    slot = _seed_int(seed, index + 7) % 4
    options_nums = _place_correct(distractors, correct, slot)
    series = ", ".join(str(n) for n in seq)
    return DeterministicQuestion(
        question_text=f"Find the next number in the series: {series}, ?",
        options=[str(v) for v in options_nums],
        correct_index=slot,
        subject="Reasoning",
        topic="Number Series",
        difficulty="EASY",
        explanation=f"Common difference is {step}; next term is {correct}. {PRACTICE_DISCLAIMER}",
        question_type="number_series",
    )


def generate_coding_decoding(seed: str, index: int) -> DeterministicQuestion:
    word = ["CAT", "DOG", "BAT", "PEN", "SUN"][_seed_int(seed, index) % 5]
    shift = 1 + (_seed_int(seed, index + 1) % 3)
    encoded = "".join(chr((ord(c) - 65 + shift) % 26 + 65) for c in word)
    distractors = _unique_distractors(shift, [shift + 1, shift - 1 if shift > 1 else 4, 2, 3])
    slot = _seed_int(seed, index + 8) % 4
    options_nums = _place_correct(distractors, shift, slot)
    return DeterministicQuestion(
        question_text=(
            f"In a certain code, {word} is written as {encoded} by shifting each letter "
            f"forward by a fixed number. What is the shift?"
        ),
        options=[str(v) for v in options_nums],
        correct_index=slot,
        subject="Reasoning",
        topic="Coding-Decoding",
        difficulty="MEDIUM",
        explanation=f"Each letter advances by {shift}. {PRACTICE_DISCLAIMER}",
        question_type="coding_decoding",
    )


def generate_directions(seed: str, index: int) -> DeterministicQuestion:
    north = 5 + (_seed_int(seed, index) % 10)
    east = 3 + (_seed_int(seed, index + 6) % 8)
    correct = round(math.sqrt(north**2 + east**2), 1)
    candidates = [
        correct,
        round(north + east, 1),
        round(abs(north - east), 1),
        round(math.sqrt(north**2 + (east + 2) ** 2), 1),
    ]
    seen: set[str] = set()
    options: list[str] = []
    for value in candidates:
        text = str(value)
        if text not in seen:
            seen.add(text)
            options.append(text)
    while len(options) < 4:
        pad = str(round(correct + len(options), 1))
        if pad not in seen:
            seen.add(pad)
            options.append(pad)
    slot = _seed_int(seed, index + 11) % 4
    correct_text = str(correct)
    if correct_text in options:
        cur = options.index(correct_text)
        options[cur], options[slot] = options[slot], correct_text
    else:
        options[slot] = correct_text
    return DeterministicQuestion(
        question_text=(
            f"A person walks {north} km north and then {east} km east. "
            f"How far is the person from the starting point (km, approximate)?"
        ),
        options=options[:4],
        correct_index=slot,
        subject="Reasoning",
        topic="Directions",
        difficulty="MEDIUM",
        explanation=(
            f"Displacement = √({north}² + {east}²) ≈ {correct}. {PRACTICE_DISCLAIMER}"
        ),
        question_type="directions",
    )


_SYNONYM_PAIRS = (
    ("Abundant", "Plentiful", "Scarce", "Tiny", "Weak"),
    ("Rapid", "Swift", "Slow", "Lazy", "Dull"),
    ("Honest", "Truthful", "Corrupt", "Rude", "Harsh"),
    ("Bright", "Radiant", "Dim", "Faint", "Pale"),
)

_ANTONYM_PAIRS = (
    ("Brave", "Timid", "Courageous", "Bold", "Heroic"),
    ("Ancient", "Modern", "Old", "Historic", "Past"),
    ("Transparent", "Opaque", "Clear", "Bright", "Visible"),
    ("Scarce", "Abundant", "Rare", "Limited", "Sparse"),
)

# Static verified facts only — never treated as current affairs or official PYQ.
_GK_FACTS = (
    ("Who was the first President of India?", "Dr. Rajendra Prasad", "Jawaharlal Nehru", "Sardar Patel", "B.R. Ambedkar", "static:india_presidents"),
    ("The Reserve Bank of India was established in which year?", "1935", "1947", "1950", "1969", "static:rbi_establishment_1935"),
    ("Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Mercury", "static:solar_system"),
    ("GST was implemented in India in which year?", "2017", "2015", "2016", "2018", "static:india_gst_2017"),
)


def generate_synonym(seed: str, index: int) -> DeterministicQuestion:
    word, correct, *wrongs = _SYNONYM_PAIRS[_seed_int(seed, index) % len(_SYNONYM_PAIRS)]
    options = [correct, *wrongs]
    slot = _seed_int(seed, index + 3) % 4
    options[0], options[slot] = options[slot], options[0]
    # Ensure correct at slot
    if correct in options:
        cur = options.index(correct)
        options[cur], options[slot] = options[slot], correct
    return DeterministicQuestion(
        question_text=f'Choose the synonym of "{word}":',
        options=options[:4],
        correct_index=slot,
        subject="English Language",
        topic="Vocabulary",
        difficulty="EASY",
        explanation=f'Synonym of {word} is {correct}. {PRACTICE_DISCLAIMER}',
        question_type="synonym",
    )


def generate_antonym(seed: str, index: int) -> DeterministicQuestion:
    word, correct, *wrongs = _ANTONYM_PAIRS[_seed_int(seed, index) % len(_ANTONYM_PAIRS)]
    options = [correct, *wrongs]
    slot = _seed_int(seed, index + 5) % 4
    if correct in options:
        cur = options.index(correct)
        options[cur], options[slot] = options[slot], correct
    return DeterministicQuestion(
        question_text=f'Choose the antonym of "{word}":',
        options=options[:4],
        correct_index=slot,
        subject="English Language",
        topic="Vocabulary",
        difficulty="EASY",
        explanation=f'Antonym of {word} is {correct}. {PRACTICE_DISCLAIMER}',
        question_type="antonym",
    )


def generate_static_gk(seed: str, index: int) -> DeterministicQuestion:
    stem, correct, w1, w2, w3, source_ref = _GK_FACTS[_seed_int(seed, index) % len(_GK_FACTS)]
    options = [correct, w1, w2, w3]
    slot = _seed_int(seed, index + 7) % 4
    if correct in options:
        cur = options.index(correct)
        options[cur], options[slot] = options[slot], correct
    # Lightly vary stem with index so near-dup detection does not collapse all GK
    varied = f"{stem} (practice set {(_seed_int(seed, index) % 97) + 1})"
    return DeterministicQuestion(
        question_text=varied,
        options=options[:4],
        correct_index=slot,
        subject="General Awareness",
        topic="Static GK",
        difficulty="EASY",
        explanation=f"{correct}. {PRACTICE_DISCLAIMER}",
        question_type="static_gk",
        source_reference=source_ref,
        is_current_affairs=False,
    )


_GENERATORS = {
    "percentage": generate_percentage,
    "simple_arithmetic": generate_simple_arithmetic,
    "number_series": generate_number_series,
    "coding_decoding": generate_coding_decoding,
    "directions": generate_directions,
    "synonym": generate_synonym,
    "antonym": generate_antonym,
    "static_gk": generate_static_gk,
}


def types_for_section(section_code: str, section_name: str = "") -> tuple[ApprovedType, ...]:
    key = (section_code or "").strip().lower()
    if key in SECTION_TYPE_MAP:
        return SECTION_TYPE_MAP[key]
    name = (section_name or "").strip().lower()
    for needle, types in (
        ("quant", SECTION_TYPE_MAP["quant"]),
        ("reason", SECTION_TYPE_MAP["reasoning"]),
        ("english", SECTION_TYPE_MAP["english"]),
        ("aware", SECTION_TYPE_MAP["ga"]),
        ("general", SECTION_TYPE_MAP["ga"]),
    ):
        if needle in key or needle in name:
            return types
    return APPROVED_TYPES


def generate_practice_variants(
    *,
    count: int,
    seed: str,
    allowed_types: Sequence[ApprovedType] | None = None,
    section_code: str | None = None,
    section_name: str | None = None,
) -> list[DeterministicQuestion]:
    """Generate up to `count` labeled practice variants for approved types only."""
    if count <= 0:
        return []
    if allowed_types:
        types = [t for t in allowed_types if t in APPROVED_TYPES]
    elif section_code or section_name:
        types = list(types_for_section(section_code or "", section_name or ""))
    else:
        types = list(APPROVED_TYPES)
    if not types:
        return []

    out: list[DeterministicQuestion] = []
    for i in range(count):
        qtype = types[i % len(types)]
        out.append(_GENERATORS[qtype](seed, i))
    return out
