import { describe, expect, it } from "vitest";
import {
  customPracticeSetLabel,
  decideQuestionInventory,
  formatInventoryCoverage,
  generateButtonLabel,
  generationSourceSummary,
} from "@/lib/gov-exam/questionInventoryPolicy";

describe("question inventory policy", () => {
  it("blocks a 100-question paper when only 23 approved items exist", () => {
    const decision = decideQuestionInventory({ available: 23, requested: 100 });
    expect(decision.canGenerateRequested).toBe(false);
    expect(decision.reason).toBe("short");
    expect(decision.customPracticeMax).toBe(23);
    expect(formatInventoryCoverage(23, 100)).toBe("23 / 100 questions available");
    expect(customPracticeSetLabel(23)).toBe("Generate Custom Practice Set — up to 23 questions");
  });

  it("allows generation when inventory meets the request", () => {
    const decision = decideQuestionInventory({ available: 25, requested: 25 });
    expect(decision.canGenerateRequested).toBe(true);
    expect(decision.reason).toBe("ok");
  });

  it("treats empty banks as not generatable", () => {
    const decision = decideQuestionInventory({ available: 0, requested: 10 });
    expect(decision.canGenerateRequested).toBe(false);
    expect(decision.reason).toBe("empty");
  });
});

describe("AI-assisted generation", () => {
  it("allows a 100-question paper from 21 bank items when AI fill is available", () => {
    const decision = decideQuestionInventory({
      available: 21,
      requested: 100,
      aiFillAvailable: true,
    });

    expect(decision.canGenerateRequested).toBe(true);
    expect(decision.mode).toBe("ai_assisted");
    expect(decision.reason).toBe("ai_fill");
    expect(decision.aiQuestions).toBe(79);
    expect(generateButtonLabel(decision)).toBe(
      "Generate Full AI Mock Paper — 100 questions",
    );
    expect(generationSourceSummary(decision)).toBe(
      "21 from the approved bank, 79 generated by AI to the official blueprint.",
    );
  });

  it("generates a whole paper when the bank is completely empty", () => {
    const decision = decideQuestionInventory({
      available: 0,
      requested: 100,
      aiFillAvailable: true,
    });

    expect(decision.canGenerateRequested).toBe(true);
    expect(decision.aiQuestions).toBe(100);
    expect(generationSourceSummary(decision)).toContain("All 100 questions");
  });

  it("still prefers the bank when it already covers the request", () => {
    const decision = decideQuestionInventory({
      available: 120,
      requested: 100,
      aiFillAvailable: true,
    });

    expect(decision.mode).toBe("bank_only");
    expect(decision.aiQuestions).toBe(0);
    expect(generateButtonLabel(decision)).toBe(
      "Generate Full Mock Paper — 100 questions",
    );
    expect(generationSourceSummary(decision)).toBe(
      "All 100 questions come from the approved bank.",
    );
  });

  it("keeps blocking a short bank when the plan has no AI capability", () => {
    const decision = decideQuestionInventory({
      available: 21,
      requested: 100,
      aiFillAvailable: false,
    });

    expect(decision.canGenerateRequested).toBe(false);
    expect(decision.mode).toBe("blocked");
    expect(decision.customPracticeMax).toBe(21);
  });
});
