"""Black-box cases — Practice Coach, Live, Mock, Gov Exams, AI Coach, Prep, Docs."""
from __future__ import annotations

from .common import SITE, tc

B = SITE


def practice_coach_cases() -> list[dict]:
    return [
        tc("TC-PC-001", "Practice Coach", "Setup wizard required fields",
           f"1. Open {B}/app/live.\n2. Leave required fields empty; try Start.\n3. Fill required fields with valid data.",
           "1. Setup loads.\n2. Validation blocks start.\n3. Valid data enables start.",
           "Setup validates required fields before start.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Setup"),
        tc("TC-PC-002", "Practice Coach", "Microphone permission denied",
           "1. Deny microphone in browser prompt.\n2. Attempt to start Practice Coach.\n3. Observe guidance.",
           "1. Permission denied.\n2. Start blocked or clear error.\n3. User told how to enable mic — no silent hang.",
           "Mic denial fails gracefully with actionable message.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="Audio"),
        tc("TC-PC-003", "Practice Coach", "Microphone permission granted — session starts",
           "1. Allow microphone.\n2. Complete setup and start.\n3. Confirm session UI / overlay appears.",
           "1. Mic allowed.\n2. Start succeeds (or clear credit/plan gate).\n3. Live session UI visible.",
           "With mic + credits, session starts.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Session"),
        tc("TC-PC-004", "Practice Coach", "Consent / compliance banner",
           "1. Start session.\n2. Read consent/compliance messaging if shown.\n3. Accept/continue as required.",
           "1. Session path begins.\n2. Consent visible when required.\n3. Cannot proceed without required acknowledgment if product requires it.",
           "Consent requirements are enforceable and visible.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Compliance"),
        tc("TC-PC-005", "Practice Coach", "Current question / hint / AI answer visible",
           "1. In active session, trigger hint/AI help controls.\n2. Speak or use chat if available.\n3. Observe responses appear in UI.",
           "1. Controls respond.\n2. Input accepted.\n3. AI content appears OR clear failure (not infinite Generating).",
           "Hints/AI answers are real responses or honest failures.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="AI Help",
           notes="Bubble alone ≠ Pass."),
        tc("TC-PC-006", "Practice Coach", "Transcript updates",
           "1. Speak a short phrase with mic on.\n2. Watch transcript panel.\n3. Pause speaking; confirm no runaway ghosts.",
           "1. Audio captured.\n2. Transcript text appears within reasonable time OR STT error shown.\n3. Stable UI.",
           "Transcript reflects speech or shows STT failure clearly.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Transcript"),
        tc("TC-PC-007", "Practice Coach", "Chat during session",
           "1. Open session chat if present.\n2. Send a message.\n3. Wait for reply.\n4. Duplicate-click Send once.",
           "1. Chat opens.\n2. Message sends.\n3. Reply or clear error.\n4. No duplicate charge storm / duplicate posts beyond product rules.",
           "In-session chat works; duplicate send is safe.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Chat"),
        tc("TC-PC-008", "Practice Coach", "Hotkeys",
           "1. Open hotkey help if available.\n2. Trigger documented hotkeys (hint, hide, end) where safe.\n3. Confirm UI reacts.",
           "1. Help lists keys.\n2. Keys perform actions.\n3. No stuck overlay.",
           "Documented hotkeys work in session.",
           priority="P2", severity="Minor", account="SUFFICIENT_CREDIT_01", sub="Hotkeys"),
        tc("TC-PC-009", "Practice Coach", "Pause and resume",
           "1. Start session.\n2. Pause if control exists.\n3. Resume.\n4. Confirm timers/transcript behavior.",
           "1. Active.\n2. Paused state clear.\n3. Resumes.\n4. No corrupt UI state.",
           "Pause/resume works without breaking the session.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Session"),
        tc("TC-PC-010", "Practice Coach", "End session → summary",
           "1. End session via End control.\n2. View summary.\n3. Refresh summary/sessions list.\n4. Reopen session record.",
           "1. Session ends.\n2. Summary shown.\n3. Record persists.\n4. Detail still available.",
           "Ending session produces a persisted summary.",
           priority="P0", severity="Critical", test_type="Persistence", account="SUFFICIENT_CREDIT_01", sub="End"),
        tc("TC-PC-011", "Practice Coach", "Refresh mid-session restore",
           "1. Start session; note session URL if present.\n2. Refresh.\n3. Observe restore or safe end.",
           "1. Active.\n2. Reload.\n3. Either restores cleanly or ends with clear message — not a stuck blank overlay.",
           "Refresh mid-session is recoverable.",
           priority="P1", severity="Major", test_type="Persistence", account="SUFFICIENT_CREDIT_01", sub="Restore"),
        tc("TC-PC-012", "Practice Coach", "Insufficient credits blocks AI",
           "1. Login ZERO_CREDIT_01.\n2. Attempt Practice Coach AI features / start if credit-gated.\n3. Observe messaging.",
           "1. Zero balance visible.\n2. Action blocked or upgrade prompt.\n3. No false success; no infinite spinner.",
           "Zero credits fail gracefully for credit-gated coach actions.",
           priority="P0", severity="Critical", test_type="Negative", account="ZERO_CREDIT_01", sub="Credits"),
        tc("TC-PC-013", "Practice Coach", "AI unavailable visible failure",
           "1. If QA lead provides AI-down window OR simulate offline after start.\n"
           "2. Request AI hint/answer.\n3. Observe UI for timeout ≤ product SLA.",
           "1. Failure mode active.\n2. Request attempted.\n3. Clear error or fallback — never endless Generating; no false credit error if credits remain.",
           "AI outage surfaces honest user-visible failure/fallback.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="AI Fallback",
           notes="Coordinate AI-down window with QA lead."),
        tc("TC-PC-014", "Practice Coach", "Deepgram / STT unavailable",
           "1. During QA STT-down window (or deny/network block STT host if permitted).\n"
           "2. Speak.\n3. Observe status badge/error.",
           "1. STT impaired.\n2. Speech attempted.\n3. Clear audio/STT error; session can be ended safely.",
           "STT failure is visible and non-destructive.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="STT"),
        tc("TC-PC-015", "Practice Coach", "System/tab audio where supported",
           "1. Follow in-app guide for system/tab audio.\n2. Grant or deny.\n3. Record observed behavior.",
           "1. Guide/steps available.\n2. Permission path works.\n3. Denial shows guidance; grant enables capture OR Unavailable if unsupported browser.",
           "System/tab audio path is honest per browser support.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Audio"),
        tc("TC-PC-016", "Practice Coach", "Rate limit visible",
           "1. Rapidly request AI help many times.\n2. Observe rate-limit messaging if triggered.",
           "1. Bursts sent.\n2. 429/rate-limit message or throttle — app remains usable.",
           "Rate limiting is user-visible and non-corrupting.",
           priority="P2", severity="Minor", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="Limits"),
    ]


def live_copilot_cases() -> list[dict]:
    return [
        tc("TC-LIVE-001", "Live Copilot", "Overlay opens",
           f"1. From Practice Coach start path, open overlay ({B}/app/live/overlay if routed).\n"
           "2. Confirm overlay chrome (question, hints, controls).",
           "1. Overlay route/UI opens.\n2. Core panels visible; not blank.",
           "Live overlay UI loads.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01"),
        tc("TC-LIVE-002", "Live Copilot", "Overlay hide / stealth controls",
           "1. Use hide/stealth controls if present.\n2. Restore visibility.\n3. Confirm app still responsive.",
           "1. Overlay hides/minimizes.\n2. Restores.\n3. No stuck invisible blocking layer.",
           "Hide/show overlay works safely.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-LIVE-003", "Live Copilot", "Overlay resize / position",
           "1. Drag/resize overlay if handles exist.\n2. Refresh if session restores.\n3. Note whether position persists.",
           "1. Move/resize works.\n2. Session recoverable.\n3. Persistence matches product (document actual).",
           "Overlay window management works.",
           priority="P2", severity="Minor", account="SUFFICIENT_CREDIT_01"),
        tc("TC-LIVE-004", "Live Copilot", "Network badge / offline",
           "1. Go offline mid-overlay (DevTools Offline).\n2. Observe badge/error.\n3. Go online; confirm recovery or safe end.",
           "1. Offline.\n2. Visible network error.\n3. Recovers or ends cleanly.",
           "Overlay handles offline visibly.",
           priority="P1", severity="Major", test_type="Negative", account="SUFFICIENT_CREDIT_01"),
        tc("TC-LIVE-005", "Live Copilot", "Electron overlay note",
           "1. If desktop app provided, launch overlay path.\n2. If only web, mark Blocked by Environment for Electron-only checks.",
           "1. Desktop path available or N/A.\n2. Classification honest.",
           "Electron-specific overlay tested only when desktop build provided.",
           priority="P2", severity="Minor", account="SUFFICIENT_CREDIT_01",
           notes="Web testers mark Electron-only as Blocked by Environment."),
    ]


def mock_interview_cases() -> list[dict]:
    return [
        tc("TC-MOCK-001", "Mock Interview", "Setup and start",
           f"1. Open {B}/app/mock.\n2. Complete setup.\n3. Start mock (warmup if shown).",
           "1. Setup loads.\n2. Valid config accepted.\n3. Session starts.",
           "Mock interview can be configured and started.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-002", "Mock Interview", "TTS not treated as user answer",
           "1. Allow question TTS to play fully without speaking.\n2. Observe whether answer advances incorrectly.\n3. Provide a real answer afterward.",
           "1. TTS plays.\n2. TTS alone does not submit a user answer.\n3. Real answer captured separately.",
           "TTS audio is not mistaken for the candidate answer.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-003", "Mock Interview", "Next question",
           "1. Answer or skip to enable Next.\n2. Click Next once.\n3. Confirm new question appears.",
           "1. Ready for next.\n2. Single advance.\n3. Different question (unless bank exhausted — then clear message).",
           "Next advances exactly one question.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-004", "Mock Interview", "Skip question",
           "1. Click Skip once.\n2. Confirm advance.\n3. Rapid double-click Skip.",
           "1. Skip works.\n2. One question skipped.\n3. Double-click does not skip multiple unexpectedly.",
           "Skip is single-step safe under double-click.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-005", "Mock Interview", "Silence handling",
           "1. Remain silent for the silence timeout window.\n2. Observe prompts/auto-advance behavior.",
           "1. Silence.\n2. Clear prompt, timer, or defined auto-behavior — session not permanently stuck.",
           "Silence does not freeze the mock session.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-006", "Mock Interview", "Text answer input if available",
           "1. If text answer box exists, type an answer.\n2. Submit.\n3. Confirm acceptance.",
           "1. Input available or N/A.\n2. Submit works.\n3. Answer reflected in session flow.",
           "Text answers work when offered.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-007", "Mock Interview", "Question generation / retry",
           "1. If generation spinner appears, wait.\n2. On failure, use Retry.\n3. Confirm questions arrive or clear failure.",
           "1. Generating state temporary.\n2. Retry available on fail.\n3. No endless Generating.",
           "Question generation completes or fails honestly.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-008", "Mock Interview", "End → score → result persist",
           "1. End mock.\n2. View score/result.\n3. Refresh.\n4. Reopen from Sessions/history.",
           "1. Ends.\n2. Score/result visible.\n3. Persists.\n4. Reopenable.",
           "Mock results persist after refresh and revisit.",
           priority="P0", severity="Critical", test_type="Persistence", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-009", "Mock Interview", "Unexpected question repeat",
           "1. Complete at least 5 questions.\n2. Note question texts.\n3. Flag unexpected immediate repeats.",
           "1. Flow progresses.\n2. Texts recorded.\n3. No pathological immediate repeats unless bank size forces it (note bank size).",
           "Questions do not repeat unexpectedly within a session.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-MOCK-010", "Mock Interview", "Insufficient credits",
           "1. As ZERO_CREDIT_01 attempt mock start/AI scoring path.\n2. Observe gate.",
           "1. Attempt made.\n2. Clear credit/plan message; no half-started corrupt session.",
           "Zero credits block mock credit-gated paths cleanly.",
           priority="P1", severity="Major", test_type="Negative", account="ZERO_CREDIT_01"),
    ]


def gov_exam_cases() -> list[dict]:
    cases = [
        tc("TC-GOV-001", "Government Exams", "Hub loads",
           f"1. Login PRO_USER_01.\n2. Open {B}/app/mock-test.\n3. Observe search/selector.",
           "1. Auth ok.\n2. Hub loads (or India region gate message).\n3. Search/exam list usable.",
           "Gov exam hub is reachable and usable.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Hub"),
        tc("TC-GOV-002", "Government Exams", "Exam search — valid query",
           "1. Type a known exam name/alias (e.g. SSC/IBPS/UPSC if listed).\n2. Select a result.\n3. Open exam detail.",
           "1. Suggestions appear.\n2. Selection sticks.\n3. Detail page shows exam info.",
           "Exam search returns selectable results.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Search"),
        tc("TC-GOV-003", "Government Exams", "Exam search — nonsense query",
           "1. Search 'zzzz-not-an-exam-qqq'.\n2. Observe empty/no-result state.",
           "1. Query entered.\n2. Empty state; no crash; no random wrong exam auto-selected.",
           "Nonsense search shows empty state safely.",
           priority="P1", severity="Major", test_type="Negative", account="PRO_USER_01", sub="Search"),
        tc("TC-GOV-004", "Government Exams", "Alias resolution",
           "1. Search common aliases for a known exam.\n2. Confirm same exam selectable.",
           "1. Alias queried.\n2. Correct exam found or clear miss — document actual aliases that work.",
           "Aliases resolve to the intended exam when supported.",
           priority="P1", severity="Major", account="PRO_USER_01", sub="Search"),
        tc("TC-GOV-005", "Government Exams", "Stage / paper / language config",
           f"1. Open configure ({B}/app/mock-test/configure) for a selected exam.\n"
           "2. Set stage, paper, language.\n3. Continue.",
           "1. Config UI loads.\n2. Options apply.\n3. Proceeds to availability/generate.",
           "Exam configuration options apply correctly.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Configure"),
        tc("TC-GOV-006", "Government Exams", "Availability / approved question count",
           "1. On Review/availability panel, record the available/approved count.\n"
           "2. Open Generate for the same exam/config.\n"
           "3. Compare the available number on Generate with Review.\n"
           "4. Attempt generate when count insufficient.\n5. Attempt when sufficient.",
           "1. Counts visible.\n2. Generate screen loads.\n"
           "3. Review available == Generate available (same snapshot).\n"
           "4. Insufficient blocked with CONTENT_INSUFFICIENT or clear message — not infinite Generating.\n"
           "5. Sufficient allows generate.",
           "Availability gates generation honestly and Review matches Generate.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Availability",
           notes="Disagreeing Review vs Generate counts is Fail. If Edge 404 mark Blocked BLK-EDGE."),
        tc("TC-GOV-007", "Government Exams", "Full Mock generation",
           "1. Note credit balance.\n2. Choose Full Mock mode.\n3. Click Generate once.\n"
           "4. Wait for completion (note time) or honest failure.\n"
           "5. If completed, confirm Start Exam is enabled even if count is short of pattern (toast OK).\n"
           "6. If Edge 404 / never completes, stop and classify Blocked — do not Fail for undeployed stack.",
           "1. Balance recorded.\n2. Mode selected.\n3. Generating progress shown.\n"
           "4. Completes or clear failure ≤ timeout (CONTENT_INSUFFICIENT is Pass if bank is short).\n"
           "5. Start enabled when status=completed and mock_test_id exists.\n"
           "6. BLK-EDGE / BLK-PY recorded if functions/worker not live.",
           "Full Mock generates a startable paper or fails honestly.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Generate",
           notes="Credits reserved on create, finalized only when paper exists. Undeployed Edge/Python = Blocked."),
        tc("TC-GOV-008", "Government Exams", "Custom Practice generation",
           "1. Choose Custom Practice; set question count within allowed min/max.\n"
           "2. Generate.\n3. Verify count roughly matches request (Custom may reduce; Full Mock must not clamp this).\n"
           "4. Confirm paper is startable. This is the P0 live-proof path.",
           "1. Custom settings accepted.\n2. Generation completes or honest fail.\n"
           "3. Paper size matches config (or explains adjustment).\n4. Start Exam available.",
           "Custom Practice generation respects configured count.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Generate",
           notes="Release gate: one completed Custom/Full Mock paper on live URL. Else RELEASE BLOCKED."),
        tc("TC-GOV-009", "Government Exams", "Boundary — below min / above max questions",
           "1. Enter question count below minimum.\n2. Enter above maximum.\n3. Enter zero/empty.",
           "1. Blocked with validation.\n2. Blocked with validation.\n3. Blocked with validation.",
           "Question count boundaries are enforced in UI.",
           priority="P1", severity="Major", test_type="Boundary", account="PRO_USER_01", sub="Configure"),
        tc("TC-GOV-010", "Government Exams", "Refresh during generation",
           "1. Start Generate.\n2. While Generating, refresh page.\n3. Observe restore/fail/retry — not infinite Generating.",
           "1. Generating.\n2. Refresh.\n3. Recoverable state with truthful status.",
           "Refresh during generation does not trap the user.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="Generate"),
        tc("TC-GOV-011", "Government Exams", "Generation failure / retry",
           "1. If failure occurs (or during induced outage), read error.\n2. Click Retry.\n3. Confirm no false 'insufficient credits' when balance remains.",
           "1. Clear failure text.\n2. Retry re-attempts.\n3. Credit message only if credits actually insufficient.",
           "Generation failures are truthful and retryable.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="Generate"),
        tc("TC-GOV-012", "Government Exams", "AI gap-fill / Python fallback (user-visible)",
           "1. Generate a paper in a scenario QA lead marks as AI-impaired.\n"
           "2. Observe whether a valid fallback paper appears OR clear failure.\n"
           "3. Confirm not stuck Generating; confirm credit messaging truthful.",
           "1. Generate under AI impairment.\n2. Fallback paper OR honest failure.\n3. No infinite Generating; no false credit error.",
           "AI failure yields fallback paper or clear failure from user perspective.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="AI Fallback"),
        tc("TC-GOV-013", "Government Exams", "Question uniqueness in paper",
           "1. Open generated paper/session.\n2. Spot-check for duplicate question stems.\n3. Record duplicates if any.",
           "1. Paper open.\n2. Review performed.\n3. No unexpected duplicates (flag if found).",
           "Generated paper does not contain unexpected duplicate questions.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Quality"),
        tc("TC-GOV-014", "Government Exams", "Blueprint / marks / negative marking display",
           "1. Before/during test, locate marks and negative marking info.\n2. Answer and review score explanation after submit.",
           "1. Marking scheme visible or documented in UI.\n2. Result scoring explanation consistent with scheme shown.",
           "Marks and negative marking are visible and consistent.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Scoring"),
        tc("TC-GOV-015", "Government Exams", "Timer",
           "1. Start test; note timer and that Start Exam succeeded.\n"
           "2. Observe countdown (server clock — client must not let you add time).\n"
           "3. On expiry, observe auto-submit/lock behavior.",
           "1. Timer running from server started_at/expires_at.\n2. Decrements; refresh does not extend time.\n"
           "3. Expiry handled (auto-submit or lock) — not editable forever.",
           "Exam timer enforces time boundaries.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Runner",
           notes="If start-exam 404, Blocked BLK-EDGE."),
        tc("TC-GOV-016", "Government Exams", "Navigation palette",
           "1. Use question palette to jump.\n2. Mark for review.\n3. Return to marked question.\n"
           "4. Confirm palette states: unanswered / answered / marked / answered+marked / current.",
           "1. Jump works.\n2. Marked state visible.\n3. Return works.\n4. All five states distinguishable.",
           "Palette navigation and mark-for-review work.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Runner"),
        tc("TC-GOV-017", "Government Exams", "Answer autosave",
           "1. Select an answer.\n2. Navigate away to another question and back.\n"
           "3. Mark for review on the same save.\n4. Refresh mid-test and confirm restore.",
           "1. Answer selected.\n2. Answer retained on navigate.\n"
           "3. Marked state saved with the answer.\n"
           "4. Refresh restores answers or warns — never silent loss. Stale save skipped honestly.",
           "Answers autosave across question navigation.",
           priority="P0", severity="Critical", test_type="Persistence", account="SUFFICIENT_CREDIT_01", sub="Runner",
           notes="Versioned save-test-answer. ATTEMPT_EXPIRED / SUBMISSION_CONFLICT must be readable."),
        tc("TC-GOV-018", "Government Exams", "Partial vs final submission",
           "1. Leave some unanswered.\n2. Attempt submit; confirm warning if any.\n3. Final submit.\n4. Confirm cannot quietly resubmit altering score.",
           "1. Partial paper.\n2. Warning or allowed per product rules.\n3. Submitted.\n4. Result stable; no silent double-submit corruption.",
           "Submission handles partial answers and prevents corrupt double-submit.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Submit"),
        tc("TC-GOV-019", "Government Exams", "Result + history persistence",
           "1. After submit, open results page.\n2. Logout/login.\n3. Open history/results again.",
           "1. Score/breakdown visible.\n2. Re-auth.\n3. Same result still available to the owner.",
           "Results persist across logout/login.",
           priority="P0", severity="Critical", test_type="Persistence", account="SUFFICIENT_CREDIT_01", sub="Results"),
        tc("TC-GOV-020", "Government Exams", "Credits deducted only on success path",
           "1. Note credit balance.\n2. Generate successfully; wait until paper exists.\n"
           "3. Note new balance (finalize only on completed paper).\n"
           "4. Start a generate then Cancel OR wait for fail; confirm reserved credits return.\n"
           "5. Failed generate must not show insufficient credits if balance was enough.",
           "1. Balance recorded.\n2. Success path completes.\n3. Charge matches UI only after paper exists.\n"
           "4. Fail/cancel releases reservation.\n5. No false credit error.",
           "Credit behavior around generation is truthful (reserve → finalize / release).",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Credits",
           notes="BLK-MIG if reserve RPCs not on live DB."),
        tc("TC-GOV-021", "Government Exams", "Official paper vs realistic mock modes",
           "1. If Official/Previous Year is offered, attempt generate.\n"
           "2. Confirm fail-closed empty OR licensed PYQ — never AI-written questions labeled Official.\n"
           "3. Run Realistic or Custom and confirm it is not labeled Official PYQ.",
           "1. Mode selectable or hidden honestly.\n"
           "2. Official empty/fail-closed is Pass; AI fill labeled Official is Fail.\n"
           "3. Realistic/Custom labels match behavior.",
           "Paper modes are distinguishable; Official is never AI-filled.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Modes",
           notes="BLK-BANK is accepted for empty Official AFTER a Custom/Full Mock paper exists."),
        tc("TC-GOV-022", "Government Exams", "My questions / upload / revision / analytics pages",
           f"1. Visit {B}/app/mock-test/my-questions, /upload, /revision, /analytics.\n"
           "2. Perform one smoke action on each (list load / upload UI / revision item / chart).",
           "1. Pages open.\n2. Each shows real UI or honest empty — classify Partial if non-functional controls.",
           "Secondary gov-exam pages are reachable and classifiable.",
           priority="P1", severity="Major", account="PRO_USER_01", sub="Secondary"),
        tc("TC-GOV-023", "Government Exams", "Free user plan gate",
           "1. As FREE_USER_01 open gov exam generate for a pro-gated action.\n2. Observe upgrade/gate.",
           "1. Attempt.\n2. Clear plan gate or limited allowance — no unauthorized full generate if gated.",
           "Free users cannot bypass paid gov-exam capabilities.",
           priority="P0", severity="Critical", test_type="Security", account="FREE_USER_01", sub="Plan Gate"),
        tc("TC-GOV-024", "Government Exams", "Duplicate Generate click",
           "1. Click Generate.\n2. Immediately double-click Generate again.\n3. Observe single paper / clear handling.",
           "1. First click.\n2. Rapid second click.\n3. No duplicate charge chaos; one in-flight generation or clear queue message.",
           "Duplicate Generate clicks are safe.",
           priority="P1", severity="Major", test_type="Negative", account="SUFFICIENT_CREDIT_01", sub="Generate"),
        tc("TC-GOV-025", "Government Exams", "Cross-user result isolation",
           "1. As USER_A complete a test; copy results URL.\n2. Login USER_B; paste URL.\n3. Confirm access denied/not found.",
           "1. A has result.\n2. B opens URL.\n3. No A data shown.",
           "Gov exam results are not accessible cross-user via URL.",
           priority="P0", severity="Critical", test_type="Security", account="USER_A_01", sub="Security"),
    ]
    return cases


def gov_exam_live_cases() -> list[dict]:
    """P0 live-proof journey. Opening hub ≠ Pass. Tester = Anushka."""
    blk = (
        "If Edge 404 / Python worker down / migrations missing: Pass/Fail = Blocked with "
        "BLK-EDGE, BLK-PY, or BLK-MIG. Do not Fail undeployed stack."
    )
    live = [
        tc("TC-GOV-LIVE-01", "Government Exams", "Hub loads, no infinite Searching…",
           f"1. Login PRO_USER_01.\n2. Open {B}/app/mock-test.\n3. Wait ≤15s.\n"
           "4. Type a letter in search; confirm spinner ends.",
           "1. Auth ok.\n2. Hub renders.\n3. No infinite spinner/blank.\n4. Search idle or results — not stuck Searching…",
           "Gov hub is usable without infinite search.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Live proof",
           notes="Runnable now. DEF-001 retest."),
        tc("TC-GOV-LIVE-02", "Government Exams", "Search valid exam (SSC/IBPS/UPSC alias)",
           "1. Search a known exam/alias (SSC, IBPS, UPSC if listed).\n2. Select a result.\n3. Open exam detail.",
           "1. Suggestions appear (latest-wins; no stale overwrite).\n2. Selection sticks.\n3. Detail loads.",
           "Valid exam search returns a selectable exam.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Live proof"),
        tc("TC-GOV-LIVE-03", "Government Exams", "Nonsense search empty, no crash",
           "1. Search 'zzzz-not-an-exam-qqq'.\n2. Observe empty state.",
           "1. Query entered.\n2. Empty/no-result; no crash; no random exam auto-selected.",
           "Nonsense search is safe.",
           priority="P1", severity="Major", test_type="Negative", account="PRO_USER_01", sub="Live proof"),
        tc("TC-GOV-LIVE-04", "Government Exams", "Detail + pattern + syllabus",
           "1. Open exam detail.\n2. Confirm pattern (sections/marks) visible.\n"
           "3. Confirm syllabus OR honest SYLLABUS_NOT_AVAILABLE (no charge).",
           "1. Detail loads.\n2. Pattern shown.\n3. Syllabus present or honest unavailable — not a silent charge.",
           "Pattern/syllabus are honest.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Live proof"),
        tc("TC-GOV-LIVE-05", "Government Exams", "Review availability == Generate availability",
           "1. Record available count on Review.\n2. Open Generate for same config.\n3. Compare numbers.",
           "1. Review number recorded.\n2. Generate loads.\n3. Same available count. Disagree = Fail.",
           "Review and Generate share one availability snapshot.",
           priority="P0", severity="Critical", account="PRO_USER_01", sub="Live proof",
           notes=blk),
        tc("TC-GOV-LIVE-06", "Government Exams", "Custom Practice generate → completed paper",
           "1. Note credits.\n2. Custom Practice within min/max.\n3. Generate once.\n"
           "4. Wait until completed with mock_test_id.\n5. Start Exam.",
           "1. Balance recorded.\n2. Config accepted.\n3. Progress shown.\n"
           "4. Terminal completed (not infinite Generating).\n5. Runner opens.",
           "P0 release gate: a real Custom Practice paper exists on the live URL.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof",
           notes="GO requires this Pass (or Full Mock equivalent). " + blk),
        tc("TC-GOV-LIVE-07", "Government Exams", "Full Mock startable or honest CONTENT_INSUFFICIENT",
           "1. Choose Full Mock.\n2. Generate.\n3. If bank short, confirm fail-closed message.\n"
           "4. If completed, Start Exam works even if count is short of pattern (toast OK).",
           "1. Mode selected.\n2. Job runs.\n3. Honest CONTENT_INSUFFICIENT is Pass.\n"
           "4. Infinite Generating is Fail. Completed+short still startable.",
           "Full Mock does not trap the user.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof",
           notes=blk),
        tc("TC-GOV-LIVE-08", "Government Exams", "Official/PYQ fail-closed, never AI-labeled Official",
           "1. Choose Official / Previous Year if offered.\n2. Generate or observe empty.\n"
           "3. Confirm questions are not AI-written labeled Official.",
           "1. Mode visible or hidden honestly.\n2. Empty/fail-closed OR licensed PYQ.\n"
           "3. AI fill labeled Official = Fail.",
           "Official stays fail-closed.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes="BLK-BANK accepted only AFTER LIVE-06 Pass."),
        tc("TC-GOV-LIVE-09", "Government Exams", "Duplicate Generate = one job, no double charge",
           "1. Note credits.\n2. Click Generate.\n3. Immediately click Generate again.\n4. Observe jobs and credits.",
           "1. Baseline.\n2. First job starts.\n3. Second click does not create a second reservation.\n"
           "4. One in-flight paper or 409 replay.",
           "Duplicate Generate is safe.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes=blk),
        tc("TC-GOV-LIVE-10", "Government Exams", "Refresh during Generating = restore, not trap",
           "1. Start Generate.\n2. Refresh while Generating.\n3. Confirm restore or truthful fail/retry — not infinite Generating.",
           "1. In-flight.\n2. Refresh.\n3. Recoverable truthful status.",
           "Refresh does not trap generation.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes=blk),
        tc("TC-GOV-LIVE-11", "Government Exams", "Retry after fail; no false insufficient-credits",
           "1. If job fails (or after cancel), read error.\n2. Click Retry.\n3. Confirm credit message matches real balance.",
           "1. Clear failure.\n2. Retry re-attempts.\n3. No false insufficient credits.",
           "Failures are retryable and truthful.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes=blk),
        tc("TC-GOV-LIVE-12", "Government Exams", "Failed/cancelled generate refunds reserved credits",
           "1. Note balance.\n2. Start generate then Cancel, or wait for fail.\n3. Refresh balance.",
           "1. Baseline.\n2. Cancel/fail terminal.\n3. Reserved credits released — balance restored.",
           "Fail/cancel releases reservation.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof",
           notes=blk),
        tc("TC-GOV-LIVE-13", "Government Exams", "Successful generate finalizes credits only when paper exists",
           "1. Note balance.\n2. Complete a paper (LIVE-06).\n3. Confirm deduction happens after completed+mock_test_id, not at click.",
           "1. Baseline.\n2. Paper exists.\n3. Charge matches UI only on success path.",
           "Credits finalize only on completed paper.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof",
           notes=blk),
        tc("TC-GOV-LIVE-14", "Government Exams", "Start Exam uses server timer",
           "1. Start Exam on a completed paper.\n2. Note timer.\n3. Refresh.\n4. Confirm time did not reset/extend.",
           "1. Runner starts.\n2. Countdown visible.\n3. Refresh.\n4. Server started_at/expires_at honored.",
           "Client cannot forever-extend the exam clock.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof",
           notes="start-exam 404 = BLK-EDGE."),
        tc("TC-GOV-LIVE-15", "Government Exams", "Palette states",
           "1. Leave one unanswered.\n2. Answer one.\n3. Mark one unanswered.\n4. Answer+mark one.\n5. Observe current highlight.",
           "1–5. Palette shows unanswered / answered / marked / answered+marked / current.",
           "Palette states are complete and visible.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof"),
        tc("TC-GOV-LIVE-16", "Government Exams", "Autosave + mark-for-review persist",
           "1. Answer Q1 and mark for review.\n2. Jump to Q2 and back.\n3. Refresh.\n4. Confirm answer + marked restored.",
           "1. Saved.\n2. Retained on navigate.\n3. Refresh.\n4. Both answer and mark persist (or honest warning).",
           "Autosave and mark-for-review survive navigate and refresh.",
           priority="P0", severity="Critical", test_type="Persistence", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes="BLK-EDGE if save-test-answer missing."),
        tc("TC-GOV-LIVE-17", "Government Exams", "Submit + expiry + no corrupt double-submit",
           "1. Leave some unanswered.\n2. Submit (warning OK).\n3. Try submit again.\n"
           "4. On a second attempt, let timer expire if a short paper exists.",
           "1. Partial paper.\n2. Submitted; score shown.\n3. Second submit does not change score.\n"
           "4. Expiry auto-submits or locks.",
           "Submit is stable; expiry is enforced.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="Live proof"),
        tc("TC-GOV-LIVE-18", "Government Exams", "Result in history after logout/login",
           "1. After submit, open results.\n2. Logout.\n3. Login same user.\n4. Open history/results.",
           "1. Score visible.\n2. Logged out.\n3. Re-auth.\n4. Same result still available to owner.",
           "Results persist across sessions.",
           priority="P0", severity="Critical", test_type="Persistence", account="SUFFICIENT_CREDIT_01",
           sub="Live proof"),
        tc("TC-GOV-LIVE-19", "Government Exams", "USER_B cannot open USER_A paper/result URL",
           "1. As USER_A copy results or session URL.\n2. Login USER_B.\n3. Paste URL.",
           "1. A has URL.\n2. B session.\n3. Denied/not found — no A questions or scores.",
           "Gov papers/results are owner-isolated.",
           priority="P0", severity="Critical", test_type="Security", account="USER_A_01", sub="Live proof"),
        tc("TC-GOV-LIVE-20", "Government Exams", "Free user plan gate",
           "1. As FREE_USER_01 open generate for a gated action.\n2. Observe upgrade/gate.",
           "1. Attempt.\n2. Clear gate — no unauthorized full generate.",
           "Free users cannot bypass paid gov-exam generate.",
           priority="P0", severity="Critical", test_type="Security", account="FREE_USER_01", sub="Live proof"),
        tc("TC-GOV-LIVE-21", "Government Exams", "Zero-credit / low-credit truthful",
           "1. As ZERO_CREDIT_01 attempt generate.\n2. As LOW_CREDIT_01 (qa.lowcredit@) observe warning.\n"
           "3. Confirm neither is the past-due account.",
           "1. Zero blocked with buy/upgrade — not unknown tool.\n2. Low-credit warning if product has threshold.\n"
           "3. Fixtures are qa.zero@ / qa.lowcredit@ / qa.exactcredit@.",
           "Credit fixtures are truthful and distinct from past-due.",
           priority="P0", severity="Critical", test_type="Negative", account="ZERO_CREDIT_01",
           sub="Live proof", notes="BLK-CRED if fixtures missing."),
        tc("TC-GOV-LIVE-22", "Government Exams", "AI-down fallback; Official stays fail-closed",
           "1. If QA lead marks AI-impaired, generate Realistic/Custom.\n"
           "2. Observe fallback paper OR honest fail.\n3. Official must still fail-closed.",
           "1. Scenario started.\n2. Not infinite Generating; no false credit error.\n"
           "3. Official never AI-filled.",
           "AI-down is honest; Official never uses AI.",
           priority="P1", severity="Major", test_type="Negative", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes="Coordinate AI-down with QA lead. " + blk),
        tc("TC-GOV-LIVE-23", "Government Exams", "429/409 during poll stays in-flight",
           "1. Start Generate.\n2. Watch Network for poll 429/409/5xx.\n"
           "3. Confirm UI stays Generating (backoff) and is not SESSION_ACTION 20/min trapped.",
           "1. Job in-flight.\n2. Transient errors observed or documented as not seen.\n"
           "3. Job recovers or fails honestly — not a 20/min session trap.",
           "Poll uses JOB_POLL backoff; transient errors stay in-flight.",
           priority="P0", severity="Critical", test_type="API Observation", account="SUFFICIENT_CREDIT_01",
           sub="Live proof", notes=blk),
        tc("TC-GOV-LIVE-24", "Government Exams", "Admin ingest never auto-publishes",
           f"1. Login ADMIN_USER_01.\n2. Open {B}/app/admin/gov/ingest.\n"
           "3. Upload a small PDF if allowed.\n4. Confirm queued/needs_review — questions not live on hub.\n"
           "5. On question-review, APPROVE/REJECT required before publish.",
           "1. Admin auth.\n2. Ingest UI loads.\n3. 202 queued or honest size limit.\n"
           "4. OCR/unpublished.\n5. No auto-publish.",
           "Ingest stays unpublished until review.",
           priority="P1", severity="Major", account="ADMIN_USER_01", role="admin", sub="Live proof",
           notes="Heavy PDF 502 with no refund is Fail if credits charged."),
    ]
    for c in live:
        c["Tester"] = "Anushka"
    return live


def ai_coach_cases() -> list[dict]:

    return [
        tc("TC-AI-001", "AI Coach / Chatbot", "Open chat",
           "1. From supported surface (overlay/dashboard/support widget), open AI chat.\n2. Confirm input visible.",
           "1. Chat opens.\n2. Composer ready — opening alone is not success of AI.",
           "Chat UI opens with input.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-AI-002", "AI Coach / Chatbot", "Send message → response",
           "1. Send 'Say hello in one sentence.'\n2. Wait for response.\n3. Confirm streaming or final text.",
           "1. Message sent.\n2. Response arrives OR clear error.\n3. Not infinite thinking.",
           "Chat returns a real response or honest failure.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01",
           notes="Never Pass only because bubble opened."),
        tc("TC-AI-003", "AI Coach / Chatbot", "Conversation continuity",
           "1. Send a fact ('My target role is backend').\n2. Ask 'What role did I just say?'.\n3. Observe continuity.",
           "1. Fact sent.\n2. Follow-up sent.\n3. Reply reflects prior turn OR product states statelessness clearly.",
           "Multi-turn continuity works as designed.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-AI-004", "AI Coach / Chatbot", "Live vs Mock context",
           "1. Open chat during Live session if available; ask about current question.\n"
           "2. Repeat in Mock if available.\n3. Compare context awareness.",
           "1. Live context used or honestly absent.\n2. Mock context used or honestly absent.\n3. No fabricated session facts.",
           "Chat context matches the active mode without inventing data.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-AI-005", "AI Coach / Chatbot", "Zero credits",
           "1. As ZERO_CREDIT_01 send chat message requiring credits.\n2. Observe block.",
           "1. Send attempted.\n2. Clear insufficient credits; no fake reply billed.",
           "Chat credit gate works.",
           priority="P0", severity="Critical", test_type="Negative", account="ZERO_CREDIT_01"),
        tc("TC-AI-006", "AI Coach / Chatbot", "AI unavailable / fallback",
           "1. During AI-down window, send a message.\n2. Observe fallback or error.\n3. Confirm not stuck.",
           "1. Down mode.\n2. Fallback/error visible.\n3. UI recoverable.",
           "Chat fails gracefully when AI unavailable.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01"),
        tc("TC-AI-007", "AI Coach / Chatbot", "Duplicate send",
           "1. Type a message.\n2. Double-click Send.\n3. Check one logical send / safe dedupe.",
           "1. Draft ready.\n2. Double send.\n3. No duplicate spam replies beyond product rules.",
           "Duplicate send is safe.",
           priority="P2", severity="Minor", test_type="Negative", account="SUFFICIENT_CREDIT_01"),
        tc("TC-AI-008", "AI Coach / Chatbot", "Refresh mid-chat",
           "1. Exchange 2 messages.\n2. Refresh.\n3. Check history restore if product keeps history.",
           "1. History exists.\n2. Refresh.\n3. History restored or clear new-thread — no crash.",
           "Refresh during chat is safe.",
           priority="P1", severity="Major", test_type="Persistence", account="SUFFICIENT_CREDIT_01"),
    ]


def prep_lab_cases() -> list[dict]:
    return [
        tc("TC-PREP-001", "Prep Lab", "Hub loads",
           f"1. Open {B}/app/prep.\n2. Open each tool card (STAR, Project, Rephraser, Coding hints, System design).",
           "1. Hub loads.\n2. Each tool opens or shows gate — classify honestly.",
           "Prep Lab tools are reachable.",
           priority="P1", severity="Major", account="PRO_USER_01"),
        tc("TC-PREP-002", "Prep Lab", "STAR Builder — does not invent facts",
           f"1. Open {B}/app/prep/star-builder.\n"
           "2. Enter only: Situation='Led a 2-person bugfix for login timeout'. Leave other fields minimal.\n"
           "3. Generate STAR.\n4. Verify output does not invent employers, metrics, or tech not supplied.",
           "1. Form opens.\n2. Sparse input entered.\n3. Output generated or error.\n4. No fabricated facts beyond user input (flag hallucinations).",
           "STAR AI does not invent unsourced facts.",
           priority="P0", severity="Critical", account="SUFFICIENT_CREDIT_01", sub="STAR"),
        tc("TC-PREP-003", "Prep Lab", "Rephraser valid input",
           f"1. Open {B}/app/prep/rephraser.\n2. Paste a short answer.\n3. Rephrase.\n4. Refresh and check history if any.",
           "1. Opens.\n2. Input accepted.\n3. Improved text or clear error.\n4. Persistence per product.",
           "Rephraser returns improved text or honest failure.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Rephraser"),
        tc("TC-PREP-004", "Prep Lab", "Project Builder",
           f"1. Open project builder.\n2. Fill required fields.\n3. Generate.\n4. Save if available; reopen.",
           "1. Opens.\n2. Validation works.\n3. Output/error.\n4. Persists if save offered.",
           "Project Builder completes a saveable flow.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="Project"),
        tc("TC-PREP-005", "Prep Lab", "System design tool",
           f"1. Open system design.\n2. Submit a prompt (e.g. URL shortener).\n3. Observe diagram/text output.",
           "1. Opens.\n2. Prompt sent.\n3. Useful output or clear failure — not infinite load.",
           "System design tool produces output or honest failure.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01", sub="System Design"),
        tc("TC-PREP-006", "Prep Lab", "Coding hints",
           f"1. Open coding hints (or note feature flag).\n2. Ask for a hint on a simple problem.\n3. Confirm hint ≠ full spoil if product promises partial hints.",
           "1. Available or flagged.\n2. Hint returned/error.\n3. Behavior matches UI promise.",
           "Coding hints work when enabled.",
           priority="P2", severity="Minor", account="SUFFICIENT_CREDIT_01", sub="Coding Hints"),
        tc("TC-PREP-007", "Prep Lab", "AI failure fallback",
           "1. During AI-down window run STAR generate.\n2. Observe fallback/error.\n3. Confirm credits messaging truthful.",
           "1. Down.\n2. Fallback/error.\n3. No false credit error.",
           "Prep tools fail gracefully when AI is down.",
           priority="P0", severity="Critical", test_type="Negative", account="SUFFICIENT_CREDIT_01"),
        tc("TC-PREP-008", "Prep Lab", "Empty / very long input boundaries",
           "1. Submit empty required STAR fields.\n2. Paste a very long paragraph (10k+ chars if field allows).\n3. Try special chars/Unicode.",
           "1. Validation blocks empty.\n2. Long text handled or limited with message.\n3. Unicode accepted or clear rejection.",
           "Prep inputs handle empty/long/Unicode safely.",
           priority="P2", severity="Minor", test_type="Boundary", account="PRO_USER_01"),
    ]


def documents_cases() -> list[dict]:
    return [
        tc("TC-DOC-001", "Documents", "Upload supported PDF resume",
           f"1. Open {B}/app/documents.\n2. Upload approved sample PDF resume.\n3. Wait for processing status.\n4. Refresh; reopen.",
           "1. Page loads.\n2. Upload accepted.\n3. Status progresses to ready/error clearly.\n4. Persists after refresh.",
           "Supported PDF upload processes and persists.",
           priority="P0", severity="Critical", test_type="Persistence", account="PRO_USER_01",
           data="Approved QA sample resume PDF"),
        tc("TC-DOC-002", "Documents", "Upload DOCX / TXT",
           "1. Upload sample DOCX.\n2. Upload sample TXT.\n3. Observe each status.",
           "1. DOCX accepted or clear unsupported.\n2. TXT accepted or clear unsupported.\n3. Honest per-format behavior.",
           "DOCX/TXT handling matches supported-format messaging.",
           priority="P1", severity="Major", account="PRO_USER_01"),
        tc("TC-DOC-003", "Documents", "Unsupported format",
           "1. Upload .exe or random .xyz file.\n2. Observe rejection.",
           "1. File chosen.\n2. Clear unsupported error; file not listed as processed successfully.",
           "Unsupported formats are rejected safely.",
           priority="P1", severity="Major", test_type="Negative", account="PRO_USER_01"),
        tc("TC-DOC-004", "Documents", "Empty file",
           "1. Upload 0-byte file.\n2. Observe error.",
           "1. Upload attempted.\n2. Rejected with clear message.",
           "Empty files rejected.",
           priority="P2", severity="Minor", test_type="Boundary", account="PRO_USER_01"),
        tc("TC-DOC-005", "Documents", "Corrupt / oversized file",
           "1. Upload corrupt PDF fixture.\n2. Upload oversized file above limit.\n3. Observe messages.",
           "1. Corrupt fails clearly.\n2. Oversized blocked with size message.\n3. App remains stable.",
           "Corrupt and oversized uploads fail gracefully.",
           priority="P1", severity="Major", test_type="Negative", account="PRO_USER_01"),
        tc("TC-DOC-006", "Documents", "Duplicate upload",
           "1. Upload same resume twice.\n2. Observe naming/versioning/duplicate handling.",
           "1. First stored.\n2. Second handled without crash (versioned, rejected, or both listed — document actual).",
           "Duplicate uploads are handled safely.",
           priority="P2", severity="Minor", account="PRO_USER_01"),
        tc("TC-DOC-007", "Documents", "Delete document",
           "1. Delete a test document.\n2. Refresh.\n3. Confirm gone.\n4. Ensure USER_B cannot see it.",
           "1. Deleted.\n2. Refresh.\n3. Absent.\n4. No cross-user visibility.",
           "Delete persists and respects ownership.",
           priority="P1", severity="Major", test_type="Persistence", account="PRO_USER_01"),
        tc("TC-DOC-008", "Documents", "Download ownership",
           "1. Download own document.\n2. As USER_B try direct download URL if visible.\n3. Confirm denied.",
           "1. Own download works.\n2. Cross-user attempt.\n3. Denied / not found.",
           "Downloads are owner-scoped.",
           priority="P0", severity="Critical", test_type="Security", account="USER_A_01"),
        tc("TC-DOC-009", "Documents", "Parsing failure / AI fallback visible",
           "1. Upload an unrelated/image-heavy PDF if OCR claimed.\n2. Observe parse result.\n3. On AI parse failure, look for fallback/error.",
           "1. Upload done.\n2. Parse status honest.\n3. Fallback or clear failure — not stuck Processing forever.",
           "Parse/OCR failures are visible and bounded in time.",
           priority="P1", severity="Major", test_type="Negative", account="PRO_USER_01"),
        tc("TC-DOC-010", "Documents", "Document library page",
           f"1. Open {B}/app/library.\n2. Verify list/filters.\n3. Open an item.",
           "1. Library loads.\n2. Controls work or empty.\n3. Item opens.",
           "Document library is usable.",
           priority="P2", severity="Minor", account="PRO_USER_01"),
    ]


def resume_jd_cases() -> list[dict]:
    return [
        tc("TC-RJ-001", "Resume / JD Parsing", "Resume detail view",
           "1. Open a processed resume detail.\n2. Verify extracted fields visible.\n3. Refresh.",
           "1. Detail opens.\n2. Fields shown or explicit parse-failed.\n3. Persists.",
           "Resume detail shows parse results persistently.",
           priority="P0", severity="Critical", account="PRO_USER_01"),
        tc("TC-RJ-002", "Resume / JD Parsing", "JD upload and detail",
           "1. Upload a JD PDF/TXT.\n2. Open JD detail.\n3. Confirm key skills/requirements shown or failure.",
           "1. Upload works.\n2. Detail opens.\n3. Content or honest failure.",
           "JD parsing surfaces requirements or fails clearly.",
           priority="P1", severity="Major", account="PRO_USER_01"),
        tc("TC-RJ-003", "Resume / JD Parsing", "Use resume in Practice Coach",
           "1. From Practice Coach setup, select uploaded resume if selector exists.\n2. Start session.\n3. Confirm context used or UI states selection.",
           "1. Resume selectable.\n2. Session starts.\n3. Selection reflected (or clear if not applied).",
           "Selected resume can be attached to Practice Coach setup.",
           priority="P1", severity="Major", account="SUFFICIENT_CREDIT_01"),
        tc("TC-RJ-004", "Resume / JD Parsing", "Unrelated document",
           "1. Upload a random non-resume PDF labeled as resume.\n2. Observe parse quality messaging.",
           "1. Upload accepted or warned.\n2. Low-quality/unrelated parse handled without fake perfect profile.",
           "Unrelated docs do not produce falsely confident profiles.",
           priority="P2", severity="Minor", test_type="Negative", account="PRO_USER_01"),
    ]
