"""Application inventory, roles, accounts, environment — black-box / user surface only."""
from __future__ import annotations

from .common import SITE

# Classification values for testers — inventory ships as PENDING so testers classify
# after real manual execution. Suggested notes help orientation only.
PENDING = "PENDING MANUAL CLASSIFICATION"

INVENTORY = [
    # area, feature, route, entry, role_access, suggested_note
    ("Public", "Landing page", "/", "Open site root", "Guest", "Marketing hero + CTAs"),
    ("Public", "Pricing", "/pricing", "Nav → Pricing", "Guest", "Plans & CTAs"),
    ("Public", "Gov Exams marketing", "/gov-exams", "Nav / CTA", "Guest", "Public marketing"),
    ("Public", "Help center", "/help", "Footer / Help", "Guest", "Articles list"),
    ("Public", "Help article", "/help/:slug", "Open article from Help", "Guest", "Article body"),
    ("Public", "Keyboard shortcuts", "/shortcuts", "Footer / Help link", "Guest", "Shortcuts page"),
    ("Public", "Blog list", "/blog", "Nav / footer", "Guest", "Posts list"),
    ("Public", "Blog post", "/blog/:slug", "Open post", "Guest", "Post body"),
    ("Public", "Terms of Service", "/terms", "Footer", "Guest", "Legal"),
    ("Public", "Privacy Policy", "/privacy", "Footer", "Guest", "Legal"),
    ("Public", "Shared debrief", "/share/:token", "Shared link", "Guest", "Token-gated share"),
    ("Public", "Certificate verification", "/verify-certificate/:certificateId", "Public verify URL", "Guest", "Certificate check"),
    ("Public", "About", "/about", "Footer → Company → About", "Guest", "Company overview"),
    ("Public", "Industries", "/industries", "Footer → Company → Industries", "Guest", "Industries served"),
    ("Public", "Contact Sales", "/contact-sales", "Footer → Company → Contact Sales", "Guest", "Sales contact"),
    ("Public", "Careers", "/careers", "Footer → Company → Careers", "Guest", "Careers surface"),
    ("Public", "Cookies", "/cookies", "Footer → Company → Cookies", "Guest", "Cookie / telemetry notice"),
    ("Public", "FAQ", "/faq", "Footer → Company → FAQ", "Guest", "Product FAQ — articles live in /help"),
    ("Public", "Features (landing)", "/#features", "Footer / nav → Features", "Guest", "Landing anchor — not a standalone route"),
    ("Auth", "Login", "/login", "Login CTA", "Guest", "Email/password + OAuth if shown"),
    ("Auth", "Signup", "/signup", "Sign up CTA", "Guest", "Registration"),
    ("Auth", "Verify email", "/verify-email", "After signup", "Unverified", "Verification gate"),
    ("Auth", "Forgot password", "/forgot-password", "Login → Forgot", "Guest", "Reset request"),
    ("Auth", "Reset password", "/reset-password", "Email link", "Guest", "Set new password"),
    ("Auth", "OAuth callback", "/auth/callback", "OAuth provider return", "Guest", "Only if OAuth configured"),
    ("Auth", "Logout", "Any authenticated page", "Profile / Settings logout", "User", "Session end"),
    ("Onboarding", "Onboarding wizard", "/onboarding", "First login after verify", "New user", "Multi-step setup"),
    ("Dashboard", "Home dashboard", "/app/dashboard", "Sidebar Dashboard", "User", "KPIs / shortcuts"),
    ("Dashboard", "Interview Day", "/app/interview-day", "Sidebar", "User", "Day view"),
    ("Dashboard", "Usage / credits dashboard", "/app/usage", "Sidebar Credits usage", "User", "Usage metrics"),
    ("Dashboard", "Referrals", "/app/referrals", "Sidebar", "User", "Referral codes"),
    ("Dashboard", "Notifications page", "/app/notifications", "Bell / sidebar", "User", "Notification list"),
    ("Practice Coach", "Live rehearsal setup", "/app/live", "Sidebar Practice Coach", "User", "Session setup"),
    ("Practice Coach", "Live overlay", "/app/live/overlay", "Start live session", "User", "Overlay UI"),
    ("Mock Interview", "Mock setup", "/app/mock", "Sidebar Mock Interview", "User", "Configure mock"),
    ("Mock Interview", "Mock warmup", "/app/mock/warmup", "Warmup flow", "User", "Pre-session"),
    ("Mock Interview", "Mock session", "/app/mock/session/:sessionId", "Start mock", "User", "Q&A lifecycle"),
    ("Government Exams", "Mock test hub", "/app/mock-test", "Sidebar Gov Exams", "User (India gate)", "Exam hub"),
    ("Government Exams", "Configure mock", "/app/mock-test/configure", "Configure CTA", "User", "Paper config"),
    ("Government Exams", "Exam detail", "/app/mock-test/exam/:examCode", "Select exam", "User", "Exam info"),
    ("Government Exams", "Generate paper", "/app/mock-test/generate", "Generate CTA", "User", "Generation UX"),
    ("Government Exams", "Test session runner", "/app/mock-test/session/:testId", "Start test", "User", "MCQ runner"),
    ("Government Exams", "Test results", "/app/mock-test/results/:testId", "After submit", "User", "Score/result"),
    ("Government Exams", "My questions", "/app/mock-test/my-questions", "Hub nav", "User", "Personal Qs"),
    ("Government Exams", "Upload questions", "/app/mock-test/upload", "Hub nav", "User", "Upload"),
    ("Government Exams", "Revision", "/app/mock-test/revision", "Hub nav", "User", "Revision"),
    ("Government Exams", "Gov analytics", "/app/mock-test/analytics", "Hub nav", "User", "Analytics"),
    ("Government Exams", "Exam papers", "/app/mock-test/papers/:examType", "Papers link", "User", "Paper list"),
    ("Assessments", "Assessment templates", "/app/assessments", "Sidebar Assessments", "User", "Templates"),
    ("Assessments", "Assessment session", "/app/assessments/session/:testId", "Start assessment", "User", "Runner"),
    ("Assessments", "Assessment results", "/app/assessments/results/:testId", "After submit", "User", "Results"),
    ("Prep Lab", "Prep hub", "/app/prep", "Sidebar Prep Lab", "User", "Tool hub"),
    ("Prep Lab", "STAR Builder", "/app/prep/star-builder", "Prep → STAR", "User", "STAR form + AI"),
    ("Prep Lab", "Project Builder", "/app/prep/project-builder", "Prep → Project", "User", "Project tool"),
    ("Prep Lab", "Rephraser", "/app/prep/rephraser", "Prep → Rephraser", "User", "Rewrite"),
    ("Prep Lab", "Coding hints", "/app/prep/coding-hints", "Prep → Coding hints", "User", "May be feature-flagged"),
    ("Prep Lab", "System design", "/app/prep/system-design", "Prep → System design", "User", "System design tool"),
    ("Sessions", "Session list", "/app/sessions", "Sidebar Sessions", "User", "History list"),
    ("Sessions", "Session detail", "/app/sessions/:id", "Open session", "User", "Detail / transcript"),
    ("Documents", "Documents list", "/app/documents", "Sidebar Documents", "User", "Upload/list"),
    ("Documents", "Resume detail", "/app/documents/resume/:id", "Open resume", "User", "Parsed resume"),
    ("Documents", "JD detail", "/app/documents/jd/:id", "Open JD", "User", "Parsed JD"),
    ("Documents", "Document library", "/app/library", "Sidebar Document library", "User", "Library"),
    ("Answer Bank", "Answer bank list", "/app/answers", "Sidebar Answer bank", "User", "May be feature-flagged"),
    ("Answer Bank", "Answer detail", "/app/answers/:id", "Open answer", "User", "Edit/view"),
    ("Scheduler", "Interviews list", "/app/interviews", "Sidebar Interviews", "User", "May need calendar_sync flag"),
    ("Scheduler", "New interview", "/app/interviews/new", "Create interview", "User", "Form"),
    ("Scheduler", "Interview detail", "/app/interviews/:id", "Open interview", "User", "Detail"),
    ("Scheduler", "Edit interview", "/app/interviews/:id/edit", "Edit CTA", "User", "Edit form"),
    ("Company Research", "Companies list", "/app/companies", "Sidebar Company research", "User", "May be flagged"),
    ("Company Research", "Company profile", "/app/companies/:id", "Open company", "User", "Brief"),
    ("Reports", "Debriefs list", "/app/debriefs", "Sidebar Debrief", "User", "Debrief list"),
    ("Reports", "Debrief detail", "/app/debriefs/:id", "Open debrief", "User", "Scorecard/debrief"),
    ("Reports", "Scorecard", "/app/scorecard/:sessionId", "From session/debrief", "User", "Score view"),
    ("Analytics", "Analytics", "/app/analytics", "Sidebar Analytics", "User", "May be flagged"),
    ("Practice", "Practice plan", "/app/plan", "Sidebar Practice plan", "User", "Plan"),
    ("Practice", "Practice workspace", "/app/practice-workspace", "Sidebar", "User", "Workspace"),
    ("Practice", "Question bank", "/app/question-bank", "Sidebar", "User", "Questions"),
    ("Learning Hub", "Courses list", "/app/learn", "Sidebar Learning Hub", "User", "May be empty content"),
    ("Learning Hub", "Course detail", "/app/learn/:courseId", "Open course", "User", "Modules"),
    ("Learning Hub", "Lesson player", "/app/learn/:courseId/lesson/:lessonId", "Open lesson", "User", "Player"),
    ("Community", "Community / Q&A", "/app/community", "Sidebar Q&A", "User", "Posts"),
    ("Community", "Post detail", "/app/community/:postId", "Open post", "User", "Thread"),
    ("Coding Lab", "Coding lab", "/app/coding", "Sidebar Coding lab", "User", "May be flagged"),
    ("Coding Lab", "Coding assessment", "/app/coding/:questionId", "Open question", "User", "Editor/run"),
    ("Guide", "In-app guide", "/app/guide", "Guide link", "User", "Guide"),
    ("Guide", "Practice Coach guide", "/app/guide/practice-coach", "Guide link", "User", "Coach guide"),
    ("Retired", "Rooms / group practice", "/app/rooms", "Direct URL", "User", "Should redirect — Retired"),
    ("Settings", "Settings shell", "/app/settings", "Sidebar Settings", "User", "Tabs"),
    ("Settings", "Profile", "/app/settings/profile", "Settings → Profile", "User", "Profile form"),
    ("Settings", "Audio", "/app/settings/audio", "Settings → Audio", "User", "Mic/speakers"),
    ("Settings", "Practice Coach prefs", "/app/settings/practice-coach", "Settings → Practice Coach", "User", "Prefs"),
    ("Settings", "Models", "/app/settings/models", "Settings → Models", "User", "Model prefs / BYOK"),
    ("Settings", "Billing", "/app/settings/billing", "Settings → Billing", "User", "Plan & credits"),
    ("Settings", "Notifications prefs", "/app/settings/notifications", "Settings → Notifications", "User", "Prefs"),
    ("Settings", "Privacy", "/app/settings/privacy", "Settings → Privacy", "User", "Privacy"),
    ("Settings", "Security / MFA", "/app/settings/security", "Settings → Security", "User", "Security"),
    ("Settings", "Integrations", "/app/settings/integrations", "Settings → Integrations", "User", "Connect/disconnect"),
    ("Settings", "Appearance", "/app/settings/appearance", "Settings → Appearance", "User", "Theme"),
    ("Settings", "Data export", "/app/settings/data", "Settings → Data", "User", "Export"),
    ("Settings", "Danger zone / delete", "/app/settings/danger", "Settings → Danger", "User", "Delete account"),
    ("Settings", "Hotkeys", "/app/settings/hotkeys", "Settings → Hotkeys", "User", "Shortcuts"),
    ("Settings", "Polish", "/app/settings/polish", "Settings → Polish", "User", "Polish prefs"),
    ("Billing", "Upgrade / purchase credits", "/app/settings/billing + pricing CTAs", "Buy / Upgrade", "User", "Sandbox payment only"),
    ("Admin", "Admin dashboard", "/app/admin", "Admin nav (staff only)", "Admin", "Staff only"),
    ("Admin", "Users", "/app/admin/users", "Admin → Users", "Admin", "User mgmt"),
    ("Admin", "Analytics", "/app/admin/analytics", "Admin → Analytics", "Admin", "Admin analytics"),
    ("Admin", "Revenue", "/app/admin/revenue", "Admin → Revenue", "Admin", "Revenue"),
    ("Admin", "Model costs", "/app/admin/model-costs", "Admin → Model costs", "Admin", "Costs"),
    ("Admin", "AI Hub", "/app/admin/ai-hub", "Admin → AI Hub", "Admin", "AI config"),
    ("Admin", "Feature flags", "/app/admin/feature-flags", "Admin → Feature flags", "Admin", "Flags"),
    ("Admin", "Seed questions", "/app/admin/seed-questions", "Admin → Seed", "Admin", "Seed"),
    ("Admin", "Bulk upload", "/app/admin/bulk-upload", "Admin → Bulk upload", "Admin", "PDF/bulk"),
    ("Admin", "Live chat / support inbox", "/app/admin/live-chat", "Admin → Live chat", "Admin", "Support"),
    ("Admin", "Questions editor", "/app/admin/questions", "Admin → Questions", "Admin", "Editor"),
    ("Admin", "Audit log", "/app/admin/audit-log", "Admin → Audit", "Admin", "Audit"),
    ("Admin", "Diagnostics", "/app/admin/diagnostics", "Admin → Diagnostics", "Admin", "Diagnostics"),
    ("Admin", "Blog CMS", "/app/admin/blog", "Admin → Blog", "Admin", "CMS"),
    ("Admin", "Help articles CMS", "/app/admin/help-articles", "Admin → Help", "Admin", "CMS"),
    ("Admin", "Support", "/app/admin/support", "Admin → Support", "Admin", "Support"),
    ("Admin", "Promo codes", "/app/admin/promo-codes", "Admin → Promo", "Admin", "Promos"),
    ("Admin", "Billing settings", "/app/admin/billing-settings", "Admin → Billing settings", "Admin", "Billing cfg"),
    ("Admin", "Gov sources", "/app/admin/gov/sources", "Admin → Gov sources", "Admin", "Sources"),
    ("Admin", "Gov PDF ingest", "/app/admin/gov/ingest", "Admin → Gov ingest", "Admin", "Ingest"),
    ("Admin", "Exam registry", "/app/admin/gov/exams", "Admin → Exam registry", "Admin", "Registry"),
    ("Admin", "Question review", "/app/admin/gov/question-review", "Admin → Q review", "Admin", "Review"),
    ("Admin", "Paper review", "/app/admin/gov/paper-review", "Admin → Paper review", "Admin", "Review"),
    ("Admin", "Translations review", "/app/admin/gov/translations", "Admin → Translations", "Admin", "Review"),
    ("Admin", "Community moderation", "/app/admin/community", "Admin → Community", "Admin", "Moderation"),
    ("Admin", "Learning admin", "/app/admin/learning", "Admin → Learning", "Admin", "Courses admin"),
    ("Security", "Direct admin access by non-admin", "/app/admin", "Paste URL as Free user", "Free user", "Must block/redirect"),
    ("Security", "Logged-out protected route", "/app/dashboard", "Paste URL logged out", "Guest", "Must redirect login"),
]

ROLES = [
    ("Guest", "Unauthenticated visitor", "Public pages, login/signup CTAs", "No app modules, no admin", "Public marketing & auth entry"),
    ("Unverified User", "Signed up, email not verified", "Verify-email screen", "Cannot enter /app until verified", "Email verification flow"),
    ("New / Onboarding User", "Verified, onboarding incomplete", "Onboarding wizard", "App shell blocked until complete", "Onboarding"),
    ("Free User", "plan free", "Core free features per plan gates", "Paid/pro-gated actions blocked or upgrade prompt", "Free plan QA"),
    ("Pro User", "plan pro", "Pro features + higher credits", "Enterprise-only if any", "Pro plan QA"),
    ("Max / Enterprise User", "plan enterprise / max", "Highest plan features & credits", "Admin still denied unless staff", "Max plan QA"),
    ("Zero Credit User", "Authenticated with 0 credits", "Browse UI; AI actions blocked gracefully", "Credit-consuming actions", "Credit exhaustion"),
    ("Low Credit User", "Credits near threshold", "Low-credit banners / warnings", "Actions that exceed balance", "Boundary credits"),
    ("Admin", "Staff role (admin)", "Full Admin portal + user app", "N/A", "Admin portal QA"),
    ("Moderator", "moderator role if assigned", "If UI exposes moderation tools", "Full admin may be denied", "Only if role is provisioned"),
    ("Banned / Suspended User", "Account banned", "Login rejected or safe ban message", "All app access", "Ban enforcement"),
    ("Expired Session User", "Valid account, stale session", "Re-auth / redirect to login", "Protected actions", "Session expiry"),
]

ACCOUNTS = [
    ("GUEST", "Guest", "none", "Public browsing", "N/A — no login", "Closed Beta / QA Target", "No credentials", "Public pages only"),
    ("NEW_USER_01", "Newly Registered", "free", "Signup + verify + onboarding", "Credential store (.env.qa.local / secure vault — never paste passwords into Excel)", "Closed Beta / QA Target", "Disposable inbox", "Create account; complete onboarding"),
    ("UNVERIFIED_01", "Unverified", "free", "Email verification gate", "Credential store", "Closed Beta / QA Target", "Do not verify until test done", "Stuck on verify-email"),
    ("FREE_USER_01", "Free User", "free", "Free-plan feature testing", "Credential store", "Closed Beta / QA Target", "Standard free credits", "Free entitlements"),
    ("FREE_USER_02", "Free User (empty history)", "free", "Empty-state testing", "Credential store", "Closed Beta / QA Target", "No sessions/docs", "Empty states"),
    ("PRO_USER_01", "Pro User", "pro", "Pro features & credits", "Credential store", "Closed Beta / QA Target", "Sufficient credits", "Pro entitlements"),
    ("MAX_USER_01", "Max/Enterprise User", "enterprise", "Max plan features", "Credential store", "Closed Beta / QA Target", "High credits", "Max entitlements"),
    ("ADMIN_USER_01", "Admin", "enterprise", "Admin portal testing", "Credential store", "Closed Beta / QA Target", "Staff only", "Admin + user app"),
    ("MOD_USER_01", "Moderator (if available)", "pro", "Moderation UI if exposed", "Credential store", "Closed Beta / QA Target", "Skip if role not provisioned", "Moderation only"),
    ("BANNED_USER_01", "Banned", "free", "Ban enforcement", "Credential store", "Closed Beta / QA Target", "Must remain banned", "Login denied"),
    ("ZERO_CREDIT_01", "Zero credits", "free/pro", "Credit exhaustion UX", "Credential store", "Closed Beta / QA Target", "Balance must stay 0", "AI actions blocked gracefully"),
    ("LOW_CREDIT_01", "Low credits", "pro", "Low-credit banners & boundary", "qa.lowcredit@ (.env.qa.local)", "Closed Beta / QA Target", "5 credits — npm run qa:reset-fixtures", "Warning + block when insufficient"),
    ("EXACT_CREDIT_01", "Exact credits", "pro", "Exact-cost boundary (gov paper = 3)", "qa.exactcredit@ (.env.qa.local)", "Closed Beta / QA Target", "3 credits — npm run qa:reset-fixtures", "Exact-spend then block"),
    ("MFA_USER_01", "MFA enrolled", "pro", "TOTP challenge (TC-AUTH-015)", "qa.mfa@ (.env.qa.local)", "Closed Beta / QA Target", "npm run qa:seed-mfa", "Password + OTP required"),
    ("SUFFICIENT_CREDIT_01", "Sufficient credits", "pro", "Happy-path AI/credit consume", "Credential store", "Closed Beta / QA Target", "Do not drain completely", "Successful AI flows"),
    ("EXPIRED_SESSION_01", "Any valid user", "any", "Session expiry / idle timeout", "Reuse FREE/PRO", "Closed Beta / QA Target", "Expire session per QA playbook", "Re-auth required"),
    ("HISTORY_USER_01", "User with completed history", "pro", "Sessions/reports/compare", "qa.history@clarify.ai.test — npm run qa:seed-accounts && npm run qa:seed-compare", "Closed Beta / QA Target", "Pre-seeded via qa:seed-compare (2 scored + 1 unscored)", "History present"),
    ("NO_HISTORY_01", "User with no history", "free", "Empty sessions/analytics", "Same as FREE_USER_02", "Closed Beta / QA Target", "No prior sessions", "Empty states"),
    ("USER_A_01", "User A (isolation)", "pro", "Cross-user resource isolation", "Credential store", "Closed Beta / QA Target", "Pair with USER_B", "Own data only"),
    ("USER_B_01", "User B (isolation)", "pro", "Cross-user resource isolation", "Credential store", "Closed Beta / QA Target", "Pair with USER_A", "Own data only"),
]

ENV_FIELDS = [
    ("Web application URL", SITE),
    ("Admin URL", f"{SITE}/app/admin"),
    ("Local URL (optional)", "http://localhost:5173"),
    ("Test environment name", "Closed Beta / QA Target"),
    ("Browser (primary)", "Chrome (latest stable)"),
    ("Browser version", "Record at execution time"),
    ("Desktop resolution", "1920 × 1080 (also 1440 × 900, 1366 × 768)"),
    ("Mobile resolution", "360 × 800, 375 × 812, 414 × 896"),
    ("Tablet resolution", "768 × 1024"),
    ("Supported browsers", "Chrome, Edge, Firefox, Safari (where available)"),
    ("Required extensions", "None required. Ad blockers may interfere — disable for QA."),
    ("Required permissions", "Microphone, notifications (optional), clipboard as prompted; system/tab audio where testing Practice Coach"),
    ("Test email system", "Disposable / QA inbox provided by QA lead (do not use personal email)"),
    ("Payment sandbox", "Razorpay/Stripe TEST mode only — never live cards unless explicitly approved"),
    ("Stripe test card (sandbox)", "4242 4242 4242 4242 — any future expiry, any CVC (test mode)"),
    ("File upload test folder", "Use approved QA fixtures folder supplied by QA lead (PDF/DOCX/TXT/corrupt/oversized)"),
    ("Supported languages", "English (primary); exam languages as shown in Gov Exam UI"),
    ("Timezone", "Asia/Kolkata (IST) unless otherwise noted"),
    ("Test date", "Fill at execution"),
    ("Tester name", "Fill at execution"),
    ("Credential location", "Secure vault / .env.qa.local (gitignored) — NEVER paste passwords into this workbook"),
    ("DevTools policy", "Network + Console inspection permitted for evidence; do not modify requests to bypass auth"),
    ("Secrets policy", "Do not capture passwords, tokens, API keys, or full payment credentials in screenshots"),
]

BASE = SITE
