"""31 Aug 2026 retest wave + seeded defects for the assigned workbook."""
from __future__ import annotations

RETEST_WAVE: list[dict] = [
    # Anushka — Gov generate / runner / admin gov
    {
        "Test Case ID": "TC-GOV-007",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail / Blocked (poll + charge-before-paper)",
        "Fix claimed by eng": "JOB_POLL backoff; reserve credits until paper exists",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-PY / BLK-MIG until live paper exists",
        "Notes": "Full Mock generate. If 404/timeout mark Blocked not Fail.",
    },
    {
        "Test Case ID": "TC-GOV-008",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail / Blocked",
        "Fix claimed by eng": "Custom Practice via unified factory; count not Full Mock clamp",
        "Live proof required?": "Yes — P0 release gate",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-PY / BLK-MIG",
        "Notes": "Must produce a completed Custom Practice paper for GO.",
    },
    {
        "Test Case ID": "TC-GOV-010",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail (refresh trap / bootstrap)",
        "Fix claimed by eng": "Gov browse during recovery; truthful restore after refresh",
        "Live proof required?": "Yes",
        "Runnable now?": "Yes (hub/search); generate path maybe Blocked",
        "Blocker": "BLK-EDGE if still Generating forever",
        "Notes": "DEF-013 / bootstrap: hub must not infinite-search.",
    },
    {
        "Test Case ID": "TC-GOV-011",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail (no Retry / false insufficient credits)",
        "Fix claimed by eng": "Retry UI; new idempotency only after terminal fail",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-PY",
        "Notes": "Retry must not claim insufficient credits if balance remains.",
    },
    {
        "Test Case ID": "TC-GOV-012",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Not proven live",
        "Fix claimed by eng": "AI fill Realistic/Custom only; Official fail-closed",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-PY / BLK-CFG (AI-down scenario needs QA-lead flag)",
        "Notes": "Official must never be AI-labeled.",
    },
    {
        "Test Case ID": "TC-GOV-015",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Blocked (no live paper)",
        "Fix claimed by eng": "Server started_at / expires_at via start-exam",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE (start-exam 404 until deploy)",
        "Notes": "Client must not forever-extend the clock.",
    },
    {
        "Test Case ID": "TC-GOV-016",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Blocked",
        "Fix claimed by eng": "Palette states restored from test_responses",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-PY",
        "Notes": "Unanswered / answered / marked / answered+marked.",
    },
    {
        "Test Case ID": "TC-GOV-017",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Blocked",
        "Fix claimed by eng": "Versioned autosave; stale skip; ATTEMPT_EXPIRED",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE (save-test-answer)",
        "Notes": "Navigate + refresh must restore or warn honestly.",
    },
    {
        "Test Case ID": "TC-GOV-018",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Blocked",
        "Fix claimed by eng": "submit-test duplicate replay; no silent rescore",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-PY",
        "Notes": "Partial submit warning + stable result.",
    },
    {
        "Test Case ID": "TC-GOV-019",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Blocked",
        "Fix claimed by eng": "Results persist on mock_tests + history routes",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-PY",
        "Notes": "Logout/login must still show owner result.",
    },
    {
        "Test Case ID": "TC-GOV-020",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail (charge before paper)",
        "Fix claimed by eng": "reserve → finalize on completed; release on fail/cancel",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-MIG / BLK-EDGE",
        "Notes": "Failed generate must not keep reserved credits.",
    },
    {
        "Test Case ID": "TC-GOV-024",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P1",
        "Previous result": "Fail (duplicate Generate)",
        "Fix claimed by eng": "Idempotency key; 409 replay no second reservation",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE / BLK-MIG",
        "Notes": "Double-click Generate = one job.",
    },
    {
        "Test Case ID": "TC-API-004",
        "Module": "API / Network Observation",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail (SESSION_ACTION 20/min on poll)",
        "Fix claimed by eng": "JOB_POLL preset + 2s→15s backoff",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE",
        "Notes": "Observe Network during Generate poll. Pair with TC-GOV-007.",
    },
    {
        "Test Case ID": "TC-API-005",
        "Module": "API / Network Observation",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail (429 drops in-flight job)",
        "Fix claimed by eng": "429/5xx stay in-flight; 8 transient retries",
        "Live proof required?": "Yes",
        "Runnable now?": "Blocked",
        "Blocker": "BLK-EDGE",
        "Notes": "Do not Fail a 429 that recovers.",
    },
    {
        "Test Case ID": "DEF-013 / TC-GOV-010",
        "Module": "Government Exams",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail (bootstrap trap / infinite Searching…)",
        "Fix claimed by eng": "Gov browse during onboarding recovery; search abort/latest-wins",
        "Live proof required?": "Partial — hub is user-visible today",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "DEF-001 related. Hub must not infinite spinner.",
    },
    {
        "Test Case ID": "TC-ADM-022",
        "Module": "Admin Portal",
        "Tester": "Anushka",
        "Priority": "P1",
        "Previous result": "Fail (topic Apply-only + dual empty)",
        "Fix claimed by eng": "Live debounce + one empty card",
        "Live proof required?": "No (admin UI)",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Question review: one empty state, Apply live.",
    },
    {
        "Test Case ID": "TC-MOD-SMOKE-GOV",
        "Module": "Module Smoke",
        "Tester": "Anushka",
        "Priority": "P0",
        "Previous result": "Fail — infinite search spinner on /app/mock-test",
        "Fix claimed by eng": "Search debounce/abort; profile recovery browse",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Re-run module smoke on Gov hub. Opening hub ≠ Pass.",
    },
    {
        "Test Case ID": "TC-PREP-COACH-CREDITS",
        "Module": "Practice Coach",
        "Tester": "Anushka",
        "Priority": "P1",
        "Previous result": "prep-tool 401/unknown looked like no credits",
        "Fix claimed by eng": "JWT via fetchEdge; credit-first; raw_prompt alias",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-EDGE if prep-tool 404",
        "Notes": "Coach/docs surface must not say insufficient credits on 401.",
    },
    # Sultana — credits, sessions, billing, prep
    {
        "Test Case ID": "TC-SES-002",
        "Module": "Sessions",
        "Tester": "Sultana",
        "Priority": "P0",
        "Previous result": "Fail (session detail 500)",
        "Fix claimed by eng": "get_owned_session_detail owner RPC; Not scored empty",
        "Live proof required?": "Yes if migration unapplied",
        "Runnable now?": "Yes",
        "Blocker": "BLK-MIG if 500 persists",
        "Notes": "Must show transcript/score OR honest empty — never 500.",
    },
    {
        "Test Case ID": "TC-CR-003",
        "Module": "Credits",
        "Tester": "Sultana",
        "Priority": "P0",
        "Previous result": "Fail (zero-credit 400 unknown tool)",
        "Fix claimed by eng": "402 before tool_id; raw_prompt alias",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "ZERO_CREDIT_01. Block must be credits, not unknown tool.",
    },
    {
        "Test Case ID": "TC-CR-004",
        "Module": "Credits",
        "Tester": "Sultana",
        "Priority": "P1",
        "Previous result": "Fail (past-due reused as low-credit)",
        "Fix claimed by eng": "Separate qa.lowcredit@ fixture",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CRED if qa.lowcredit@ missing",
        "Notes": "Use LOW_CREDIT_01 only — not past-due.",
    },
    {
        "Test Case ID": "TC-CR-005",
        "Module": "Credits",
        "Tester": "Sultana",
        "Priority": "P1",
        "Previous result": "Fail (wrong fixture)",
        "Fix claimed by eng": "qa.exactcredit@ exact-boundary",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CRED if qa.exactcredit@ missing",
        "Notes": "Use EXACT_CREDIT_01.",
    },
    {
        "Test Case ID": "TC-BILL-007",
        "Module": "Billing",
        "Tester": "Sultana",
        "Priority": "P1",
        "Previous result": "N/A / not run",
        "Fix claimed by eng": "BillingHistory refund filter from ledger",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CFG if no refund rows in sandbox",
        "Notes": "Honest empty refund list is Pass if product has no refunds.",
    },
    {
        "Test Case ID": "TC-PREP-003",
        "Module": "Prep Lab",
        "Tester": "Sultana",
        "Priority": "P1",
        "Previous result": "Fail (prep-tool 401/unknown)",
        "Fix claimed by eng": "JWT fetchEdge; credit-first",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-EDGE if function 404",
        "Notes": "Unknown/401 must not look like no credits.",
    },
    {
        "Test Case ID": "DOCX-30-001/002",
        "Module": "Credits",
        "Tester": "Sultana",
        "Priority": "P2",
        "Previous result": "Fail (Help catalog drift)",
        "Fix claimed by eng": "Help fallback from creditEconomics",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Help copy for free plan / extra credits matches product.",
    },
    # Venkat — auth, public, settings, scheduler
    {
        "Test Case ID": "TC-AUTH-008",
        "Module": "Authentication",
        "Tester": "Venkat",
        "Priority": "P0",
        "Previous result": "Fail (raw email_not_confirmed)",
        "Fix claimed by eng": "formatSupabaseAuthError on login + OAuth",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Human-readable verify-email copy, not raw error code.",
    },
    {
        "Test Case ID": "TC-AUTH-014",
        "Module": "Authentication",
        "Tester": "Venkat",
        "Priority": "P0",
        "Previous result": "Fail (broken Google CTA)",
        "Fix claimed by eng": "Hide CTA when isOAuthProviderEnabled is false",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CFG if Google enabled but 400",
        "Notes": "Visible dead Google button = Fail. Hidden = Pass.",
    },
    {
        "Test Case ID": "TC-AUTH-015",
        "Module": "Authentication",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (MFA paused)",
        "Fix claimed by eng": "MFA_ENFORCEMENT_PAUSED = false",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Security/MFA controls visible and consistent.",
    },
    {
        "Test Case ID": "TC-ONB-002",
        "Module": "Onboarding",
        "Tester": "Venkat",
        "Priority": "P0",
        "Previous result": "Fail (no fixture)",
        "Fix claimed by eng": "Seed qa.onboarding@",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CRED if NEW_USER_01 missing",
        "Notes": "Use NEW_USER_01 / qa.onboarding@.",
    },
    {
        "Test Case ID": "TC-ONB-004",
        "Module": "Onboarding",
        "Tester": "Venkat",
        "Priority": "P0",
        "Previous result": "Fail (popstate / step lost)",
        "Fix claimed by eng": "Persist onboarding_step on Next/Back",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Browser Back must restore step.",
    },
    {
        "Test Case ID": "TC-ONB-005",
        "Module": "Onboarding",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail",
        "Fix claimed by eng": "onboarding_step persist",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Refresh mid-wizard restores step.",
    },
    {
        "Test Case ID": "TC-ONB-006",
        "Module": "Onboarding",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail",
        "Fix claimed by eng": "onboarding_step persist",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Next/Back do not skip required fields.",
    },
    {
        "Test Case ID": "TC-ONB-007",
        "Module": "Onboarding",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail",
        "Fix claimed by eng": "onboarding_step persist",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Complete onboarding lands in app.",
    },
    {
        "Test Case ID": "TC-AUTH-010 / D-012",
        "Module": "Authentication",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (reset width + inbox copy)",
        "Fix claimed by eng": "AuthShell max-w-md; spam/wait copy",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Reset form readable; copy mentions spam/wait.",
    },
    {
        "Test Case ID": "TC-SET-015",
        "Module": "Settings",
        "Tester": "Venkat",
        "Priority": "P0",
        "Previous result": "Fail (delete 429 on retry)",
        "Fix claimed by eng": "Skip rate limit when existingOp exists",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "DISPOSABLE_01 only. Re-seed after.",
    },
    {
        "Test Case ID": "TC-SCH-002",
        "Module": "Interview Scheduler",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (local Date parse)",
        "Fix claimed by eng": "IANA zonedWallTimeToUtc + Zod schema",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Edit/reschedule keeps intended IST wall time.",
    },
    {
        "Test Case ID": "TC-SCH-003",
        "Module": "Interview Scheduler",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (timezone)",
        "Fix claimed by eng": "IANA timezone validation",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Invalid date/timezone blocked with validation.",
    },
    {
        "Test Case ID": "TC-SCH-004",
        "Module": "Interview Scheduler",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (Calendar Connect 501)",
        "Fix claimed by eng": "Disabled Not configured when probe 501",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CFG if Calendar later enabled",
        "Notes": "Visible dead Connect = Fail. Not configured = Pass.",
    },
    {
        "Test Case ID": "TC-SCH-005",
        "Module": "Interview Scheduler",
        "Tester": "Venkat",
        "Priority": "P2",
        "Previous result": "Fail (reminder email silent)",
        "Fix claimed by eng": "Honest email not configured when Resend missing",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CFG",
        "Notes": "Do not Pass a silent missing email.",
    },
    {
        "Test Case ID": "TC-SET-010",
        "Module": "Settings",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail / Partial (integrations 501)",
        "Fix claimed by eng": "Integrations list + Not configured",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "BLK-CFG",
        "Notes": "List can load; dead Connect is Fail.",
    },
    {
        "Test Case ID": "TC-PUB-004",
        "Module": "Public Pages",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (FAB vs Login overlap)",
        "Fix claimed by eng": "Marketing FAB bottom-20 md:bottom-6",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Help/status FAB must not cover Login on mobile.",
    },
    {
        "Test Case ID": "TC-PUB-014",
        "Module": "Public Pages",
        "Tester": "Venkat",
        "Priority": "P2",
        "Previous result": "Fail (Contact Sales dead)",
        "Fix claimed by eng": "Existing mailto in MarketingLayout",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Contact Sales must be mailto or working form.",
    },
    {
        "Test Case ID": "D-013 / TC-RSP-006/007",
        "Module": "Responsive / Cross-Browser",
        "Tester": "Venkat",
        "Priority": "P1",
        "Previous result": "Fail (blank band / PublicErrorState)",
        "Fix claimed by eng": "Centered PublicErrorState + VerifyCertificate",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "360×800 and 1440. No blank band. Verify certificate error centered.",
    },
    {
        "Test Case ID": "DOCX-30-003",
        "Module": "Accessibility",
        "Tester": "Venkat",
        "Priority": "P2",
        "Previous result": "Fail (duplicate icons)",
        "Fix claimed by eng": "Overlay GripVertical; Dashboard Coins vs TopBar Zap unique aria-labels",
        "Live proof required?": "No",
        "Runnable now?": "Yes",
        "Blocker": "",
        "Notes": "Icons must not share the same accessible name.",
    },
]

DEFECT_SEEDS: list[dict] = [
    {
        "Defect ID": "DEF-001",
        "Title": "Infinite search spinner / profile timeout on /app/mock-test",
        "Module": "Government Exams",
        "Test Case ID": "TC-MOD-003 / TC-GOV-001",
        "Severity (P0-P4)": "P1",
        "Assigned Tester": "Anushka",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "PRO_USER_01",
        "Status": "Open",
        "Steps to Reproduce": "Login PRO_USER_01 → /app/mock-test → type search. Observe infinite Searching… and profile load_timed_out.",
        "Expected": "Search finishes; no infinite spinner.",
        "Actual": "Search stuck; console auth profile timeout.",
    },
    {
        "Defect ID": "DEF-002",
        "Title": "Missing DialogTitle on global search modal",
        "Module": "Accessibility",
        "Test Case ID": "TC-MOD-022",
        "Severity (P0-P4)": "P3",
        "Assigned Tester": "Venkat",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "PRO_USER_01",
        "Status": "Open",
        "Steps to Reproduce": "Open command/search palette. Watch console for DialogTitle / aria-describedby.",
        "Expected": "Modal accessible; no Radix DialogTitle errors.",
        "Actual": "Repeated DialogContent requires DialogTitle warnings.",
    },
    {
        "Defect ID": "DEF-003",
        "Title": "Razorpay risk-detection script blocked by CSP",
        "Module": "Billing",
        "Test Case ID": "TC-BILL-002",
        "Severity (P0-P4)": "P2",
        "Assigned Tester": "Sultana",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "PRO_USER_01",
        "Status": "Open",
        "Steps to Reproduce": "Settings → Billing → Buy Max. Watch console CSP on cdn.razorpay.com.",
        "Expected": "Checkout scripts load or payment uses an allowed provider without CSP errors that break pay.",
        "Actual": "script-src blocks razorpay-risk-detection bundle.",
    },
    {
        "Defect ID": "DEF-BILL-002",
        "Title": "Razorpay test card treated as unsupported international",
        "Module": "Billing",
        "Test Case ID": "TC-BILL-002",
        "Severity (P0-P4)": "P0",
        "Assigned Tester": "Sultana",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "PRO_USER_01",
        "Status": "Open",
        "Steps to Reproduce": "Sandbox checkout with documented test card.",
        "Expected": "Test payment completes or honest sandbox limitation.",
        "Actual": "international_transaction_not_allowed 400.",
    },
    {
        "Defect ID": "DEF-BILL-003",
        "Title": "Razorpay payments/validate/account 500",
        "Module": "Billing",
        "Test Case ID": "TC-BILL-003",
        "Severity (P0-P4)": "P0",
        "Assigned Tester": "Sultana",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "PRO_USER_01",
        "Status": "Open",
        "Steps to Reproduce": "Complete sandbox pay after checkout opens.",
        "Expected": "Credits granted after successful test pay.",
        "Actual": "validate/account HTTP 500; credit grant blocked.",
    },
    {
        "Defect ID": "DEF-INT-001",
        "Title": "Calendar sync 501 with live Connect CTA",
        "Module": "Integrations",
        "Test Case ID": "TC-INT-001 / TC-SCH-004",
        "Severity (P0-P4)": "P1",
        "Assigned Tester": "Venkat",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "PRO_USER_01",
        "Status": "Open",
        "Steps to Reproduce": "Settings → Integrations or Scheduler Connect Calendar.",
        "Expected": "Not configured (disabled) OR working OAuth.",
        "Actual": "501 Not Implemented on a clickable Connect.",
    },
    {
        "Defect ID": "DEF-PUB-013",
        "Title": "Continue with Google 400 validation_failed",
        "Module": "Authentication",
        "Test Case ID": "TC-PUB-013 / TC-AUTH-014",
        "Severity (P0-P4)": "P0",
        "Assigned Tester": "Venkat",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "GUEST",
        "Status": "Open",
        "Steps to Reproduce": "Landing/signup Continue with Google.",
        "Expected": "OAuth starts OR CTA hidden when provider disabled.",
        "Actual": "400 validation_failed; CTA still visible.",
    },
    {
        "Defect ID": "DEF-HELP-COPY",
        "Title": "Help FAQ vs footer status copy mismatch",
        "Module": "Public Pages",
        "Test Case ID": "TC-PUB-004 / DOCX-30-001",
        "Severity (P0-P4)": "P2",
        "Assigned Tester": "Venkat",
        "Reproducibility": "Always",
        "Environment": "Closed beta Chrome",
        "Account ID": "GUEST",
        "Status": "Open",
        "Steps to Reproduce": "Open /help. Compare free-plan / extra-credits FAQ vs footer status mailto.",
        "Expected": "Help answers match live product; status is honest mailto if no status page.",
        "Actual": "FAQ/footer copy inconsistent.",
    },
]
