/**
 * Client-side policy helper for paper generation vs approved inventory.
 * The server remains the authority; this only decides what the UI may offer.
 *
 * A short bank is not a dead end when the caller's plan includes AI generation: the
 * shortfall is generated to the blueprint and the paper is labelled AI-generated.
 */

export type InventoryMode = "bank_only" | "ai_assisted" | "blocked";

export type InventoryDecision = {
  canGenerateRequested: boolean;
  mode: InventoryMode;
  available: number;
  requested: number;
  /** How many questions AI would have to produce for a full paper. */
  aiQuestions: number;
  customPracticeMax: number;
  reason: "ok" | "empty" | "short" | "ai_fill";
};

export function decideQuestionInventory(input: {
  available: number;
  requested: number;
  minQuestions?: number;
  /** True when the signed-in plan may generate missing questions with AI. */
  aiFillAvailable?: boolean;
}): InventoryDecision {
  const available = Math.max(0, Math.floor(Number(input.available) || 0));
  const requested = Math.max(0, Math.floor(Number(input.requested) || 0));
  const minQuestions = Math.max(1, Math.floor(Number(input.minQuestions) || 5));
  const aiFillAvailable = input.aiFillAvailable === true;
  const customPracticeMax = available;

  // AI can cover any shortfall, including a completely empty bank.
  if (aiFillAvailable && requested > available) {
    return {
      canGenerateRequested: true,
      mode: "ai_assisted",
      available,
      requested,
      aiQuestions: requested - available,
      customPracticeMax,
      reason: "ai_fill",
    };
  }

  if (available < minQuestions) {
    return {
      canGenerateRequested: false,
      mode: "blocked",
      available,
      requested,
      aiQuestions: 0,
      customPracticeMax,
      reason: "empty",
    };
  }

  if (requested > available) {
    return {
      canGenerateRequested: false,
      mode: "blocked",
      available,
      requested,
      aiQuestions: 0,
      customPracticeMax,
      reason: "short",
    };
  }

  return {
    canGenerateRequested: true,
    mode: "bank_only",
    available,
    requested,
    aiQuestions: 0,
    customPracticeMax,
    reason: "ok",
  };
}

export function formatInventoryCoverage(available: number, requested: number): string {
  const avail = Math.max(0, Math.floor(Number(available) || 0));
  const req = Math.max(0, Math.floor(Number(requested) || 0));
  if (req <= 0) return `${avail} approved questions available`;
  return `${avail} / ${req} questions available`;
}

export function customPracticeSetLabel(maxQuestions: number): string {
  const n = Math.max(0, Math.floor(Number(maxQuestions) || 0));
  return `Generate Custom Practice Set — up to ${n} questions`;
}

/** Primary generate-button label, honest about how the paper will be built. */
export function generateButtonLabel(decision: InventoryDecision): string {
  if (decision.mode === "ai_assisted") {
    return `Generate Full AI Mock Paper — ${decision.requested} questions`;
  }
  return `Generate Full Mock Paper — ${decision.requested} questions`;
}

/** One-line explanation of the bank/AI split shown before generating. */
export function generationSourceSummary(decision: InventoryDecision): string {
  if (decision.mode !== "ai_assisted") {
    return `All ${decision.requested} questions come from the approved bank.`;
  }
  if (decision.available === 0) {
    return `All ${decision.aiQuestions} questions will be generated by AI to the official blueprint.`;
  }
  return (
    `${decision.available} from the approved bank, ` +
    `${decision.aiQuestions} generated by AI to the official blueprint.`
  );
}
