export const INTERVIEW_TYPES = [
  "Technical",
  "Behavioral",
  "HR",
  "Managerial",
  "System Design",
  "Coding",
  "Resume Based",
] as const;

export type InterviewType = (typeof INTERVIEW_TYPES)[number];

export type PracticeAnswer = {
  question: string;
  answer: string;
};

export type PracticeScores = {
  overall: number;
  technical: number;
  communication: number;
  answerQuality: number;
  areasToImprove: string[];
  rubricNote: string;
};

function clamp(n: number): number {
  return Math.max(0, Math.min(100, Math.round(n)));
}

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function hasStar(text: string): boolean {
  const t = text.toLowerCase();
  return (
    /\b(situation|when i|at my last)\b/.test(t) &&
    /\b(i |we )?(did|built|led|implemented|designed|fixed)\b/.test(t) &&
    /\b(result|impact|outcome|reduced|improved|increased)\b/.test(t)
  );
}

function isNonResponsive(text: string): boolean {
  const normalized = text.trim().toLowerCase().replace(/[^a-z0-9\s]/g, "");
  return normalized.length < 10 || /^(idk|i dont know|dont know|na|n a|none|no idea|skip)$/.test(normalized);
}

export function scorePracticeAnswers(
  answers: PracticeAnswer[],
  interviewType: InterviewType,
): PracticeScores {
  if (answers.length === 0) {
    return {
      overall: 0,
      technical: 0,
      communication: 0,
      answerQuality: 0,
      areasToImprove: ["Add at least one answer before ending the session."],
      rubricNote: "Practice rubric only — not an official interview score and not generated by a new AI provider.",
    };
  }

  const lengths = answers.map((a) => wordCount(a.answer));
  const nonResponsiveCount = answers.filter((a) => isNonResponsive(a.answer)).length;
  if (nonResponsiveCount === answers.length) {
    return {
      overall: 0,
      technical: 0,
      communication: 0,
      answerQuality: 0,
      areasToImprove: ["Replace non-responsive answers with specific examples, reasoning, and outcomes."],
      rubricNote: "Practice rubric only — non-responsive answers are not eligible for a positive score.",
    };
  }
  const avgWords = lengths.reduce((s, n) => s + n, 0) / lengths.length;
  const communication = clamp(avgWords >= 80 ? 85 : avgWords >= 40 ? 70 : avgWords >= 15 ? 55 : 35);

  const starHits = answers.filter((a) => hasStar(a.answer)).length;
  const starRatio = starHits / answers.length;
  const answerQuality = clamp(40 + starRatio * 50 + Math.min(10, avgWords / 12));

  const keywordHits = answers.filter((a) =>
    /\b(api|system|database|latency|scale|react|python|sql|trade-?off|metric)\b/i.test(a.answer),
  ).length;
  const technicalBase = interviewType === "Behavioral" || interviewType === "HR" ? 55 : 45;
  const technical = clamp(technicalBase + (keywordHits / answers.length) * 40);

  // A non-answer must never be offset by otherwise strong responses.
  const responsiveRatio = (answers.length - nonResponsiveCount) / answers.length;
  const overall = clamp(((technical + communication + answerQuality) / 3) * responsiveRatio);
  const areasToImprove: string[] = [];
  if (communication < 65) areasToImprove.push("Expand answers with a clearer beginning, middle, and end.");
  if (answerQuality < 65) areasToImprove.push("Use a Situation–Task–Action–Result structure with a concrete outcome.");
  if (technical < 65 && interviewType !== "HR") {
    areasToImprove.push("Name specific tools, constraints, and metrics.");
  }
  if (areasToImprove.length === 0) areasToImprove.push("Record another session and compare against this baseline.");

  return {
    overall,
    technical,
    communication,
    answerQuality,
    areasToImprove,
    rubricNote: "Practice rubric only — not an official interview score and not generated by a new AI provider.",
  };
}
