import {
  classifySessionAnswers,
  qualityClassLabel,
  scoreCapForQualityClass,
  type AnswerQualityClass,
} from "@/lib/scoring/answerQualityGate";

export const INTERVIEW_TYPES = [
  "Technical",
  "Behavioral",
  "HR",
  "Managerial",
  "System Design",
  "Coding",
  "Resume Based",
] as const;

export type InterviewType = (typeof INTERVIEW_TYPES)[number];

export type PracticeAnswer = {
  question: string;
  answer: string;
};

export type PracticeScores = {
  overall: number;
  technical: number;
  communication: number;
  answerQuality: number;
  areasToImprove: string[];
  rubricNote: string;
  qualityClasses?: AnswerQualityClass[];
};

function clamp(n: number): number {
  return Math.max(0, Math.min(100, Math.round(n)));
}

function wordCount(text: unknown): number {
  return String(text ?? "")
    .trim()
    .split(/\s+/)
    .filter(Boolean).length;
}

function hasStar(text: unknown): boolean {
  const t = String(text ?? "").toLowerCase();
  return (
    /\b(situation|when i|at my last)\b/.test(t) &&
    /\b(i |we )?(did|built|led|implemented|designed|fixed)\b/.test(t) &&
    /\b(result|impact|outcome|reduced|improved|increased)\b/.test(t)
  );
}

function relevanceHits(question: string, answer: string): number {
  const stop = new Set([
    "the", "and", "for", "that", "this", "with", "from", "your", "what", "when",
    "how", "why", "are", "was", "were", "have", "has", "had", "you", "can",
  ]);
  const qWords = question
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length > 3 && !stop.has(w));
  if (qWords.length === 0) return 0;
  const hay = answer.toLowerCase();
  return qWords.filter((w) => hay.includes(w)).length / qWords.length;
}

export function scorePracticeAnswers(
  answers: PracticeAnswer[],
  interviewType: InterviewType,
): PracticeScores {
  if (answers.length === 0) {
    return {
      overall: 0,
      technical: 0,
      communication: 0,
      answerQuality: 0,
      areasToImprove: ["Add at least one answer before ending the session."],
      rubricNote: "Practice rubric only — not an official interview score and not generated by a new AI provider.",
      qualityClasses: [],
    };
  }

  const qualityClasses = classifySessionAnswers(
    answers.map((a) => ({ question: a.question, answer: a.answer })),
  );
  const allBad = qualityClasses.every((c) => c !== "VALID");
  if (allBad) {
    const labels = [...new Set(qualityClasses.map(qualityClassLabel))];
    return {
      overall: 0,
      technical: 0,
      communication: 0,
      answerQuality: 0,
      areasToImprove: labels,
      rubricNote: "Practice rubric only — irrelevant or non-responsive answers are not eligible for a positive score.",
      qualityClasses,
    };
  }

  const lengths = answers.map((a) => wordCount(a.answer));
  const avgWords = lengths.reduce((s, n) => s + n, 0) / lengths.length;
  const validCount = qualityClasses.filter((c) => c === "VALID").length;

  const communication = clamp(
    avgWords >= 80 ? 75 : avgWords >= 40 ? 55 : avgWords >= 15 ? 35 : 15,
  );

  const starHits = answers.filter((a, i) => qualityClasses[i] === "VALID" && hasStar(a.answer)).length;
  const starRatio = validCount > 0 ? starHits / validCount : 0;
  // No artificial +40 baseline — quality comes from STAR + substance among valid answers.
  const answerQuality = clamp(starRatio * 70 + Math.min(25, avgWords / 8));

  const keywordHits = answers.filter((a, i) =>
    qualityClasses[i] === "VALID" &&
    /\b(api|system|database|latency|scale|react|python|sql|trade-?off|metric)\b/i.test(a.answer),
  ).length;
  const relevanceAvg =
    answers.reduce((s, a, i) => {
      if (qualityClasses[i] !== "VALID") return s;
      return s + relevanceHits(a.question, a.answer);
    }, 0) / Math.max(1, validCount);
  const technicalBase = interviewType === "Behavioral" || interviewType === "HR" ? 30 : 25;
  const technical = clamp(
    technicalBase + (keywordHits / Math.max(1, answers.length)) * 35 + relevanceAvg * 40,
  );

  let overall = clamp((technical + communication + answerQuality) / 3);
  // Cap overall by worst non-valid answer class when mixed.
  const caps = qualityClasses.map(scoreCapForQualityClass);
  const minCap = Math.min(...caps);
  if (minCap < 100) {
    const validShare = validCount / answers.length;
    overall = clamp(overall * validShare);
  }

  const areasToImprove: string[] = [];
  for (const cls of qualityClasses) {
    if (cls !== "VALID") areasToImprove.push(qualityClassLabel(cls));
  }
  if (communication < 65) areasToImprove.push("Expand answers with a clearer beginning, middle, and end.");
  if (answerQuality < 65) areasToImprove.push("Use a Situation–Task–Action–Result structure with a concrete outcome.");
  if (technical < 65 && interviewType !== "HR") {
    areasToImprove.push("Name specific tools, constraints, and metrics.");
  }
  if (areasToImprove.length === 0) areasToImprove.push("Record another session and compare against this baseline.");

  return {
    overall,
    technical,
    communication,
    answerQuality,
    areasToImprove: [...new Set(areasToImprove)].slice(0, 6),
    rubricNote: "Practice rubric only — not an official interview score and not generated by a new AI provider.",
    qualityClasses,
  };
}
