# -*- coding: utf-8 -*-
"""Clarify AI QA inventory — full feature + defect registers for workbook generation.
Statuses reflect post–launch-fixes pass (29 Jul 2026) where applicable.
"""

from datetime import date, timedelta

TODAY = date(2026, 7, 29)

# Feature tuple:
# id, module, name, description, FE, BE, DB, API, Edge,
# status, impl, qa, priority, risk, owner, qa_owner, est_h, act_h, comments
FEATURES = [
    # Auth & Onboarding
    ("FEAT-001", "Auth & Onboarding", "Email/password auth", "Signup/login with password", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Auth Lead", "Raj Balani", 2, 1.5, ""),
    ("FEAT-002", "Auth & Onboarding", "OAuth providers", "Google/GitHub/LinkedIn/Azure", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Critical", "Medium", "Auth Lead", "Raj Balani", 3, 2, "Provider enablement env-dependent"),
    ("FEAT-003", "Auth & Onboarding", "Email verification", "Verify email flow", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Auth Lead", "Raj Balani", 1.5, 1, ""),
    ("FEAT-004", "Auth & Onboarding", "Password reset", "Forgot/reset password", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Auth Lead", "Raj Balani", 1.5, 1, ""),
    ("FEAT-005", "Auth & Onboarding", "TOTP MFA", "Enable/verify TOTP + login challenge", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Ready", "High", "High", "Auth Lead", "Raj Balani", 3, 2.5, "Login AAL2 challenge wired"),
    ("FEAT-006", "Auth & Onboarding", "Account lockout", "Client lockout after failures", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Not Tested", "Medium", "Medium", "Auth Lead", "Raj Balani", 1, 0, "localStorage based"),
    ("FEAT-007", "Auth & Onboarding", "Onboarding wizard 5 steps", "Collect profile/experience/audio/resume", "Yes", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "In Testing", "Critical", "High", "Auth Lead", "Shreya Patil", 5, 3, "Mic+anxiety prefs now persist"),
    # Dashboard / Nav
    ("FEAT-008", "Dashboard", "Home dashboard KPIs", "Sessions, credits, upcoming", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Low", "Product", "Raj Balani", 2, 1.5, ""),
    ("FEAT-009", "Dashboard", "App routing guards", "ProtectedRoute + admin gates", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Platform", "Shreya Patil", 2, 1.5, ""),
    ("FEAT-010", "Dashboard", "In-app 404 NotFound", "/app/* splat catch-all", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Product", "Raj Balani", 0.5, 0.25, "P1-4 fixed"),
    ("FEAT-011", "Dashboard", "Mobile navigation", "Bottom nav destinations", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Ready", "Medium", "Medium", "Product", "Raj Balani", 2, 2, "Notifications/Guide/Profile/Admin in More"),
    ("FEAT-012", "Dashboard", "Command palette", "Ctrl/Cmd+K search", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Partial", "In Testing", "Low", "Low", "Product", "Raj Balani", 1, 0.5, "Nav only"),
    # Live Practice Coach
    ("FEAT-013", "Live Practice Coach", "Live Practice Coach session", "Core live rehearsal loop", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "Critical", "Live Coach", "Shreya Patil", 8, 6, ""),
    ("FEAT-014", "Live Practice Coach", "System/tab audio capture", "Chrome/Edge tab audio", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Live Coach", "Shreya Patil", 3, 2, "Chrome/Edge only"),
    ("FEAT-015", "Live Practice Coach", "Deepgram streaming STT", "nova-2-meeting stream", "Yes", "Yes", "N/A", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "Critical", "Live Coach", "Shreya Patil", 4, 3.5, "deepgram-token"),
    ("FEAT-016", "Live Practice Coach", "Speaker diarization", "Interviewer vs candidate", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "High", "Live Coach", "Shreya Patil", 3, 2, ""),
    ("FEAT-017", "Live Practice Coach", "Real-time AI hints", "generate-hint", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "Critical", "High", "Live Coach", "Shreya Patil", 3, 2, "Credits"),
    ("FEAT-018", "Live Practice Coach", "Streaming AI answers", "generate-answer SSE", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "Critical", "Critical", "Live Coach", "Shreya Patil", 5, 4, "Free limited; overlay Pro"),
    ("FEAT-019", "Live Practice Coach", "Screenshot/vision capture", "Coding problem OCR/vision", "Yes", "Yes", "N/A", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "High", "Live Coach", "Shreya Patil", 4, 2, "Pro gated"),
    ("FEAT-020", "Live Practice Coach", "Stealth mode", "UI labels only", "Yes", "N/A", "N/A", "N/A", "N/A", "In Progress", "Partial", "Failed", "Medium", "Medium", "Desktop", "Shreya Patil", 2, 0.5, "No capture evasion"),
    ("FEAT-021", "Live Practice Coach", "Panic mode", "Static coaching steps", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Live Coach", "Shreya Patil", 1, 0.5, ""),
    # Mock Interview
    ("FEAT-022", "Mock Interview", "Mock interview session", "Timed AI mock", "Yes", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "In Testing", "High", "High", "Live Coach", "Shreya Patil", 6, 3, "No TTS"),
    ("FEAT-023", "Mock Interview", "Mock warm-up", "Warm-up questions", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Partial", "Passed", "Medium", "Low", "Live Coach", "Shreya Patil", 1.5, 1, "WARMUP_MAX copy fixed"),
    ("FEAT-024", "Mock Interview", "Mock TTS playback", "Spoken questions", "No", "No", "N/A", "No", "No", "Not Started", "Not Built", "Not Tested", "High", "Medium", "Live Coach", "Shreya Patil", 8, 0, "Roadmap"),
    # Sessions & Debriefs
    ("FEAT-025", "Sessions & Debriefs", "Session history list", "Past sessions", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Low", "Sessions", "Shreya Patil", 2, 1.5, ""),
    ("FEAT-026", "Sessions & Debriefs", "Session detail scores", "Dimension breakdown", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Sessions", "Shreya Patil", 2, 1.5, "Null=Not scored P1-7"),
    ("FEAT-027", "Sessions & Debriefs", "AI Debrief", "generate-debrief", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Sessions", "Shreya Patil", 3, 2, ""),
    ("FEAT-028", "Sessions & Debriefs", "Debrief public share", "Share token link", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "Sessions", "Shreya Patil", 2, 1, ""),
    ("FEAT-029", "Sessions & Debriefs", "Scorecard", "Client Gemini scoring", "Yes", "Yes", "Yes", "Yes", "Partial", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Sessions", "Shreya Patil", 3, 1.5, ""),
    # Analytics
    ("FEAT-030", "Analytics & Usage", "Analytics dashboard", "Trends WPM fillers", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Analytics", "Raj Balani", 3, 2, "total_sessions fix P2-8"),
    ("FEAT-031", "Analytics & Usage", "Credits usage dashboard", "Ledger view", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Billing", "Raj Balani", 2, 1.5, ""),
    # Prep Lab
    ("FEAT-032", "Prep Lab", "Prep Lab hub", "Tool launcher", "Yes", "Yes", "N/A", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "High", "Low", "Prep", "Raj Balani", 1, 0.5, ""),
    ("FEAT-033", "Prep Lab", "STAR Builder", "STAR answer builder", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Prep", "Raj Balani", 3, 2, "Cost from economics"),
    ("FEAT-034", "Prep Lab", "Project Builder", "Project drafts", "Yes", "Partial", "N/A", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "Prep", "Raj Balani", 2, 1, "localStorage drafts"),
    ("FEAT-035", "Prep Lab", "Rephraser", "Rewrite answers", "Yes", "Yes", "N/A", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Prep", "Raj Balani", 2, 1.5, "Error state wired"),
    ("FEAT-036", "Prep Lab", "Coding Hints catalog", "DB coding hints", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "Prep", "Raj Balani", 2, 1, ""),
    ("FEAT-037", "Prep Lab", "System Design topics", "DB topics", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "Prep", "Raj Balani", 2, 1, ""),
    ("FEAT-038", "Prep Lab", "prep-tool AI suite", "12 AI prep tools", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Prep", "Raj Balani", 4, 2, ""),
    # Documents
    ("FEAT-039", "Documents & Resumes", "Resume upload + AI parse", "parse-resume + OCR", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Docs", "Shreya Patil", 5, 4, "Credits + free onboarding"),
    ("FEAT-040", "Documents & Resumes", "Job description parse", "Client Gemini JD", "Yes", "Partial", "Yes", "Partial", "N/A", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Docs", "Shreya Patil", 2, 1, ""),
    ("FEAT-041", "Documents & Resumes", "Resume vs JD gap analysis", "gap-analysis edge", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Ready", "High", "Medium", "Docs", "Shreya Patil", 4, 3, "JDDetail run + 402 handling"),
    ("FEAT-042", "Documents & Resumes", "Resume version history UI", "Version list UI", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Ready", "Medium", "Low", "Docs", "Shreya Patil", 4, 2, "Read-only list on ResumeDetail"),
    ("FEAT-043", "Documents & Resumes", "parse-document OCR", "Generic doc parse", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Docs", "Shreya Patil", 3, 1.5, "Charged; key in header"),
    # Answer Bank
    ("FEAT-044", "Answer Bank", "Answer Bank CRUD", "Save/edit STAR answers", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Prep", "Raj Balani", 2, 1.5, ""),
    ("FEAT-045", "Answer Bank", "Answer Bank AI generate", "prep-tool star_method", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "Prep", "Raj Balani", 3, 2, "Wired P3"),
    # Interviews
    ("FEAT-046", "Interviews & Calendar", "Manual interview CRUD", "Schedule interviews", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Scheduling", "Raj Balani", 3, 2, "next_round helpers"),
    ("FEAT-047", "Interviews & Calendar", "Interview email reminders", "schedule-interview email", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Blocked", "Medium", "Medium", "Scheduling", "Raj Balani", 2, 0.5, "Needs Resend key"),
    ("FEAT-048", "Interviews & Calendar", "Google Calendar connect", "OAuth connect", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Scheduling", "Raj Balani", 3, 1.5, ""),
    ("FEAT-049", "Interviews & Calendar", "Google Calendar sync", "sync-calendar", "Yes", "Yes", "Yes", "Yes", "Yes", "Blocked", "Partial", "Blocked", "High", "Medium", "Scheduling", "Raj Balani", 4, 1, "501 without secrets"),
    ("FEAT-050", "Interviews & Calendar", "Outlook Calendar", "Outlook sync", "No", "No", "N/A", "No", "No", "Not Started", "Not Built", "Not Tested", "Medium", "Low", "Scheduling", "Raj Balani", 8, 0, "Descope"),
    ("FEAT-051", "Interviews & Calendar", "Interview Day screen", "Day-of interview UI", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Scheduling", "Raj Balani", 2, 1.5, "Date bug fixed P1-1"),
    ("FEAT-052", "Company Research", "Company Research AI", "AI brief + cache", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Medium", "Medium", "Prep", "Raj Balani", 3, 2, "Pro gated"),
    # Notifications / Profile / Referrals
    ("FEAT-053", "Notifications & Profile", "In-app notifications", "Realtime notifications", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Growth", "Raj Balani", 2, 1.5, ""),
    ("FEAT-054", "Notifications & Profile", "Email notification prefs", "Prefs UI + send-email gate", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Ready", "Medium", "Medium", "Growth", "Raj Balani", 2, 1.5, "send-email honours prefs"),
    ("FEAT-055", "Notifications & Profile", "Push notifications", "Web push", "Partial", "No", "N/A", "No", "No", "Not Started", "Not Built", "Not Tested", "Low", "Low", "Growth", "Raj Balani", 6, 0, "Permission only"),
    ("FEAT-056", "Notifications & Profile", "Gamification XP/streak", "XP badges streaks", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Growth", "Raj Balani", 3, 2, ""),
    ("FEAT-057", "Notifications & Profile", "Profile page display", "Streak badges profile", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Medium", "Growth", "Raj Balani", 2, 1.5, "streak_days + badges fixed"),
    ("FEAT-058", "Referrals & Guide", "Referral program", "RPC credit grants", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Growth", "Raj Balani", 2, 1.5, ""),
    ("FEAT-059", "Referrals & Guide", "In-app Guide/Help", "Help articles", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Low", "Low", "Growth", "Shreya Patil", 1.5, 1, "Group Practice coming soon"),
    # Gov exams
    ("FEAT-060", "Gov Exam Mock Tests", "Mock test engine", "create/submit/score atomic", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "High", "GovExams", "Raj Balani", 6, 5, ""),
    ("FEAT-061", "Gov Exam Mock Tests", "Question bank content", "Seeded MCQs", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Ready", "Critical", "High", "GovExams", "Raj Balani", 20, 8, "~100+ MCQs via expand migration"),
    ("FEAT-062", "Gov Exam Mock Tests", "Adaptive question select", "select-test-questions", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "High", "Medium", "GovExams", "Raj Balani", 3, 2, ""),
    ("FEAT-063", "Gov Exam Mock Tests", "AI question gap-fill", "Pro + credits", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "GovExams", "Raj Balani", 3, 1.5, ""),
    ("FEAT-064", "Gov Exam Mock Tests", "Spaced repetition", "Revision schedule", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "GovExams", "Raj Balani", 3, 1, ""),
    ("FEAT-065", "Gov Exam Mock Tests", "Exam papers browser", "Past papers UI", "Yes", "Yes", "Yes", "Yes", "Partial", "In Progress", "Partial", "Failed", "Medium", "Medium", "GovExams", "Raj Balani", 3, 1, "Many empty"),
    ("FEAT-066", "Gov Exam Mock Tests", "PDF question import", "parse-question-pdf", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Blocked", "High", "Medium", "GovExams", "Raj Balani", 4, 1, "Quota/env"),
    ("FEAT-067", "Gov Exam Mock Tests", "Excel/CSV import", "bulk-import-questions", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "GovExams", "Raj Balani", 3, 2, ""),
    ("FEAT-068", "Gov Exam Mock Tests", "Collect exam papers", "collect-exam-papers", "Yes", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "Blocked", "Medium", "High", "GovExams", "Raj Balani", 4, 0.5, "Brittle hosts"),
    ("FEAT-069", "Gov Exam Mock Tests", "Python scraper service", "External scraper", "N/A", "Partial", "Yes", "N/A", "N/A", "Not Started", "Partial", "Not Tested", "Medium", "High", "GovExams", "Raj Balani", 16, 0, "Not deployed"),
    ("FEAT-070", "Gov Exam Mock Tests", "India region gate", "India-only UI/gate", "Yes", "Yes", "N/A", "N/A", "N/A", "Completed", "Partial", "Passed", "Low", "Low", "Platform", "Shreya Patil", 1, 0.5, "Claims removed; gate disabled"),
    # Settings
    ("FEAT-071", "Settings", "Profile/audio/appearance", "Core settings", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Low", "Platform", "Raj Balani", 2, 1.5, ""),
    ("FEAT-072", "Settings", "Security MFA settings", "Password + TOTP", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Critical", "High", "Platform", "Raj Balani", 2, 1, ""),
    ("FEAT-073", "Settings", "Data export / delete", "GDPR export delete", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "High", "Platform", "Shreya Patil", 3, 1.5, ""),
    ("FEAT-074", "Settings", "Hotkeys settings", "Overlay hotkeys UI", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Desktop", "Shreya Patil", 1.5, 1, ""),
    ("FEAT-075", "Settings", "Privacy toggles", "Privacy prefs + analytics opt-out", "Yes", "Partial", "Yes", "N/A", "N/A", "Completed", "Partial", "Ready", "Medium", "Medium", "Platform", "Raj Balani", 1.5, 1, "PostHog enforced; others honesty"),
    ("FEAT-076", "Settings", "Notification toggles", "Email/push prefs", "Yes", "Partial", "Yes", "N/A", "N/A", "In Progress", "Partial", "Failed", "Medium", "Medium", "Platform", "Raj Balani", 1.5, 0.5, "Saved never read"),
    ("FEAT-077", "Settings", "Retention polish", "Data retention", "Yes", "Partial", "Partial", "N/A", "N/A", "In Progress", "Partial", "Not Tested", "Low", "Low", "Platform", "Raj Balani", 2, 0, "Not enforced"),
    ("FEAT-078", "Settings", "Billing settings tab", "Plan credits portal", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Billing", "Raj Balani", 3, 2.5, "Ledger usage P2-6"),
    ("FEAT-079", "Settings", "Integrations calendar", "Google connect UI", "Yes", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "Blocked", "High", "Medium", "Scheduling", "Raj Balani", 2, 1, ""),
    # Admin
    ("FEAT-080", "Admin Portal", "Admin users management", "List/filter users", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Admin", "Raj Balani", 3, 2, ""),
    ("FEAT-081", "Admin Portal", "Admin analytics", "DAU/MAU", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Admin", "Raj Balani", 3, 1.5, ""),
    ("FEAT-082", "Admin Portal", "Admin revenue", "USD/INR MRR", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Critical", "High", "Admin", "Raj Balani", 4, 3, "P0-6 fixed"),
    ("FEAT-083", "Admin Portal", "Admin model costs", "Read-only AI_CREDIT_COSTS catalog", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Ready", "Medium", "Medium", "Admin", "Raj Balani", 3, 2, "Fake Save removed"),
    ("FEAT-084", "Admin Portal", "Admin feature flags", "DB flags UI", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Admin", "Raj Balani", 2, 1, ""),
    ("FEAT-085", "Admin Portal", "Admin question editor", "CRUD + filter", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Admin", "Raj Balani", 4, 3, "Filter fixed P1-5"),
    ("FEAT-086", "Admin Portal", "Admin bulk upload", "Excel import", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Admin", "Raj Balani", 3, 2, ""),
    ("FEAT-087", "Admin Portal", "Admin seed questions", "PDF AI extract", "Yes", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "Blocked", "High", "Medium", "Admin", "Raj Balani", 4, 1, "Gap-fill stub"),
    ("FEAT-088", "Admin Portal", "Admin live chat", "Support realtime", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "In Testing", "Medium", "Low", "Admin", "Raj Balani", 3, 2, ""),
    ("FEAT-089", "Admin Portal", "Admin support page", "Queue + Live Chat deep link", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Ready", "Low", "Low", "Admin", "Raj Balani", 1, 1, "Links to /app/admin/live-chat"),
    ("FEAT-090", "Admin Portal", "Admin audit log", "Read audit log", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Admin", "Raj Balani", 1.5, 1, ""),
    ("FEAT-091", "Admin Portal", "Admin QA checklist", "qaChecklist.json local-only", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Partial", "Ready", "Low", "Low", "Admin", "Shreya Patil", 2, 1, "Honesty: browser localStorage only"),
    ("FEAT-092", "Admin Portal", "Admin promo codes", "CRUD promos", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Admin", "Raj Balani", 2, 1.5, ""),
    ("FEAT-093", "Admin Portal", "Admin billing settings", "INR prices referral", "Yes", "Yes", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Admin", "Raj Balani", 2, 1.5, "auto_deduct UI removed"),
    # Marketing / Billing / Electron / Platform
    ("FEAT-094", "Marketing Site", "Landing + pricing pages", "Marketing funnel", "Yes", "Partial", "Yes", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Low", "Growth", "Shreya Patil", 3, 2, "Max $79"),
    ("FEAT-095", "Marketing Site", "Help/Blog CMS", "DB-backed content", "Yes", "Yes", "Yes", "Yes", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Growth", "Shreya Patil", 2, 1.5, ""),
    ("FEAT-096", "Billing & Credits", "Stripe checkout + webhooks", "Subscriptions packs", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "Critical", "Billing", "Raj Balani", 8, 6, "Enterprise price IDs"),
    ("FEAT-097", "Billing & Credits", "Razorpay INR checkout", "One-time orders", "Yes", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "Failed", "Critical", "High", "Billing", "Raj Balani", 6, 4, "No recurring"),
    ("FEAT-098", "Billing & Credits", "Credits ledger", "Server-authoritative", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "Critical", "Billing", "Shreya Patil", 4, 3, ""),
    ("FEAT-099", "Billing & Credits", "Plan gating enforcement", "requirePlan/capability", "Yes", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "Passed", "Critical", "Critical", "Billing", "Shreya Patil", 5, 4, "starter→pro remap"),
    ("FEAT-100", "Billing & Credits", "Money refunds clawback", "Stripe/Razorpay refunds", "N/A", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "Critical", "High", "Billing", "Shreya Patil", 4, 2, "P4-2"),
    ("FEAT-101", "Billing & Credits", "Razorpay Subscriptions", "Recurring INR", "No", "No", "N/A", "No", "No", "Not Started", "Not Built", "Not Tested", "High", "High", "Billing", "Raj Balani", 12, 0, "Roadmap"),
    ("FEAT-102", "Electron Desktop Overlay", "Electron overlay shell", "Always-on-top overlay", "Yes", "N/A", "N/A", "N/A", "N/A", "In Progress", "Partial", "In Testing", "Critical", "High", "Desktop", "Shreya Patil", 6, 3, ""),
    ("FEAT-103", "Electron Desktop Overlay", "Overlay hotkeys native", "Global shortcuts", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Desktop", "Shreya Patil", 2, 1.5, "No Ctrl+Shift+C dup"),
    ("FEAT-104", "Electron Desktop Overlay", "Window min size clamp", "360x320", "Yes", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "Medium", "Low", "Desktop", "Shreya Patil", 1, 0.5, "P1-9"),
    ("FEAT-105", "Electron Desktop Overlay", "Auto-update", "electron-updater", "Yes", "N/A", "N/A", "N/A", "N/A", "In Progress", "Partial", "Blocked", "High", "High", "Desktop", "Shreya Patil", 3, 1, "Unsigned"),
    ("FEAT-106", "Electron Desktop Overlay", "Code signing Windows", "EV/OV cert", "N/A", "N/A", "N/A", "N/A", "N/A", "Not Started", "Not Built", "Not Tested", "High", "High", "Desktop", "Shreya Patil", 8, 0, "P4-6 deferred"),
    ("FEAT-107", "Security & Platform", "RLS + edge shared libs", "Platform security", "N/A", "Yes", "Yes", "Yes", "Yes", "In Progress", "Partial", "In Testing", "Critical", "Critical", "Platform", "Shreya Patil", 8, 4, "Baseline recovery partial"),
    ("FEAT-108", "Security & Platform", "Distributed rate limits", "check_rate_limit", "N/A", "Yes", "Yes", "Yes", "Yes", "Completed", "Fully Implemented", "In Testing", "Critical", "High", "Platform", "Shreya Patil", 4, 2, "P4-1"),
    ("FEAT-109", "Security & Platform", "Edge Sentry reporting", "reportEdgeError", "N/A", "Yes", "N/A", "N/A", "Yes", "Completed", "Fully Implemented", "In Testing", "High", "Medium", "Platform", "Shreya Patil", 2, 1, "Optional DSN"),
    ("FEAT-110", "Security & Platform", "Session force sign-out", "Timeout at T=0", "Yes", "Yes", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Platform", "Raj Balani", 1.5, 1, "P4-7"),
    ("FEAT-111", "Security & Platform", "CI validate-env", "CI placeholders", "N/A", "N/A", "N/A", "N/A", "N/A", "Completed", "Fully Implemented", "Passed", "High", "Medium", "Platform", "Shreya Patil", 1, 0.5, "P1-8"),
    ("FEAT-112", "Security & Platform", "Unit/E2E coverage", "Vitest + Playwright", "Yes", "Yes", "N/A", "N/A", "N/A", "In Progress", "Partial", "Failed", "High", "High", "Platform", "Shreya Patil", 40, 8, "Low coverage; 794 todos"),
    ("FEAT-113", "Security & Platform", "Observability Sentry/PostHog", "Web client only", "Yes", "Partial", "N/A", "N/A", "Partial", "In Progress", "Partial", "In Testing", "High", "Medium", "Platform", "Shreya Patil", 3, 1.5, ""),
    ("FEAT-114", "Security & Platform", "Group practice WebRTC", "Rooms", "No", "No", "Partial", "No", "No", "Not Started", "Not Built", "Not Tested", "Low", "Low", "Platform", "Shreya Patil", 20, 0, "Descope"),
]

# Bug: id, title, description, module, feature, env, browser, device, os,
# severity, priority, status, assigned, reported_by, found, fixed, retest,
# build, sprint, root_cause, resolution, screenshot, video, comments
def _d(days):
    return TODAY - timedelta(days=days)

BUGS = [
    ("BUG-P0-01", "Max/enterprise Stripe price IDs missing", "PLANS.enterprise lacked stripePriceIdMonthly/Yearly so Max checkout failed",
     "Billing & Credits", "Stripe checkout + webhooks", "Staging", "Chrome", "Desktop", "Windows",
     "Critical", "Critical", "Closed", "Billing", "Raj Balani", _d(20), _d(2), _d(1), "1.0.0", "Sprint 26", "Config/Env",
     "Wired ENV.STRIPE_PRICE_ENTERPRISE_*", "", "", "P0-1 FIXED in hardening"),
    ("BUG-P0-02", "invoice.payment_failed wiped credits to 50", "Absolute credits overwrite destroyed purchased packs",
     "Billing & Credits", "Stripe checkout + webhooks", "Staging", "N/A", "Desktop", "Windows",
     "Critical", "Critical", "Closed", "Billing", "Shreya Patil", _d(20), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Stop writing credits on payment_failed", "", "", "P0-2 FIXED"),
    ("BUG-P0-03", "Server plan gating was a no-op", "starter rank 0 = free; requirePlan starter never blocked",
     "Billing & Credits", "Plan gating enforcement", "Staging", "Chrome", "Desktop", "Windows",
     "Critical", "Critical", "Closed", "Billing", "Shreya Patil", _d(20), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Remap starter→pro; rebuild CAPABILITY_MIN_RANK", "", "", "P0-3 FIXED"),
    ("BUG-P0-04", "AI parse endpoints free forever", "parse-resume/gap-analysis/parse-document never deducted",
     "Documents & Resumes", "Resume upload + AI parse", "Staging", "Chrome", "Desktop", "Windows",
     "Critical", "Critical", "Closed", "Docs", "Shreya Patil", _d(20), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "deductCreditsAtomic + free first onboarding", "", "", "P0-4 FIXED"),
    ("BUG-P0-05", ".env.production committed + release-new unignored", "Secrets/artifacts exposure risk",
     "Security & Platform", "CI validate-env", "Production", "N/A", "Desktop", "Windows",
     "Critical", "Critical", "Closed", "Platform", "Shreya Patil", _d(20), _d(2), "", "1.0.0", "Sprint 26", "Config/Env",
     "git rm --cached; gitignore; example file", "", "", "Rotate anon key still OPS"),
    ("BUG-P0-06", "Admin revenue treated credits as money", "monthlyRevenueByPlan summed credit_transactions",
     "Admin Portal", "Admin revenue", "Staging", "Chrome", "Desktop", "Windows",
     "Critical", "Critical", "Closed", "Admin", "Raj Balani", _d(20), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Subscriptions x prices + INR separate", "", "", "P0-6 FIXED"),
    ("BUG-P1-01", "Interview dates Invalid Date", "UI read scheduled_at; store has next_round.scheduled_at",
     "Interviews & Calendar", "Manual interview CRUD", "Staging", "Chrome", "Desktop", "Windows",
     "High", "High", "Closed", "Scheduling", "Raj Balani", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "roundHelpers next_round", "", "", "P1-1 FIXED"),
    ("BUG-P1-02", "Profile streak always 0", "Read streak_current; column is streak_days",
     "Notifications & Profile", "Profile page display", "Staging", "Chrome", "Desktop", "Windows",
     "High", "High", "Closed", "Growth", "Raj Balani", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Use streak_days", "", "", "P1-2 FIXED"),
    ("BUG-P1-03", "Profile badge count wrong", "Read profile.badges; badges in user_badges",
     "Notifications & Profile", "Gamification XP/streak", "Staging", "Chrome", "Desktop", "Windows",
     "High", "Medium", "Closed", "Growth", "Raj Balani", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "unlockedBadges from user_badges", "", "", "P1-3 FIXED"),
    ("BUG-P1-04", "Blank page on unknown /app route", "No splat NotFound under AppShell",
     "Dashboard", "In-app 404 NotFound", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "High", "Closed", "Product", "Raj Balani", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "path * → NotFound", "", "", "P1-4 FIXED"),
    ("BUG-P1-05", "Admin exam filter returns nothing", "JEE_MAIN vs JEE Main mismatch",
     "Admin Portal", "Admin question editor", "Staging", "Chrome", "Desktop", "Windows",
     "High", "High", "Closed", "Admin", "Raj Balani", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Display string map", "", "", "P1-5 FIXED"),
    ("BUG-P1-06", "Hotkey Ctrl+Shift+C collision", "MockSession vs overlay capture",
     "Mock Interview", "Mock interview session", "Electron Dev", "Electron", "Laptop", "Windows",
     "High", "High", "Closed", "Desktop", "Shreya Patil", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Removed local MockSession binding", "", "", "P1-6 FIXED"),
    ("BUG-P1-07", "Unscored dimensions show as 0", "Null rendered as confident zero",
     "Sessions & Debriefs", "Session detail scores", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Sessions", "Shreya Patil", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "UI Regression",
     "Not scored label", "", "", "P1-7 FIXED"),
    ("BUG-P1-08", "CI validate-env fails", "VITE_APP_ENV=test + ci-placeholder rejected",
     "Security & Platform", "CI validate-env", "CI", "N/A", "Desktop", "Linux",
     "High", "High", "Closed", "Platform", "Shreya Patil", _d(15), _d(2), "", "1.0.0", "Sprint 26", "Config/Env",
     "development + allowlist placeholders", "", "", "P1-8 FIXED"),
    ("BUG-P1-09", "Overlay min size forced 800x600", "Clamped above design 360x320",
     "Electron Desktop Overlay", "Window min size clamp", "Electron Dev", "Electron", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Desktop", "Shreya Patil", _d(15), _d(2), _d(1), "1.0.0", "Sprint 26", "Logic Bug",
     "Min 360x320", "", "", "P1-9 FIXED"),
    ("BUG-P1-10", "Electron release glob mismatch", "Uploads release/*.exe builds in release-new",
     "Electron Desktop Overlay", "Auto-update", "CI", "N/A", "Desktop", "Windows",
     "Medium", "High", "Closed", "Desktop", "Shreya Patil", _d(15), _d(2), "", "1.0.0", "Sprint 26", "Config/Env",
     "directories.output=release; gitignore release-new", "", "", "P1-10"),
    ("BUG-P2-01", "Warm-up copy said 2 ran 10", "Copy vs WARMUP_MAX mismatch",
     "Mock Interview", "Mock warm-up", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Medium", "Closed", "Live Coach", "Shreya Patil", _d(12), _d(2), _d(1), "1.0.0", "Sprint 26", "UI Regression",
     "Copy reads WARMUP_MAX", "", "", "P2-1 FIXED"),
    ("BUG-P2-02", "MockTestHub total questions wrong", "Counted user uploads as bank size",
     "Gov Exam Mock Tests", "Question bank content", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "GovExams", "Raj Balani", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Label My uploads", "", "", "P2-2 FIXED"),
    ("BUG-P2-03", "Predicted percentile misleading", "Formula not cohort rank",
     "Gov Exam Mock Tests", "Mock test engine", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "GovExams", "Raj Balani", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Design Gap",
     "Relabeled estimated band", "", "", "P2-3 FIXED"),
    ("BUG-P2-04", "Pricing showed Max as Custom", "Should show $79",
     "Marketing Site", "Landing + pricing pages", "Staging", "Chrome", "Desktop", "Windows",
     "High", "High", "Closed", "Growth", "Shreya Patil", _d(12), _d(2), _d(1), "1.0.0", "Sprint 26", "UI Regression",
     "Show $79", "", "", "P2-4 FIXED"),
    ("BUG-P2-05", "StarBuilder polish cost wrong", "Hardcoded cost vs economics",
     "Prep Lab", "STAR Builder", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Prep", "Raj Balani", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Use creditEconomics", "", "", "P2-5 FIXED"),
    ("BUG-P2-06", "SettingsBilling creditsUsed negative", "allowance - remaining after packs",
     "Settings", "Billing settings tab", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "High", "Closed", "Billing", "Raj Balani", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Usage from ledger", "", "", "P2-6 FIXED"),
    ("BUG-P2-07", "India-only advertised but disabled", "UI claims vs indiaRegion always true",
     "Gov Exam Mock Tests", "India region gate", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Platform", "Shreya Patil", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Design Gap",
     "Strip India-only claims", "", "", "P2-7 FIXED"),
    ("BUG-P2-08", "Analytics overwrote total_sessions", "Client page length overwrite",
     "Analytics & Usage", "Analytics dashboard", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Analytics", "Raj Balani", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Keep server total_sessions", "", "", "P2-8 FIXED"),
    ("BUG-P2-09", "Onboarding always saved default mic", "audio_input_device hardcoded",
     "Auth & Onboarding", "Onboarding wizard 5 steps", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Auth Lead", "Shreya Patil", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Persist selected device", "", "", "P2-9 FIXED"),
    ("BUG-P2-10", "Onboarding anxiety never saved", "Collected then discarded",
     "Auth & Onboarding", "Onboarding wizard 5 steps", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Medium", "Closed", "Auth Lead", "Shreya Patil", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Persist in JSON prefs", "", "", "P2-10 FIXED"),
    ("BUG-P2-11", "Sidebar collapse overwritten on resize", "Breakpoint overwrote preference",
     "Dashboard", "Home dashboard KPIs", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Closed", "Product", "Raj Balani", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Logic Bug",
     "Local transient collapse", "", "", "P2-11 FIXED"),
    ("BUG-P2-12", "Help still describes Group Practice", "Rooms redirect away",
     "Referrals & Guide", "In-app Guide/Help", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Closed", "Growth", "Shreya Patil", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Design Gap",
     "Coming soon copy", "", "", "P2-12 FIXED"),
    ("BUG-OPEN-01", "Razorpay plans do not auto-renew", "One-time Order only; UI now discloses one-time (Subscriptions API still missing)",
     "Billing & Credits", "Razorpay INR checkout", "Production", "Chrome", "Desktop", "Windows",
     "High", "Critical", "Open", "Billing", "Raj Balani", _d(25), "", "", "1.0.0", "Sprint 25", "Design Gap",
     "UI honesty shipped; recurring INR still roadmap", "", "", "Roadmap — recurring INR"),
    ("BUG-OPEN-02", "Gov exam bank was thin (~26 MCQs)", "Expanded via migration 20260729120000 (~80+ new MCQs)",
     "Gov Exam Mock Tests", "Question bank content", "Staging", "Chrome", "Desktop", "Windows",
     "High", "Critical", "Closed", "GovExams", "Raj Balani", _d(30), _d(1), "", "1.0.0", "Sprint 27", "Design Gap",
     "Apply expand_gov_exam_mcq_seeds migration", "", "", "FIXED launch pass — retest bank size"),
    ("BUG-OPEN-03", "Google Calendar sync returns 501", "Missing OAuth secrets in staging/prod",
     "Interviews & Calendar", "Google Calendar sync", "Staging", "Chrome", "Laptop", "macOS",
     "High", "High", "Blocked", "Scheduling", "Shreya Patil", _d(10), "", "", "1.0.0", "Sprint 26", "Config/Env",
     "Needs GOOGLE_CLIENT_ID/SECRET (+ refresh tokens) in Edge secrets", "", "", "Ops blocker — no fake fix"),
    ("BUG-OPEN-04", "Mock interview has no TTS", "Questions not spoken aloud",
     "Mock Interview", "Mock TTS playback", "Staging", "Chrome", "Desktop", "Windows",
     "High", "High", "Open", "Live Coach", "Shreya Patil", _d(28), "", "", "1.0.0", "Sprint 24", "Design Gap",
     "", "", "", "Roadmap / descope"),
    ("BUG-OPEN-05", "Gap analysis UI not fully wired", "JDDetail now runs gap-analysis + shows results/402",
     "Documents & Resumes", "Resume vs JD gap analysis", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "High", "Closed", "Docs", "Shreya Patil", _d(18), _d(1), "", "1.0.0", "Sprint 27", "Design Gap",
     "Retest JD gap panel with primary resume", "", "", "FIXED launch pass"),
    ("BUG-OPEN-06", "Resume version history UI missing", "Read-only version list on ResumeDetail",
     "Documents & Resumes", "Resume version history UI", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Docs", "Shreya Patil", _d(22), _d(1), "", "1.0.0", "Sprint 27", "Design Gap",
     "Confirm versions appear after re-parse", "", "", "FIXED launch pass"),
    ("BUG-OPEN-07", "Outlook Calendar not built", "Type only",
     "Interviews & Calendar", "Outlook Calendar", "N/A", "N/A", "Desktop", "Windows",
     "Medium", "Medium", "Won't Fix", "Scheduling", "Raj Balani", _d(40), "", "", "1.0.0", "Sprint 22", "Design Gap",
     "Descope until scheduled", "", "", ""),
    ("BUG-OPEN-08", "Email/push prefs never consumed", "send-email gates on prefs; UI honesty for push/digest",
     "Notifications & Profile", "Email notification prefs", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Growth", "Raj Balani", _d(20), _d(1), "", "1.0.0", "Sprint 27", "Logic Bug",
     "Toggle off debrief_ready and confirm skip", "", "", "FIXED launch pass"),
    ("BUG-OPEN-09", "Push notifications not implemented", "Permission prompt only",
     "Notifications & Profile", "Push notifications", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Open", "Growth", "Raj Balani", _d(35), "", "", "1.0.0", "Sprint 22", "Design Gap",
     "", "", "", "Missing / descope"),
    ("BUG-OPEN-10", "Mobile nav missing destinations", "Notifications, Guide, Profile, Admin (+ Usage/Interview Day) in More",
     "Dashboard", "Mobile navigation", "Staging", "Chrome", "Android Phone", "Android",
     "Medium", "Medium", "Closed", "Product", "Raj Balani", _d(14), _d(1), "", "1.0.0", "Sprint 28", "UI Regression",
     "Parity with sidebar footer destinations", "", "", "FIXED QA sync pass"),
    ("BUG-OPEN-11", "Stealth mode is cosmetic only", "No capture evasion",
     "Live Practice Coach", "Stealth mode", "Electron Dev", "Electron", "Desktop", "Windows",
     "Medium", "Medium", "Open", "Desktop", "Shreya Patil", _d(16), "", "", "1.0.0", "Sprint 25", "Design Gap",
     "", "", "", "Roadmap / descope"),
    ("BUG-OPEN-12", "Admin model costs save is stub", "Read-only AI_CREDIT_COSTS catalog; fake Save removed",
     "Admin Portal", "Admin model costs", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Admin", "Raj Balani", _d(18), _d(1), "", "1.0.0", "Sprint 27", "Logic Bug",
     "Confirm no Save; values match creditEconomics", "", "", "FIXED launch pass"),
    ("BUG-OPEN-13", "Admin support page read-only", "Deep-linked to Live Chat for replies",
     "Admin Portal", "Admin support page", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Closed", "Admin", "Raj Balani", _d(12), _d(1), "", "1.0.0", "Sprint 27", "Design Gap",
     "Open Support → Live Chat CTA", "", "", "FIXED launch pass"),
    ("BUG-OPEN-14", "Admin QA checklist local only", "Honesty banner: localStorage this browser only",
     "Admin Portal", "Admin QA checklist", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Closed", "Admin", "Shreya Patil", _d(12), _d(1), "", "1.0.0", "Sprint 27", "Design Gap",
     "Confirm banner; no multi-user pretend", "", "", "FIXED launch pass (documented)"),
    ("BUG-OPEN-15", "Exam papers browser mostly empty", "Many paper entries empty",
     "Gov Exam Mock Tests", "Exam papers browser", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Open", "GovExams", "Raj Balani", _d(20), "", "", "1.0.0", "Sprint 25", "Design Gap",
     "", "", "", ""),
    ("BUG-OPEN-16", "Question scraper not deployed", "Code complete; no deploy",
     "Gov Exam Mock Tests", "Python scraper service", "N/A", "N/A", "Desktop", "Linux",
     "High", "High", "Open", "GovExams", "Raj Balani", _d(35), "", "", "1.0.0", "Sprint 22", "Config/Env",
     "", "", "", "defer-with-roadmap"),
    ("BUG-OPEN-17", "collect-exam-papers brittle", "Allowlist hosts / Gemini failures",
     "Gov Exam Mock Tests", "Collect exam papers", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "High", "Blocked", "GovExams", "Raj Balani", _d(8), "", "", "1.0.0", "Sprint 26", "Third-party",
     "Needs GEMINI_API_KEY + allowlisted hosts", "", "", "Ops/provider blocker"),
    ("BUG-OPEN-18", "Windows binaries unsigned", "SmartScreen; signAndEditExecutable false",
     "Electron Desktop Overlay", "Code signing Windows", "Production", "N/A", "Desktop", "Windows",
     "High", "High", "Blocked", "Desktop", "Shreya Patil", _d(40), "", "", "1.0.0", "Sprint 22", "Config/Env",
     "Needs EV/OV code-signing certificate", "", "", "Ops blocker — no fake fix"),
    ("BUG-OPEN-19", "Electron auto-update trust weak", "Unsigned update chain",
     "Electron Desktop Overlay", "Auto-update", "Production", "N/A", "Desktop", "Windows",
     "High", "High", "Blocked", "Desktop", "Shreya Patil", _d(30), "", "", "1.0.0", "Sprint 23", "Config/Env",
     "Depends on EV/OV signing cert", "", "", "Ops blocker"),
    ("BUG-OPEN-20", "Low automated test coverage", "~5% real coverage; 794 it.todo placeholders",
     "Security & Platform", "Unit/E2E coverage", "CI", "N/A", "Desktop", "Windows",
     "High", "High", "Open", "Platform", "Shreya Patil", _d(45), "", "", "1.0.0", "Sprint 20", "Design Gap",
     "", "", "", "P4-4 ongoing"),
    ("BUG-OPEN-21", "No Playwright run evidence", "10 specs; no report artifacts",
     "Security & Platform", "Unit/E2E coverage", "CI", "N/A", "Desktop", "Windows",
     "Medium", "High", "Open", "Platform", "Shreya Patil", _d(45), "", "", "1.0.0", "Sprint 20", "Unknown",
     "", "", "", ""),
    ("BUG-OPEN-22", "Baseline schema incomplete in migrations", "Some tables still need staging dump DDL",
     "Security & Platform", "RLS + edge shared libs", "Local", "N/A", "Desktop", "Windows",
     "High", "High", "Open", "Platform", "Shreya Patil", _d(10), "", "", "1.0.0", "Sprint 26", "Config/Env",
     "Partial IF NOT EXISTS recovery shipped", "", "", "P4-5 partial"),
    ("BUG-OPEN-23", "deduct_credits RPC cannot service-role arbitrary user", "M4 deferred; JS gte path retained",
     "Billing & Credits", "Credits ledger", "Staging", "N/A", "Desktop", "Windows",
     "Medium", "High", "Open", "Billing", "Shreya Patil", _d(5), "", "", "1.0.0", "Sprint 26", "API Contract",
     "", "", "", "M4 DEFERRED"),
    ("BUG-OPEN-24", "Privacy settings toggles unused", "Analytics opt-out enforced; other prefs honesty-labelled",
     "Settings", "Privacy toggles", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Closed", "Platform", "Raj Balani", _d(18), _d(1), "", "1.0.0", "Sprint 27", "Logic Bug",
     "Toggle analytics off → PostHog opt-out", "", "", "FIXED launch pass"),
    ("BUG-OPEN-25", "Retention polish not enforced", "Settings exist; no enforcement",
     "Settings", "Retention polish", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Open", "Platform", "Raj Balani", _d(18), "", "", "1.0.0", "Sprint 25", "Design Gap",
     "", "", "", ""),
    ("BUG-OPEN-26", "Interview reminders need Resend", "Feature blocked without email secret",
     "Interviews & Calendar", "Interview email reminders", "Staging", "Chrome", "Desktop", "Windows",
     "Medium", "Medium", "Blocked", "Scheduling", "Raj Balani", _d(9), "", "", "1.0.0", "Sprint 26", "Config/Env",
     "Needs RESEND_API_KEY in Edge secrets", "", "", "Ops blocker — no fake fix"),
    ("BUG-OPEN-27", "Live coach desktop-first on mobile", "Poor mobile live experience",
     "Live Practice Coach", "Live Practice Coach session", "Staging", "Chrome", "iPhone", "iOS",
     "Medium", "Medium", "Open", "Live Coach", "Shreya Patil", _d(7), "", "", "1.0.0", "Sprint 26", "UI Regression",
     "", "https://example.com/live-mobile.png", "", ""),
    ("BUG-OPEN-28", "Admin tables poor on small screens", "overflow-x-auto on ModelCosts/Support/Revenue tables",
     "Admin Portal", "Admin users management", "Staging", "Chrome", "Android Phone", "Android",
     "Low", "Low", "Closed", "Admin", "Raj Balani", _d(6), _d(1), "", "1.0.0", "Sprint 28", "UI Regression",
     "Retest Model Costs + Support + Revenue on phone", "", "", "FIXED QA sync pass"),
    ("BUG-OPEN-29", "Group Practice still referenced historically", "Routes redirect; WebRTC descope",
     "Referrals & Guide", "In-app Guide/Help", "Staging", "Chrome", "Desktop", "Windows",
     "Low", "Low", "Closed", "Growth", "Shreya Patil", _d(12), _d(2), "", "1.0.0", "Sprint 26", "Design Gap",
     "Copy updated coming soon", "", "", ""),
    ("BUG-OPEN-30", "Anon key rotation still required", "Historical .env.production exposure",
     "Security & Platform", "RLS + edge shared libs", "Production", "N/A", "Desktop", "Windows",
     "High", "Critical", "Blocked", "Platform", "Shreya Patil", _d(3), "", "", "1.0.0", "Sprint 26", "Config/Env",
     "Rotate anon key in Supabase Dashboard only", "", "", "Ops blocker — cannot rotate from repo"),
]


def feature_counts_by_module():
    from collections import defaultdict
    totals = defaultdict(int)
    done = defaultdict(int)
    for f in FEATURES:
        mod = f[1]
        totals[mod] += 1
        if f[9] == "Completed" or f[10] == "Fully Implemented":
            # count completed features by Status Completed
            pass
        if f[9] == "Completed":
            done[mod] += 1
    return {m: (totals[m], done[m]) for m in totals}


# Route / QA runbook metadata (appended to Feature Inventory)
MODULE_DEFAULT_ROUTE = {
    "Auth & Onboarding": "/login",
    "Dashboard": "/app/dashboard",
    "Live Practice Coach": "/app/live",
    "Mock Interview": "/app/mock",
    "Sessions & Debriefs": "/app/sessions",
    "Analytics & Usage": "/app/analytics",
    "Prep Lab": "/app/prep",
    "Documents & Resumes": "/app/documents",
    "Answer Bank": "/app/answers",
    "Interviews & Calendar": "/app/interviews",
    "Company Research": "/app/companies",
    "Notifications & Profile": "/app/notifications",
    "Referrals & Guide": "/app/referrals",
    "Gov Exam Mock Tests": "/app/mock-test",
    "Settings": "/app/settings",
    "Admin Portal": "/app/admin",
    "Marketing Site": "/",
    "Billing & Credits": "/app/settings/billing",
    "Electron Desktop Overlay": "(Electron app)",
    "Security & Platform": "N/A",
}

FEATURE_ROUTE_OVERRIDES = {
    "FEAT-003": "/auth/verify",
    "FEAT-004": "/forgot-password",
    "FEAT-011": "/app/dashboard",
    "FEAT-031": "/app/usage",
    "FEAT-041": "/app/documents/jd/:id",
    "FEAT-042": "/app/documents/resume/:id",
    "FEAT-051": "/app/interview-day",
    "FEAT-054": "/app/settings/notifications",
    "FEAT-075": "/app/settings/privacy",
    "FEAT-079": "/app/settings/integrations",
    "FEAT-088": "/app/admin/live-chat",
    "FEAT-083": "/app/admin/model-costs",
    "FEAT-089": "/app/admin/support",
    "FEAT-091": "/app/admin/qa-checklist",
}

FEATURE_CREDIT_OVERRIDES = {
    "FEAT-017": "2 (live_hint)",
    "FEAT-018": "8 (live_answer)",
    "FEAT-019": "10 (screenshot_answer)",
    "FEAT-027": "15 (session_debrief)",
    "FEAT-033": "10 (star_builder)",
    "FEAT-035": "3 (rephraser)",
    "FEAT-039": "12 (resume_analysis; first onboarding free)",
    "FEAT-041": "10 (gap_analysis)",
    "FEAT-043": "8 (parse_document)",
    "FEAT-052": "20 (company_research)",
    "FEAT-061": "3 (create_mock_test) + AI gap fill 15",
}

FEATURE_ROLE_OVERRIDES = {
    "FEAT-019": "Pro+",
    "FEAT-052": "Pro+",
    "FEAT-049": "Pro+",
    "FEAT-083": "Admin",
    "FEAT-089": "Admin",
    "FEAT-091": "Admin",
}

FEATURE_BLOCKING_OVERRIDES = {
    "FEAT-047": "BUG-OPEN-26",
    "FEAT-049": "BUG-OPEN-03",
    "FEAT-050": "BUG-OPEN-07",
    "FEAT-024": "BUG-OPEN-04",
    "FEAT-055": "BUG-OPEN-09",
    "FEAT-066": "BUG-OPEN-17",
    "FEAT-068": "BUG-OPEN-17",
    "FEAT-105": "BUG-OPEN-18, BUG-OPEN-19",
}

FEATURE_HOW_OVERRIDES = {
    "FEAT-041": "Open a JD → select resume → Run gap analysis. Expect match score + skills; 402 if credits low.",
    "FEAT-042": "Open resume detail → Version history card lists parse snapshots (read-only).",
    "FEAT-054": "Settings → Notifications. Toggle category off, trigger send-email type; expect skipped when pref off.",
    "FEAT-061": "Mock Test Hub → configure exam → create test. Bank should return enough questions per major exam type.",
    "FEAT-075": "Settings → Privacy. Save analytics off; confirm PostHog opt-out. Other toggles show honesty copy.",
    "FEAT-083": "Admin → Model costs. Confirm read-only catalog; no Save that pretends to persist.",
    "FEAT-089": "Admin → Support. Use Open Live Chat CTA to reply.",
    "FEAT-091": "Admin → QA checklist. Confirm local-only banner; statuses stay in this browser.",
    "FEAT-011": "Mobile viewport → More sheet includes Usage and Interview Day matching sidebar.",
}


def feature_qa_columns(feat: tuple) -> tuple[str, str, str, str, str]:
    """Return (route, how_it_works, role, credit_cost, blocking_bugs)."""
    fid, module, name, desc = feat[0], feat[1], feat[2], feat[3]
    route = FEATURE_ROUTE_OVERRIDES.get(fid, MODULE_DEFAULT_ROUTE.get(module, "/app"))
    how = FEATURE_HOW_OVERRIDES.get(
        fid,
        f"Open {route}. Exercise '{name}' ({desc}). Confirm happy path for intended role; note plan gates and credit toasts.",
    )
    role = FEATURE_ROLE_OVERRIDES.get(fid, "Free+" if module != "Admin Portal" and module != "Marketing Site" else ("Admin" if module == "Admin Portal" else "Guest"))
    if module == "Marketing Site":
        role = "Guest"
    credit = FEATURE_CREDIT_OVERRIDES.get(fid, "0 / N/A")
    blocking = FEATURE_BLOCKING_OVERRIDES.get(fid, "")
    return route, how, role, credit, blocking


OPS_SECRETS_CHECKLIST = [
    ("VITE_SUPABASE_URL", "Client", "Required", "Supabase project URL"),
    ("VITE_SUPABASE_ANON_KEY / PUBLISHABLE_KEY", "Client", "Required", "Rotate in Dashboard if historically exposed (BUG-OPEN-30)"),
    ("SUPABASE_SERVICE_ROLE_KEY", "Edge secrets", "Required", "Never in Vite"),
    ("RESEND_API_KEY", "Edge secrets", "Blocked feature", "Interview reminders / send-email (BUG-OPEN-26)"),
    ("GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET", "Edge secrets", "Blocked feature", "Calendar sync 501 without these (BUG-OPEN-03)"),
    ("STRIPE_SECRET_KEY + webhook secret", "Edge secrets", "Required (USD)", "Checkout + webhooks"),
    ("RAZORPAY_KEY_ID / KEY_SECRET / WEBHOOK_SECRET", "Edge secrets", "Required (INR)", "One-time orders only — no Subscriptions"),
    ("GEMINI_API_KEY (or AI keys used by callAI)", "Edge secrets", "Required for AI", "Gap analysis, mocks, collect-exam-papers"),
    ("DEEPGRAM_API_KEY", "Edge secrets", "Required live", "STT token"),
    ("Code signing EV/OV cert", "CI/build", "Blocked desktop trust", "Unsigned Windows SmartScreen (BUG-OPEN-18/19)"),
    ("VITE_POSTHOG_KEY", "Client optional", "Optional", "Analytics opt-out tested when set"),
    ("VITE_SENTRY_DSN", "Client optional", "Optional", "Error reporting"),
]
