-- Scorecards are generated by the server scoring function. Clients may read
-- their own scorecards, but must not write authoritative scoring fields.

DROP POLICY IF EXISTS "Users can manage own scorecards" ON public.scorecards;

CREATE POLICY "Users can read own scorecards"
  ON public.scorecards FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
