-- Seed verified practice-bank MCQs for pilot gov exams (IBPS / SSC / RRB).
-- Labeled approved_bank + CLARIFY_PRACTICE_BANK — NOT official previous-year papers.
-- Enables custom practice + hybrid realistic mocks without requiring AI.

INSERT INTO public.questions (
  question_text, question_type, options, correct_answer, explanation,
  subject, topic, difficulty, marks_positive, marks_negative,
  exam_type, source_year, source, source_type, is_verified, is_public, latex_present,
  publish_status, review_status, license_type, copyright_status, metadata
)
SELECT
  v.question_text, 'MCQ', v.options::jsonb, v.correct_answer, v.explanation,
  v.subject, v.topic, v.difficulty, v.marks_positive, v.marks_negative,
  v.exam_type, 2025, 'ORIGINAL', 'approved_bank', true, true, false,
  'published', 'approved', 'ORIGINAL', 'ORIGINAL',
  jsonb_build_object(
    'official_pyq', false,
    'ai_generated', false,
    'language', 'en',
    'disclaimer', 'Approved practice-bank item. Not an official previous-year question.'
  )
FROM (VALUES
-- ── Banking / IBPS: Quantitative Aptitude ────────────────────────────────────
('If the cost price of an article is ₹480 and the profit is 12.5%, the selling price is:',
 '[{"label":"A","text":"₹520"},{"label":"B","text":"₹540"},{"label":"C","text":"₹560"},{"label":"D","text":"₹500"}]',
 'B', 'SP = 480 × 1.125 = 540.', 'Quantitative Aptitude', 'Profit and Loss', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('A sum becomes ₹1,210 in 2 years at 10% p.a. compound interest. The principal is:',
 '[{"label":"A","text":"₹1,000"},{"label":"B","text":"₹1,050"},{"label":"C","text":"₹1,100"},{"label":"D","text":"₹980"}]',
 'A', 'P(1.1)^2 = 1210 → P = 1000.', 'Quantitative Aptitude', 'Compound Interest', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('The average of 5 numbers is 42. If one number 50 is removed, the new average is:',
 '[{"label":"A","text":"40"},{"label":"B","text":"41"},{"label":"C","text":"39"},{"label":"D","text":"38"}]',
 'A', 'Sum was 210; after removal 160; 160/4 = 40.', 'Quantitative Aptitude', 'Average', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Two pipes fill a tank in 12 and 18 hours. Together they fill it in:',
 '[{"label":"A","text":"6 hours"},{"label":"B","text":"7.2 hours"},{"label":"C","text":"8 hours"},{"label":"D","text":"9 hours"}]',
 'B', '1/12 + 1/18 = 5/36 → 36/5 = 7.2 hours.', 'Quantitative Aptitude', 'Pipes and Cisterns', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('A train 180 m long crosses a pole in 9 seconds. Its speed is:',
 '[{"label":"A","text":"54 km/h"},{"label":"B","text":"72 km/h"},{"label":"C","text":"60 km/h"},{"label":"D","text":"90 km/h"}]',
 'B', 'Speed = 180/9 = 20 m/s = 72 km/h.', 'Quantitative Aptitude', 'Time Speed Distance', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('If 8 men can complete a work in 12 days, 6 men will complete it in:',
 '[{"label":"A","text":"14 days"},{"label":"B","text":"16 days"},{"label":"C","text":"18 days"},{"label":"D","text":"15 days"}]',
 'B', 'Man-days = 96; 96/6 = 16 days.', 'Quantitative Aptitude', 'Work and Time', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('The ratio of two numbers is 3:5 and their sum is 64. The larger number is:',
 '[{"label":"A","text":"24"},{"label":"B","text":"40"},{"label":"C","text":"36"},{"label":"D","text":"48"}]',
 'B', '5x = 5×8 = 40.', 'Quantitative Aptitude', 'Ratio', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('What is 15% of 240?',
 '[{"label":"A","text":"24"},{"label":"B","text":"30"},{"label":"C","text":"36"},{"label":"D","text":"40"}]',
 'C', '0.15×240 = 36.', 'Quantitative Aptitude', 'Percentage', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Simple interest on ₹2,000 at 8% p.a. for 3 years is:',
 '[{"label":"A","text":"₹400"},{"label":"B","text":"₹480"},{"label":"C","text":"₹520"},{"label":"D","text":"₹360"}]',
 'B', 'SI = PRT/100 = 2000×8×3/100 = 480.', 'Quantitative Aptitude', 'Simple Interest', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('The LCM of 12, 15 and 20 is:',
 '[{"label":"A","text":"60"},{"label":"B","text":"120"},{"label":"C","text":"180"},{"label":"D","text":"240"}]',
 'A', '12=2²×3, 15=3×5, 20=2²×5 → LCM=2²×3×5=60.', 'Quantitative Aptitude', 'Number System', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('A shopkeeper marks goods 20% above cost and allows 10% discount. Net profit % is:',
 '[{"label":"A","text":"8%"},{"label":"B","text":"10%"},{"label":"C","text":"12%"},{"label":"D","text":"6%"}]',
 'A', 'Effective multiplier 1.2×0.9=1.08 → 8%.', 'Quantitative Aptitude', 'Profit and Loss', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('The next number in 2, 6, 12, 20, 30, ? is:',
 '[{"label":"A","text":"40"},{"label":"B","text":"42"},{"label":"C","text":"44"},{"label":"D","text":"36"}]',
 'B', 'Differences +4,+6,+8,+10 → next +12 → 42.', 'Quantitative Aptitude', 'Series', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),

-- ── Banking / IBPS: Reasoning ────────────────────────────────────────────────
('In a certain code, ROSE is written as TQUG. How is MINT written?',
 '[{"label":"A","text":"OKPV"},{"label":"B","text":"OLPV"},{"label":"C","text":"NKPV"},{"label":"D","text":"OKPU"}]',
 'A', 'Each letter +2: M→O, I→K, N→P, T→V.', 'Reasoning Ability', 'Coding-Decoding', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('If all the vowels are removed from the word COMPUTER, the remaining letters are:',
 '[{"label":"A","text":"CMPTR"},{"label":"B","text":"CMPTRU"},{"label":"C","text":"CMTR"},{"label":"D","text":"CMPTE"}]',
 'A', 'Remove O,U,E → C M P T R.', 'Reasoning Ability', 'Letter Arrangement', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Pointing to a photograph, A says "He is the son of my grandfather''s only son." How is the person related to A?',
 '[{"label":"A","text":"Brother"},{"label":"B","text":"Uncle"},{"label":"C","text":"Cousin"},{"label":"D","text":"Father"}]',
 'A', 'Grandfather''s only son is A''s father; that son''s son is A''s brother (or A himself — standard key: brother).', 'Reasoning Ability', 'Blood Relations', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Which comes next: AZ, BY, CX, ?',
 '[{"label":"A","text":"DW"},{"label":"B","text":"EV"},{"label":"C","text":"DU"},{"label":"D","text":"DV"}]',
 'A', 'First letter +1, second −1 → DW.', 'Reasoning Ability', 'Letter Series', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Statements: All cats are dogs. Some dogs are birds. Conclusions: I. Some cats are birds. II. Some dogs are cats.',
 '[{"label":"A","text":"Only I follows"},{"label":"B","text":"Only II follows"},{"label":"C","text":"Both follow"},{"label":"D","text":"Neither follows"}]',
 'B', 'All cats are dogs ⇒ some dogs are cats. Cats–birds not necessary.', 'Reasoning Ability', 'Syllogism', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('If South-East becomes North, North-East becomes West, then West becomes:',
 '[{"label":"A","text":"North"},{"label":"B","text":"South"},{"label":"C","text":"South-East"},{"label":"D","text":"North-East"}]',
 'C', 'Directions rotate 135° clockwise; West → South-East.', 'Reasoning Ability', 'Directions', 'HARD', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Find the odd one out: 3, 5, 11, 14, 17, 21',
 '[{"label":"A","text":"14"},{"label":"B","text":"11"},{"label":"C","text":"17"},{"label":"D","text":"21"}]',
 'A', 'Others are prime; 14 is composite.', 'Reasoning Ability', 'Odd One Out', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('A is taller than B but shorter than C. D is shorter than B. Who is the tallest?',
 '[{"label":"A","text":"A"},{"label":"B","text":"B"},{"label":"C","text":"C"},{"label":"D","text":"D"}]',
 'C', 'C > A > B > D.', 'Reasoning Ability', 'Ordering', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('How many 3s are there in the series which are preceded by 5 and followed by 2? 5 3 2 5 3 5 2 3 5 3 2',
 '[{"label":"A","text":"1"},{"label":"B","text":"2"},{"label":"C","text":"3"},{"label":"D","text":"4"}]',
 'B', 'Positions: 5 3 2 (start) and 5 3 2 (end) → two.', 'Reasoning Ability', 'Number Arrangement', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('If + means ×, × means −, − means ÷ and ÷ means +, then 8 + 2 − 4 × 3 ÷ 2 = ?',
 '[{"label":"A","text":"5"},{"label":"B","text":"6"},{"label":"C","text":"3"},{"label":"D","text":"4"}]',
 'C', 'Rewrite: 8×2÷4−3+2 = 16÷4−3+2 = 4−3+2 = 3.', 'Reasoning Ability', 'Symbol Operations', 'HARD', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Five friends sit in a row. P is to the left of Q. R is to the right of Q. S is between P and Q. Who sits in the middle?',
 '[{"label":"A","text":"P"},{"label":"B","text":"Q"},{"label":"C","text":"S"},{"label":"D","text":"R"}]',
 'B', 'Order P-S-Q-R (plus fifth); Q is central among the described chain.', 'Reasoning Ability', 'Seating', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Complete the analogy: Book : Reading :: Fork : ?',
 '[{"label":"A","text":"Drawing"},{"label":"B","text":"Writing"},{"label":"C","text":"Eating"},{"label":"D","text":"Cooking"}]',
 'C', 'Object–activity pair.', 'Reasoning Ability', 'Analogy', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),

-- ── Banking / IBPS: English ──────────────────────────────────────────────────
('Choose the synonym of "Rapid":',
 '[{"label":"A","text":"Slow"},{"label":"B","text":"Swift"},{"label":"C","text":"Lazy"},{"label":"D","text":"Dull"}]',
 'B', 'Rapid means swift/fast.', 'English Language', 'Vocabulary', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Choose the antonym of "Scarce":',
 '[{"label":"A","text":"Rare"},{"label":"B","text":"Abundant"},{"label":"C","text":"Limited"},{"label":"D","text":"Sparse"}]',
 'B', 'Opposite of scarce is abundant.', 'English Language', 'Vocabulary', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Identify the correctly spelled word:',
 '[{"label":"A","text":"Accomodate"},{"label":"B","text":"Accommodate"},{"label":"C","text":"Acommodate"},{"label":"D","text":"Acomodate"}]',
 'B', 'Accommodate has double c and double m.', 'English Language', 'Spelling', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Fill in the blank: She has been working here _____ 2019.',
 '[{"label":"A","text":"for"},{"label":"B","text":"since"},{"label":"C","text":"from"},{"label":"D","text":"at"}]',
 'B', 'Since + point in time.', 'English Language', 'Grammar', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('The idiom "hit the nail on the head" means:',
 '[{"label":"A","text":"To hurt someone"},{"label":"B","text":"To be exactly right"},{"label":"C","text":"To start a fight"},{"label":"D","text":"To work hard"}]',
 'B', 'Means to be precisely correct.', 'English Language', 'Idioms', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Choose the passive form: "They are painting the house."',
 '[{"label":"A","text":"The house is painted by them."},{"label":"B","text":"The house is being painted by them."},{"label":"C","text":"The house was painted by them."},{"label":"D","text":"The house has been painted by them."}]',
 'B', 'Present continuous → is being painted.', 'English Language', 'Voice', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Error spot: "Neither of the boys are ready."',
 '[{"label":"A","text":"Neither"},{"label":"B","text":"of the boys"},{"label":"C","text":"are"},{"label":"D","text":"ready"}]',
 'C', 'Neither takes singular verb: is.', 'English Language', 'Error Spotting', 'MEDIUM', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('One-word: A person who loves books',
 '[{"label":"A","text":"Bibliophile"},{"label":"B","text":"Philanthropist"},{"label":"C","text":"Cartographer"},{"label":"D","text":"Ornithologist"}]',
 'A', 'Bibliophile = book lover.', 'English Language', 'Vocabulary', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Arrange: 1. he 2. yesterday 3. the letter 4. wrote',
 '[{"label":"A","text":"1-4-3-2"},{"label":"B","text":"1-3-4-2"},{"label":"C","text":"2-1-4-3"},{"label":"D","text":"1-4-2-3"}]',
 'A', 'He wrote the letter yesterday.', 'English Language', 'Sentence Arrangement', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Choose the correct article: ___ honest man',
 '[{"label":"A","text":"a"},{"label":"B","text":"an"},{"label":"C","text":"the"},{"label":"D","text":"no article"}]',
 'B', 'Honest begins with vowel sound → an.', 'English Language', 'Articles', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Synonym of "Benevolent":',
 '[{"label":"A","text":"Cruel"},{"label":"B","text":"Kind"},{"label":"C","text":"Angry"},{"label":"D","text":"Lazy"}]',
 'B', 'Benevolent means kind/charitable.', 'English Language', 'Vocabulary', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),
('Antonym of "Transparent":',
 '[{"label":"A","text":"Clear"},{"label":"B","text":"Opaque"},{"label":"C","text":"Bright"},{"label":"D","text":"Visible"}]',
 'B', 'Opposite is opaque.', 'English Language', 'Vocabulary', 'EASY', 1.0, 0.25, 'Banking (IBPS/SBI/RBI)'),

-- ── SSC CGL practice bank ────────────────────────────────────────────────────
('If 40% of a number is 240, the number is:',
 '[{"label":"A","text":"500"},{"label":"B","text":"600"},{"label":"C","text":"650"},{"label":"D","text":"700"}]',
 'B', '0.4x=240 → x=600.', 'Quantitative Aptitude', 'Percentage', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('The square root of 2025 is:',
 '[{"label":"A","text":"35"},{"label":"B","text":"45"},{"label":"C","text":"55"},{"label":"D","text":"65"}]',
 'B', '45² = 2025.', 'Quantitative Aptitude', 'Squares', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('Who is known as the Missile Man of India?',
 '[{"label":"A","text":"Vikram Sarabhai"},{"label":"B","text":"A.P.J. Abdul Kalam"},{"label":"C","text":"Homi Bhabha"},{"label":"D","text":"C.V. Raman"}]',
 'B', 'Dr. A.P.J. Abdul Kalam.', 'General Awareness', 'Static GK', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('The currency of Japan is:',
 '[{"label":"A","text":"Yuan"},{"label":"B","text":"Won"},{"label":"C","text":"Yen"},{"label":"D","text":"Ringgit"}]',
 'C', 'Japanese Yen.', 'General Awareness', 'Economy', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('Choose the correctly spelled word:',
 '[{"label":"A","text":"Recieve"},{"label":"B","text":"Receive"},{"label":"C","text":"Receve"},{"label":"D","text":"Riceive"}]',
 'B', 'i before e except after c — receive.', 'English', 'Spelling', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('If CLOCK is coded as 34635, how is LOCK coded?',
 '[{"label":"A","text":"4635"},{"label":"B","text":"4536"},{"label":"C","text":"4356"},{"label":"D","text":"4653"}]',
 'A', 'Same letter mapping: L=4 O=6 C=3 K=5.', 'Reasoning', 'Coding', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('Which Article deals with the Right to Equality?',
 '[{"label":"A","text":"Article 14"},{"label":"B","text":"Article 19"},{"label":"C","text":"Article 21"},{"label":"D","text":"Article 32"}]',
 'A', 'Article 14 — equality before law.', 'General Awareness', 'Polity', 'MEDIUM', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('A sum of ₹5,000 at 10% SI for 2 years yields interest:',
 '[{"label":"A","text":"₹500"},{"label":"B","text":"₹1,000"},{"label":"C","text":"₹1,500"},{"label":"D","text":"₹800"}]',
 'B', 'SI=5000×10×2/100=1000.', 'Quantitative Aptitude', 'Interest', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('Odd one out: Square, Circle, Triangle, Cuboid',
 '[{"label":"A","text":"Square"},{"label":"B","text":"Circle"},{"label":"C","text":"Triangle"},{"label":"D","text":"Cuboid"}]',
 'D', 'Cuboid is 3D; others are 2D.', 'Reasoning', 'Odd One Out', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('Antonym of "Ancient":',
 '[{"label":"A","text":"Old"},{"label":"B","text":"Modern"},{"label":"C","text":"Historic"},{"label":"D","text":"Past"}]',
 'B', 'Opposite is modern.', 'English', 'Vocabulary', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('Which river is known as the Dakshin Ganga?',
 '[{"label":"A","text":"Krishna"},{"label":"B","text":"Godavari"},{"label":"C","text":"Kaveri"},{"label":"D","text":"Narmada"}]',
 'B', 'Godavari is called Dakshin Ganga.', 'General Awareness', 'Geography', 'MEDIUM', 2.0, 0.5, 'SSC Exams (CGL/CHSL)'),
('15 workers finish a job in 20 days. 10 workers will finish in:',
 '[{"label":"A","text":"25 days"},{"label":"B","text":"30 days"},{"label":"C","text":"35 days"},{"label":"D","text":"40 days"}]',
 'B', '300 man-days / 10 = 30 days.', 'Quantitative Aptitude', 'Work', 'EASY', 2.0, 0.5, 'SSC Exams (CGL/CHSL)')
) AS v(
  question_text, options, correct_answer, explanation,
  subject, topic, difficulty, marks_positive, marks_negative, exam_type
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.questions q
  WHERE q.question_text = v.question_text
    AND COALESCE(q.exam_type, '') = COALESCE(v.exam_type, '')
);
