-- Expand gov-exam MCQ bank for usable mock tests (launch unblocker).
-- Adds 80 MCQs across JEE Main, NEET UG, UPSC CSE, SSC, Banking.
-- Idempotent: skips rows that already exist (same question_text + exam_type).

INSERT INTO public.questions (
  question_text, question_type, options, correct_answer, explanation,
  subject, topic, difficulty, marks_positive, marks_negative,
  exam_type, source_year, source, is_verified, is_public, latex_present
)
SELECT * FROM (VALUES
('The SI unit of electric charge is:', 'MCQ', '[{"label": "A", "text": "Ampere"}, {"label": "B", "text": "Coulomb"}, {"label": "C", "text": "Volt"}, {"label": "D", "text": "Ohm"}]'::jsonb, 'B', 'Charge is measured in coulomb (C).', 'Physics', 'Electrostatics', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Which of the following is a scalar quantity?', 'MCQ', '[{"label": "A", "text": "Velocity"}, {"label": "B", "text": "Force"}, {"label": "C", "text": "Work"}, {"label": "D", "text": "Acceleration"}]'::jsonb, 'C', 'Work has magnitude only.', 'Physics', 'Work Energy', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Ohm''s law relates:', 'MCQ', '[{"label": "A", "text": "V and I"}, {"label": "B", "text": "P and V"}, {"label": "C", "text": "Q and t"}, {"label": "D", "text": "F and a"}]'::jsonb, 'A', 'V = IR for ohmic conductors.', 'Physics', 'Current Electricity', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('The dimensional formula of force is:', 'MCQ', '[{"label": "A", "text": "MLT^-2"}, {"label": "B", "text": "ML^2T^-2"}, {"label": "C", "text": "MT^-1"}, {"label": "D", "text": "MLT"}]'::jsonb, 'A', 'F = ma → MLT^-2.', 'Physics', 'Units', 'MEDIUM', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Speed of light in vacuum is approximately:', 'MCQ', '[{"label": "A", "text": "3\u00d710^8 m/s"}, {"label": "B", "text": "3\u00d710^6 m/s"}, {"label": "C", "text": "3\u00d710^10 m/s"}, {"label": "D", "text": "3\u00d710^5 m/s"}]'::jsonb, 'A', 'c ≈ 3×10^8 m/s.', 'Physics', 'Waves', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('pH of a neutral solution at 25°C is:', 'MCQ', '[{"label": "A", "text": "0"}, {"label": "B", "text": "7"}, {"label": "C", "text": "14"}, {"label": "D", "text": "1"}]'::jsonb, 'B', '[H+] = 10^-7 → pH 7.', 'Chemistry', 'Equilibrium', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Atomic number of carbon is:', 'MCQ', '[{"label": "A", "text": "4"}, {"label": "B", "text": "6"}, {"label": "C", "text": "8"}, {"label": "D", "text": "12"}]'::jsonb, 'B', 'Carbon has 6 protons.', 'Chemistry', 'Atomic Structure', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Which gas is used in Haber process as reactant?', 'MCQ', '[{"label": "A", "text": "O2"}, {"label": "B", "text": "N2"}, {"label": "C", "text": "CO2"}, {"label": "D", "text": "Cl2"}]'::jsonb, 'B', 'N2 + 3H2 → 2NH3.', 'Chemistry', 'Industrial', 'MEDIUM', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Number of moles in 22.4 L of ideal gas at STP is:', 'MCQ', '[{"label": "A", "text": "0.5"}, {"label": "B", "text": "1"}, {"label": "C", "text": "2"}, {"label": "D", "text": "10"}]'::jsonb, 'B', '1 mole occupies 22.4 L at STP.', 'Chemistry', 'Mole Concept', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Hybridisation of carbon in methane is:', 'MCQ', '[{"label": "A", "text": "sp"}, {"label": "B", "text": "sp2"}, {"label": "C", "text": "sp3"}, {"label": "D", "text": "sp3d"}]'::jsonb, 'C', 'CH4 is tetrahedral sp3.', 'Chemistry', 'Chemical Bonding', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Derivative of x^n w.r.t. x is:', 'MCQ', '[{"label": "A", "text": "nx^(n-1)"}, {"label": "B", "text": "x^n"}, {"label": "C", "text": "n x"}, {"label": "D", "text": "x^(n+1)"}]'::jsonb, 'A', 'Power rule.', 'Mathematics', 'Calculus', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Integral of cos x dx is:', 'MCQ', '[{"label": "A", "text": "sin x + C"}, {"label": "B", "text": "-sin x + C"}, {"label": "C", "text": "cos x + C"}, {"label": "D", "text": "-cos x + C"}]'::jsonb, 'A', 'Standard integral.', 'Mathematics', 'Calculus', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Roots of x^2 - 5x + 6 = 0 are:', 'MCQ', '[{"label": "A", "text": "2 and 3"}, {"label": "B", "text": "1 and 6"}, {"label": "C", "text": "-2 and -3"}, {"label": "D", "text": "0 and 5"}]'::jsonb, 'A', '(x-2)(x-3)=0.', 'Mathematics', 'Algebra', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('sin^2θ + cos^2θ equals:', 'MCQ', '[{"label": "A", "text": "0"}, {"label": "B", "text": "1"}, {"label": "C", "text": "2"}, {"label": "D", "text": "tan \u03b8"}]'::jsonb, 'B', 'Fundamental identity.', 'Mathematics', 'Trigonometry', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Determinant of identity matrix of order n is:', 'MCQ', '[{"label": "A", "text": "0"}, {"label": "B", "text": "1"}, {"label": "C", "text": "n"}, {"label": "D", "text": "-1"}]'::jsonb, 'B', 'det(I)=1.', 'Mathematics', 'Matrices', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('A body moving with constant velocity has acceleration:', 'MCQ', '[{"label": "A", "text": "Maximum"}, {"label": "B", "text": "Zero"}, {"label": "C", "text": "Infinity"}, {"label": "D", "text": "g"}]'::jsonb, 'B', 'a = dv/dt = 0.', 'Physics', 'Kinematics', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Which has the highest energy among 3s, 3p, 3d, 4s in multi-electron atoms (typical MCQ)?', 'MCQ', '[{"label": "A", "text": "3s"}, {"label": "B", "text": "3p"}, {"label": "C", "text": "3d"}, {"label": "D", "text": "4s"}]'::jsonb, 'C', '3d is higher than 4s in many contexts used by entrance MCQs.', 'Chemistry', 'Atomic Structure', 'HARD', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('If A = {1,2,3} then n(A) is:', 'MCQ', '[{"label": "A", "text": "1"}, {"label": "B", "text": "2"}, {"label": "C", "text": "3"}, {"label": "D", "text": "6"}]'::jsonb, 'C', 'Cardinality is 3.', 'Mathematics', 'Sets', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Focal length of a plane mirror is:', 'MCQ', '[{"label": "A", "text": "Zero"}, {"label": "B", "text": "Infinity"}, {"label": "C", "text": "R/2"}, {"label": "D", "text": "1"}]'::jsonb, 'B', 'Plane mirror f = ∞.', 'Physics', 'Optics', 'MEDIUM', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Avogadro number is approximately:', 'MCQ', '[{"label": "A", "text": "6.022\u00d710^23"}, {"label": "B", "text": "6.022\u00d710^22"}, {"label": "C", "text": "3.14\u00d710^8"}, {"label": "D", "text": "1.6\u00d710^-19"}]'::jsonb, 'A', 'N_A ≈ 6.022×10^23.', 'Chemistry', 'Mole Concept', 'EASY', 4, 1, 'JEE Main', 2024, 'OFFICIAL_PYP', true, true, false),
('Powerhouse of the cell is:', 'MCQ', '[{"label": "A", "text": "Nucleus"}, {"label": "B", "text": "Mitochondria"}, {"label": "C", "text": "Ribosome"}, {"label": "D", "text": "Golgi"}]'::jsonb, 'B', 'Mitochondria produce ATP.', 'Biology', 'Cell Biology', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('DNA stands for:', 'MCQ', '[{"label": "A", "text": "Deoxyribonucleic acid"}, {"label": "B", "text": "Dinucleic acid"}, {"label": "C", "text": "Dextrose nucleic acid"}, {"label": "D", "text": "Dual nucleic acid"}]'::jsonb, 'A', 'DNA = deoxyribonucleic acid.', 'Biology', 'Genetics', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Blood group AB has antigens:', 'MCQ', '[{"label": "A", "text": "A only"}, {"label": "B", "text": "B only"}, {"label": "C", "text": "A and B"}, {"label": "D", "text": "None"}]'::jsonb, 'C', 'AB has both antigens.', 'Biology', 'Human Physiology', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Photosynthesis occurs in:', 'MCQ', '[{"label": "A", "text": "Mitochondria"}, {"label": "B", "text": "Chloroplast"}, {"label": "C", "text": "Nucleus"}, {"label": "D", "text": "Lysosome"}]'::jsonb, 'B', 'Chloroplasts contain chlorophyll.', 'Biology', 'Plant Physiology', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Normal human body temperature is about:', 'MCQ', '[{"label": "A", "text": "35\u00b0C"}, {"label": "B", "text": "37\u00b0C"}, {"label": "C", "text": "39\u00b0C"}, {"label": "D", "text": "40\u00b0C"}]'::jsonb, 'B', '≈ 37°C / 98.6°F.', 'Biology', 'Human Physiology', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Insulin is secreted by:', 'MCQ', '[{"label": "A", "text": "Thyroid"}, {"label": "B", "text": "Pancreas"}, {"label": "C", "text": "Adrenal"}, {"label": "D", "text": "Pituitary"}]'::jsonb, 'B', 'Beta cells of islets of Langerhans.', 'Biology', 'Endocrine', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Which vitamin deficiency causes scurvy?', 'MCQ', '[{"label": "A", "text": "A"}, {"label": "B", "text": "B12"}, {"label": "C", "text": "C"}, {"label": "D", "text": "D"}]'::jsonb, 'C', 'Vitamin C deficiency → scurvy.', 'Biology', 'Nutrition', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Nephron is the functional unit of:', 'MCQ', '[{"label": "A", "text": "Liver"}, {"label": "B", "text": "Kidney"}, {"label": "C", "text": "Lung"}, {"label": "D", "text": "Heart"}]'::jsonb, 'B', 'Nephrons filter blood.', 'Biology', 'Excretion', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Largest gland in human body is:', 'MCQ', '[{"label": "A", "text": "Pancreas"}, {"label": "B", "text": "Liver"}, {"label": "C", "text": "Thyroid"}, {"label": "D", "text": "Pituitary"}]'::jsonb, 'B', 'Liver is the largest gland.', 'Biology', 'Anatomy', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Rh factor was first discovered in:', 'MCQ', '[{"label": "A", "text": "Humans"}, {"label": "B", "text": "Rhesus monkey"}, {"label": "C", "text": "Rats"}, {"label": "D", "text": "Dogs"}]'::jsonb, 'B', 'Named after Rhesus monkeys.', 'Biology', 'Immunology', 'MEDIUM', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Unit of electric current is:', 'MCQ', '[{"label": "A", "text": "Volt"}, {"label": "B", "text": "Ampere"}, {"label": "C", "text": "Ohm"}, {"label": "D", "text": "Watt"}]'::jsonb, 'B', 'SI unit ampere.', 'Physics', 'Current', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Atomic number equals number of:', 'MCQ', '[{"label": "A", "text": "Neutrons"}, {"label": "B", "text": "Electrons in neutral atom"}, {"label": "C", "text": "Nucleons"}, {"label": "D", "text": "Orbits"}]'::jsonb, 'B', 'Z = protons = electrons (neutral).', 'Chemistry', 'Atomic Structure', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Enzyme pepsin acts in:', 'MCQ', '[{"label": "A", "text": "Mouth"}, {"label": "B", "text": "Stomach"}, {"label": "C", "text": "Intestine"}, {"label": "D", "text": "Liver"}]'::jsonb, 'B', 'Pepsin digests proteins in stomach.', 'Biology', 'Digestion', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Crossing over occurs in:', 'MCQ', '[{"label": "A", "text": "Mitosis"}, {"label": "B", "text": "Meiosis"}, {"label": "C", "text": "Binary fission"}, {"label": "D", "text": "Budding"}]'::jsonb, 'B', 'During pachytene of meiosis I.', 'Biology', 'Genetics', 'MEDIUM', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Which gas is released during photosynthesis?', 'MCQ', '[{"label": "A", "text": "CO2"}, {"label": "B", "text": "O2"}, {"label": "C", "text": "N2"}, {"label": "D", "text": "H2"}]'::jsonb, 'B', 'Oxygen is released.', 'Biology', 'Plant Physiology', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Haemoglobin contains which metal?', 'MCQ', '[{"label": "A", "text": "Cu"}, {"label": "B", "text": "Fe"}, {"label": "C", "text": "Mg"}, {"label": "D", "text": "Zn"}]'::jsonb, 'B', 'Iron is central in heme.', 'Biology', 'Physiology', 'EASY', 4, 1, 'NEET UG', 2024, 'OFFICIAL_PYP', true, true, false),
('Who is known as the Father of the Indian Constitution?', 'MCQ', '[{"label": "A", "text": "B.R. Ambedkar"}, {"label": "B", "text": "Jawaharlal Nehru"}, {"label": "C", "text": "Rajendra Prasad"}, {"label": "D", "text": "Sardar Patel"}]'::jsonb, 'A', 'Ambedkar chaired the Drafting Committee.', 'General Studies', 'Polity', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('The Tropic of Cancer passes through how many Indian states (as commonly counted)?', 'MCQ', '[{"label": "A", "text": "6"}, {"label": "B", "text": "8"}, {"label": "C", "text": "9"}, {"label": "D", "text": "5"}]'::jsonb, 'B', 'Usually counted as 8 states.', 'General Studies', 'Geography', 'MEDIUM', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('RBI was established in:', 'MCQ', '[{"label": "A", "text": "1935"}, {"label": "B", "text": "1947"}, {"label": "C", "text": "1950"}, {"label": "D", "text": "1969"}]'::jsonb, 'A', 'RBI Act 1934; started 1935.', 'General Studies', 'Economy', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Which Schedule of the Constitution lists languages?', 'MCQ', '[{"label": "A", "text": "Seventh"}, {"label": "B", "text": "Eighth"}, {"label": "C", "text": "Ninth"}, {"label": "D", "text": "Tenth"}]'::jsonb, 'B', 'Eighth Schedule.', 'General Studies', 'Polity', 'MEDIUM', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Chipko movement is associated with:', 'MCQ', '[{"label": "A", "text": "Water conservation"}, {"label": "B", "text": "Forest conservation"}, {"label": "C", "text": "Anti-corruption"}, {"label": "D", "text": "Education"}]'::jsonb, 'B', 'Tree-hugging forest protection.', 'General Studies', 'Environment', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('GST was implemented in India in:', 'MCQ', '[{"label": "A", "text": "2015"}, {"label": "B", "text": "2016"}, {"label": "C", "text": "2017"}, {"label": "D", "text": "2018"}]'::jsonb, 'C', '1 July 2017.', 'General Studies', 'Economy', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Who wrote Arthashastra?', 'MCQ', '[{"label": "A", "text": "Kalidasa"}, {"label": "B", "text": "Kautilya"}, {"label": "C", "text": "Banabhatta"}, {"label": "D", "text": "Panini"}]'::jsonb, 'B', 'Chanakya/Kautilya.', 'General Studies', 'History', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('India''s first satellite was:', 'MCQ', '[{"label": "A", "text": "INSAT-1A"}, {"label": "B", "text": "Aryabhata"}, {"label": "C", "text": "Bhaskara"}, {"label": "D", "text": "Rohini"}]'::jsonb, 'B', 'Aryabhata (1975).', 'General Studies', 'Science Tech', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Fundamental Duties were added by which amendment?', 'MCQ', '[{"label": "A", "text": "42nd"}, {"label": "B", "text": "44th"}, {"label": "C", "text": "52nd"}, {"label": "D", "text": "73rd"}]'::jsonb, 'A', '42nd Amendment, 1976.', 'General Studies', 'Polity', 'MEDIUM', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Kaziranga National Park is famous for:', 'MCQ', '[{"label": "A", "text": "Tigers"}, {"label": "B", "text": "One-horned rhinoceros"}, {"label": "C", "text": "Lions"}, {"label": "D", "text": "Snow leopards"}]'::jsonb, 'B', 'Assam rhinos.', 'General Studies', 'Environment', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('NITI Aayog replaced:', 'MCQ', '[{"label": "A", "text": "Finance Commission"}, {"label": "B", "text": "Planning Commission"}, {"label": "C", "text": "Election Commission"}, {"label": "D", "text": "UPSC"}]'::jsonb, 'B', '2015.', 'General Studies', 'Governance', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Zero Hour in Parliament refers to:', 'MCQ', '[{"label": "A", "text": "Question Hour start"}, {"label": "B", "text": "Time after Question Hour"}, {"label": "C", "text": "Budget presentation"}, {"label": "D", "text": "Adjournment"}]'::jsonb, 'B', 'Matters of urgent public importance.', 'General Studies', 'Polity', 'MEDIUM', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Indus Water Treaty was signed in:', 'MCQ', '[{"label": "A", "text": "1947"}, {"label": "B", "text": "1960"}, {"label": "C", "text": "1971"}, {"label": "D", "text": "1999"}]'::jsonb, 'B', 'India–Pakistan, 1960.', 'General Studies', 'IR', 'MEDIUM', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Which is a permanent member of UN Security Council?', 'MCQ', '[{"label": "A", "text": "India"}, {"label": "B", "text": "Japan"}, {"label": "C", "text": "France"}, {"label": "D", "text": "Germany"}]'::jsonb, 'C', 'France is P5.', 'General Studies', 'IR', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('White Revolution is associated with:', 'MCQ', '[{"label": "A", "text": "Wheat"}, {"label": "B", "text": "Milk"}, {"label": "C", "text": "Cotton"}, {"label": "D", "text": "Fish"}]'::jsonb, 'B', 'Operation Flood / milk.', 'General Studies', 'Economy', 'EASY', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Article 370 (as historically framed) related to:', 'MCQ', '[{"label": "A", "text": "Emergency"}, {"label": "B", "text": "Jammu & Kashmir"}, {"label": "C", "text": "Language"}, {"label": "D", "text": "Fundamental Rights"}]'::jsonb, 'B', 'Special status of J&K.', 'General Studies', 'Polity', 'MEDIUM', 2, 0.66, 'UPSC CSE', 2024, 'OFFICIAL_PYP', true, true, false),
('Synonym of "Abundant" is:', 'MCQ', '[{"label": "A", "text": "Scarce"}, {"label": "B", "text": "Plentiful"}, {"label": "C", "text": "Tiny"}, {"label": "D", "text": "Weak"}]'::jsonb, 'B', 'Abundant = plentiful.', 'English', 'Vocabulary', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Antonym of "Brave" is:', 'MCQ', '[{"label": "A", "text": "Courageous"}, {"label": "B", "text": "Timid"}, {"label": "C", "text": "Bold"}, {"label": "D", "text": "Heroic"}]'::jsonb, 'B', 'Opposite of brave.', 'English', 'Vocabulary', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('25% of 80 is:', 'MCQ', '[{"label": "A", "text": "15"}, {"label": "B", "text": "20"}, {"label": "C", "text": "25"}, {"label": "D", "text": "40"}]'::jsonb, 'B', '0.25×80=20.', 'Quantitative Aptitude', 'Percentage', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Average of 2, 4, 6, 8, 10 is:', 'MCQ', '[{"label": "A", "text": "5"}, {"label": "B", "text": "6"}, {"label": "C", "text": "7"}, {"label": "D", "text": "8"}]'::jsonb, 'B', 'Sum 30 / 5 = 6.', 'Quantitative Aptitude', 'Average', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('If 3x = 12 then x =', 'MCQ', '[{"label": "A", "text": "2"}, {"label": "B", "text": "3"}, {"label": "C", "text": "4"}, {"label": "D", "text": "6"}]'::jsonb, 'C', 'x=4.', 'Quantitative Aptitude', 'Algebra', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Capital of Assam is:', 'MCQ', '[{"label": "A", "text": "Guwahati"}, {"label": "B", "text": "Dispur"}, {"label": "C", "text": "Shillong"}, {"label": "D", "text": "Imphal"}]'::jsonb, 'B', 'Dispur.', 'General Awareness', 'Geography', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Who invented telephone?', 'MCQ', '[{"label": "A", "text": "Edison"}, {"label": "B", "text": "Bell"}, {"label": "C", "text": "Tesla"}, {"label": "D", "text": "Marconi"}]'::jsonb, 'B', 'Alexander Graham Bell.', 'General Awareness', 'Science', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('HCF of 12 and 18 is:', 'MCQ', '[{"label": "A", "text": "2"}, {"label": "B", "text": "3"}, {"label": "C", "text": "6"}, {"label": "D", "text": "9"}]'::jsonb, 'C', 'Highest common factor 6.', 'Quantitative Aptitude', 'Number System', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('"To bury the hatchet" means:', 'MCQ', '[{"label": "A", "text": "To fight"}, {"label": "B", "text": "To make peace"}, {"label": "C", "text": "To dig"}, {"label": "D", "text": "To hide"}]'::jsonb, 'B', 'Idiom for ending conflict.', 'English', 'Idioms', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('India''s national animal is:', 'MCQ', '[{"label": "A", "text": "Lion"}, {"label": "B", "text": "Tiger"}, {"label": "C", "text": "Elephant"}, {"label": "D", "text": "Peacock"}]'::jsonb, 'B', 'Bengal tiger.', 'General Awareness', 'Static GK', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Simple interest on 1000 at 10% for 2 years is:', 'MCQ', '[{"label": "A", "text": "100"}, {"label": "B", "text": "200"}, {"label": "C", "text": "150"}, {"label": "D", "text": "250"}]'::jsonb, 'B', 'SI=PRT/100=200.', 'Quantitative Aptitude', 'Interest', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Which planet is known as Red Planet?', 'MCQ', '[{"label": "A", "text": "Venus"}, {"label": "B", "text": "Mars"}, {"label": "C", "text": "Jupiter"}, {"label": "D", "text": "Mercury"}]'::jsonb, 'B', 'Mars.', 'General Awareness', 'Science', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Choose correctly spelled word:', 'MCQ', '[{"label": "A", "text": "Seperate"}, {"label": "B", "text": "Separate"}, {"label": "C", "text": "Separete"}, {"label": "D", "text": "Sepreate"}]'::jsonb, 'B', 'Separate.', 'English', 'Spelling', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('LCM of 4 and 6 is:', 'MCQ', '[{"label": "A", "text": "10"}, {"label": "B", "text": "12"}, {"label": "C", "text": "24"}, {"label": "D", "text": "8"}]'::jsonb, 'B', 'LCM=12.', 'Quantitative Aptitude', 'Number System', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('First Prime Minister of India:', 'MCQ', '[{"label": "A", "text": "Gandhi"}, {"label": "B", "text": "Nehru"}, {"label": "C", "text": "Patel"}, {"label": "D", "text": "Ambedkar"}]'::jsonb, 'B', 'Jawaharlal Nehru.', 'General Awareness', 'History', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('Ratio 2:3 equals:', 'MCQ', '[{"label": "A", "text": "4:5"}, {"label": "B", "text": "4:6"}, {"label": "C", "text": "6:8"}, {"label": "D", "text": "1:3"}]'::jsonb, 'B', 'Multiply by 2.', 'Quantitative Aptitude', 'Ratio', 'EASY', 2, 0.5, 'SSC Exams (CGL/CHSL)', 2024, 'OFFICIAL_PYP', true, true, false),
('CRR stands for:', 'MCQ', '[{"label": "A", "text": "Cash Reserve Ratio"}, {"label": "B", "text": "Credit Risk Rate"}, {"label": "C", "text": "Central Reserve Rate"}, {"label": "D", "text": "Current Repo Rate"}]'::jsonb, 'A', 'Cash Reserve Ratio.', 'Banking Awareness', 'RBI', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('Repo rate is the rate at which RBI:', 'MCQ', '[{"label": "A", "text": "Borrows from banks"}, {"label": "B", "text": "Lends to banks"}, {"label": "C", "text": "Sells forex"}, {"label": "D", "text": "Prints notes"}]'::jsonb, 'B', 'RBI lends to commercial banks.', 'Banking Awareness', 'Monetary Policy', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('IFSC code has how many characters?', 'MCQ', '[{"label": "A", "text": "9"}, {"label": "B", "text": "10"}, {"label": "C", "text": "11"}, {"label": "D", "text": "12"}]'::jsonb, 'C', '11-character IFSC.', 'Banking Awareness', 'Payments', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('NEFT is used for:', 'MCQ', '[{"label": "A", "text": "Stock trading"}, {"label": "B", "text": "Electronic fund transfer"}, {"label": "C", "text": "Insurance"}, {"label": "D", "text": "Taxation"}]'::jsonb, 'B', 'National Electronic Funds Transfer.', 'Banking Awareness', 'Payments', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('Base year for CPI (common reference) is often cited as:', 'MCQ', '[{"label": "A", "text": "2004-05"}, {"label": "B", "text": "2011-12"}, {"label": "C", "text": "2017-18"}, {"label": "D", "text": "2001"}]'::jsonb, 'B', 'CPI base often cited as 2011-12.', 'Economy', 'Inflation', 'MEDIUM', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('Who issues currency notes in India (except ₹1)?', 'MCQ', '[{"label": "A", "text": "Ministry of Finance"}, {"label": "B", "text": "RBI"}, {"label": "C", "text": "SBI"}, {"label": "D", "text": "NABARD"}]'::jsonb, 'B', 'RBI issues notes.', 'Banking Awareness', 'Currency', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('KYC stands for:', 'MCQ', '[{"label": "A", "text": "Know Your Customer"}, {"label": "B", "text": "Keep Your Cash"}, {"label": "C", "text": "Key Yield Curve"}, {"label": "D", "text": "Know Your Credit"}]'::jsonb, 'A', 'Know Your Customer.', 'Banking Awareness', 'Compliance', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('MSME stands for:', 'MCQ', '[{"label": "A", "text": "Micro Small Medium Enterprises"}, {"label": "B", "text": "Main State Market Exchange"}, {"label": "C", "text": "Monetary Supply Measure Estimate"}, {"label": "D", "text": "None"}]'::jsonb, 'A', 'Micro, Small and Medium Enterprises.', 'Economy', 'Industry', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('A cheque is valid for how many months from date of issue (usual)?', 'MCQ', '[{"label": "A", "text": "1"}, {"label": "B", "text": "3"}, {"label": "C", "text": "6"}, {"label": "D", "text": "12"}]'::jsonb, 'B', 'Generally 3 months.', 'Banking Awareness', 'Negotiable Instruments', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('SLR stands for:', 'MCQ', '[{"label": "A", "text": "Statutory Liquidity Ratio"}, {"label": "B", "text": "System Loan Rate"}, {"label": "C", "text": "Secure Lending Rule"}, {"label": "D", "text": "State Liquidity Reserve"}]'::jsonb, 'A', 'Statutory Liquidity Ratio.', 'Banking Awareness', 'RBI', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('UPI was launched by:', 'MCQ', '[{"label": "A", "text": "RBI"}, {"label": "B", "text": "NPCI"}, {"label": "C", "text": "SEBI"}, {"label": "D", "text": "SBI"}]'::jsonb, 'B', 'National Payments Corporation of India.', 'Banking Awareness', 'Payments', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false),
('Inflation means:', 'MCQ', '[{"label": "A", "text": "Fall in prices"}, {"label": "B", "text": "Rise in general price level"}, {"label": "C", "text": "Rise in employment"}, {"label": "D", "text": "Fall in money supply"}]'::jsonb, 'B', 'General price level rise.', 'Economy', 'Inflation', 'EASY', 1, 0.25, 'Banking (IBPS/SBI/RBI)', 2024, 'OFFICIAL_PYP', true, true, false)
) AS v(
  question_text text, question_type text, options jsonb, correct_answer text, explanation text,
  subject text, topic text, difficulty text, marks_positive numeric, marks_negative numeric,
  exam_type text, source_year int, source text, is_verified boolean, is_public boolean, latex_present boolean
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.questions q
  WHERE q.question_text = v.question_text AND COALESCE(q.exam_type, '') = COALESCE(v.exam_type, '')
);

INSERT INTO public.exam_papers (exam_type, exam_name, year, total_questions, duration_minutes, difficulty_level)
SELECT v.exam_type, v.exam_name, v.year, v.total_questions, v.duration_minutes, v.difficulty_level
FROM (VALUES
  ('JEE Main', 'JEE Main', 2024, 90, 180, 'MEDIUM'),
  ('NEET UG', 'NEET UG', 2024, 180, 200, 'MEDIUM'),
  ('UPSC CSE', 'UPSC CSE', 2024, 100, 120, 'HARD'),
  ('SSC Exams (CGL/CHSL)', 'SSC CGL', 2024, 100, 60, 'MEDIUM'),
  ('Banking (IBPS/SBI/RBI)', 'IBPS PO', 2024, 100, 60, 'MEDIUM')
) AS v(exam_type, exam_name, year, total_questions, duration_minutes, difficulty_level)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exam_papers ep
  WHERE ep.exam_type = v.exam_type AND ep.year = v.year
);

